### ISSUE TITLE
Enhancement: Malware check for all URL / Domain / IP

### ISSUE THREAD

**Issue by anantshri** [ajinabraham/Mobile-Security-Framework-MobSF#100]
we can run Safe Browsing API check for all URL's identified

https://developers.google.com/safe-browsing/
https://tech.yandex.com/safebrowsing/

**Comment by ajinabraham** [comment]
Already in pipeline. I have a list of known bad domains and IPs as well. Most of the things needed are already available in my previous project.
https://drive.google.com/open?id=0B_Ci-1YbMqshQWl3NWRlbXE5em8

**Comment by ajinabraham** [comment]
http://www.malwaredomainlist.com/forums/index.php?topic=3270.0 added on latest commit.
Will be released with v0.9.3 Beta
