### ISSUE TITLE
App crashed in Dynamic Analyzer

### ISSUE THREAD

**Issue by difcareer** [ajinabraham/Mobile-Security-Framework-MobSF#101]
Hi:

I upload several apps for Dynamic Analyze,  They are all crashed. (Even through I click the lauch icon).

I look at the logcat log and got this:

I/ActivityManager(  728): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.xxx.yyy/.AppEnterActivity} from pid 958
I/DEBUG   (  110):     eax 0f861226  ebx 000019f0  ecx 949efd01  edx 00000000
I/DEBUG   (  110):     esi 00000000  edi b4f0871c
I/DEBUG   (  110):     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000000  xss 0000007b
I/DEBUG   (  110):     eip 948ab751  ebp bfdeac58  esp bfdeac30  flags 00210246
I/DEBUG   (  110): 
I/DEBUG   (  110): backtrace:
I/DEBUG   (  110):     #00  pc 000e8751  /system/lib/libhoudini.so
I/DEBUG   (  110):     #01  pc 000e66ea  /system/lib/libhoudini.so
I/DEBUG   (  110):     #02  pc 000e8aaa  /system/lib/libhoudini.so
I/DEBUG   (  110):     #03  pc 000bfcfc  /system/lib/libhoudini.so
I/DEBUG   (  110):     #04  pc 000e6cc2  /system/lib/libhoudini.so (dvm2hdInit+18)
I/DEBUG   (  110):     #05  pc 001769b7  /system/lib/libdvm.so (houdini::hookDlopen(char const*, int, bool*)+343)
I/DEBUG   (  110):     #06  pc 0008bd6f  /system/lib/libdvm.so (dvmLoadNativeCode(char const*, Object*, char**)+719)
I/DEBUG   (  110):     #07  pc 000ceb1b  /system/lib/libdvm.so (Dalvik_java_lang_Runtime_nativeLoad(unsigned int const*, JValue*)+139)
I/DEBUG   (  110):     #08  pc 00177618  /system/lib/libdvm.so
I/DEBUG   (  110):     #09  pc 00005a0b  <unknown>
I/DEBUG   (  110):     #10  pc 0003b962  /system/lib/libdvm.so (dvmMterpStd(Thread*)+66)
I/DEBUG   (  110):     #11  pc 00037029  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+217)
I/DEBUG   (  110):     #12  pc 000bd097  /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, char*)+759)
I/DEBUG   (  110):     #13  pc 000bd4a7  /system/lib/libdvm.so (dvmCallMethod(Thread*, Method const*, Object*, JValue*, ...)+55)
I/DEBUG   (  110):     #14  pc 000dd922  /system/lib/libdvm.so (dvmInitClass+1458)
I/DEBUG   (  110):     #15  pc 000e0379  /system/lib/libdvm.so (dvmResolveMethod+329)
I/DEBUG   (  110):     #16  pc 0002c446  /system/lib/libdvm.so
I/DEBUG   (  110):     #17  pc 00025857  /dev/ashmem/dalvik-heap (deleted)
I/DEBUG   (  110):     #18  pc 0003b962  /system/lib/libdvm.so (dvmMterpStd(Thread*)+66)
I/DEBUG   (  110):     #19  pc 00037029  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+217)
I/DEBUG   (  110):     #20  pc 000bd097  /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, char*)+759)
I/DEBUG   (  110):     #21  pc 000bd4a7  /system/lib/libdvm.so (dvmCallMethod(Thread*, Method const*, Object*, JValue*, ...)+55)
I/DEBUG   (  110):     #22  pc 000dd922  /system/lib/libdvm.so (dvmInitClass+1458)
I/DEBUG   (  110):     #23  pc 000e0379  /system/lib/libdvm.so (dvmResolveMethod+329)
I/DEBUG   (  110):     #24  pc 0002c446  /system/lib/libdvm.so
I/DEBUG   (  110):     #25  pc 0007dd9f  /dev/ashmem/dalvik-heap (deleted)
I/DEBUG   (  110):     #26  pc 0003b962  /system/lib/libdvm.so (dvmMterpStd(Thread*)+66)
I/DEBUG   (  110):     #27  pc 00037029  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+217)
I/DEBUG   (  110):     #28  pc 000bc236  /system/lib/libdvm.so (dvmInvokeMethod(Object*, Method const*, ArrayObject*, ArrayObject*, ClassObject*, bool)+1750)
I/DEBUG   (  110):     #29  pc 00003e8d  /system/bin/app_process
I/DEBUG   (  110):     #30  pc 00177618  /system/lib/libdvm.so
I/DEBUG   (  110):     #31  pc 00005cff  <unknown>
I/DEBUG   (  110): 
I/DEBUG   (  110): stack:
I/DEBUG   (  110):          bfdeace0  b77a0000  /system/bin/linker
I/DEBUG   (  110):          bfdeace4  b4f0f1d9  /system/lib/libdvm.so
I/DEBUG   (  110):          bfdeace8  b7727689  /system/lib/libc.so (__system_property_get+9)
I/DEBUG   (  110):          bfdeacec  b769be58  /system/lib/libcutils.so
I/DEBUG   (  110):          bfdeacf0  98bacd54  
I/DEBUG   (  110):          bfdeacf4  94b3c9c0  
I/DEBUG   (  110):          bfdeacf8  bfdead18  [stack]
I/DEBUG   (  110):          bfdeacfc  948a9cc3  /system/lib/libhoudini.so (dvm2hdInit+19)
I/DEBUG   (  110):          bfdead00  b4f0f1ad  /system/lib/libdvm.so
I/DEBUG   (  110):          bfdead04  bfdead50  [stack]
I/DEBUG   (  110):          bfdead08  00000000  
I/DEBUG   (  110):          bfdead0c  b4f55cb4  /system/lib/libdvm.so
I/DEBUG   (  110):          bfdead10  b4f0871c  /system/lib/libdvm.so
I/DEBUG   (  110):          bfdead14  b4f0871c  /system/lib/libdvm.so
I/DEBUG   (  110):          bfdead18  00000000  
I/DEBUG   (  110):          bfdead1c  b4f059b8  /system/lib/libdvm.so (houdini::hookDlopen(char const*, int, bool*)+344)
I/DEBUG   (  110):     #05  bfdead20  bfdead48  [stack]
I/DEBUG   (  110):          bfdead24  b4f0f1d9  /system/lib/libdvm.so
I/DEBUG   (  110):          bfdead28  b4f06bd5  /system/lib/libdvm.so
I/DEBUG   (  110):          bfdead2c  0007d770  
I/DEBUG   (  110):          bfdead30  00000010  
I/DEBUG   (  110):          bfdead34  b798ee40  [heap]
I/DEBUG   (  110):          bfdead38  b7aed2e8  [heap]
I/DEBUG   (  110):          bfdead3c  bfdeae1b  [stack]
I/DEBUG   (  110):          bfdead40  b4f55cb4  /system/lib/libdvm.so
I/DEBUG   (  110):          bfdead44  b4fc9c80  
I/DEBUG   (  110):          bfdead48  b76941d0  /system/lib/libcutils.so (__android_log_print)
I/DEBUG   (  110):          bfdead4c  b4f05850  /system/lib/libdvm.so (houdini::dvmGetMethodShorty(houdini::fake_Method const*))
I/DEBUG   (  110):          bfdead50  a5006e6f  /dev/ashmem/dalvik-zygote (deleted)
I/DEBUG   (  110):          bfdead54  00000000  
I/DEBUG   (  110):          bfdead58  b4dc5f59  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+9)
I/DEBUG   (  110):          bfdead5c  b4efa786  /system/lib/libdvm.so (dexProtoCompare(DexProto const*, DexProto const*)+246)
I/DEBUG   (  110):          ........  ........
I/DEBUG   (  110):     #06  bfdeadd0  b7aed2e8  [heap]
I/DEBUG   (  110):          bfdeadd4  00000001  
I/DEBUG   (  110):          bfdeadd8  bfdeae1b  [stack]
I/DEBUG   (  110):          bfdeaddc  b4e1a0f0  /system/lib/libdvm.so (hashcmpNameStr(void const*, void const*))
I/DEBUG   (  110):          bfdeade0  00000000  
I/DEBUG   (  110):          bfdeade4  b4f1e794  /system/lib/libdvm.so
I/DEBUG   (  110):          bfdeade8  00000018  
I/DEBUG   (  110):          bfdeadec  b7796f9a  /system/bin/linker (__dl_pthread_mutex_unlock+154)
I/DEBUG   (  110):          bfdeadf0  00000002  
I/DEBUG   (  110):          bfdeadf4  bfdeae2c  [stack]
I/DEBUG   (  110):          bfdeadf8  a507fcf0  /dev/ashmem/dalvik-heap (deleted)
I/DEBUG   (  110):          bfdeadfc  b7762f01  /system/lib/libc.so
I/DEBUG   (  110):          bfdeae00  bfdeae8c  [stack]
I/DEBUG   (  110):          bfdeae04  b7990f40  [heap]
I/DEBUG   (  110):          bfdeae08  0000002a  
I/DEBUG   (  110):          bfdeae0c  b76da455  /system/lib/libc.so (dlfree+885)
I/DEBUG   (  110):          ........  ........
I/DEBUG   (  110):     #07  bfdeae70  b7aed2e8  [heap]
I/DEBUG   (  110):          bfdeae74  a507fcf0  /dev/ashmem/dalvik-heap (deleted)
I/DEBUG   (  110):          bfdeae78  bfdeae8c  [stack]
I/DEBUG   (  110):          bfdeae7c  b4f55cb4  /system/lib/libdvm.so
I/DEBUG   (  110):          bfdeae80  9db7ebec  /data/dalvik-cache/system@framework@core.jar@classes.dex
I/DEBUG   (  110):          bfdeae84  a4d6f0e0  /dev/ashmem/dalvik-zygote (deleted)
I/DEBUG   (  110):          bfdeae88  b4e2d735  /system/lib/libdvm.so (dvmMarkCard(void const*)+5)
I/DEBUG   (  110):          bfdeae8c  00000000  
I/DEBUG   (  110):          bfdeae90  a50d44e8  /dev/ashmem/dalvik-heap (deleted)
I/DEBUG   (  110):          bfdeae94  00000001  
I/DEBUG   (  110):          bfdeae98  b4e229b9  /system/lib/libdvm.so (dvmLockObject+9)
I/DEBUG   (  110):          bfdeae9c  9ee16a0c  
I/DEBUG   (  110):          bfdeaea0  9db8baaa  /data/dalvik-cache/system@framework@core.jar@classes.dex
I/DEBUG   (  110):          bfdeaea4  9ee16a2c  
I/DEBUG   (  110):          bfdeaea8  bfdeaf28  [stack]
I/DEBUG   (  110):          bfdeaeac  b4f06619  /system/lib/libdvm.so

These Apps are all work fine in real phone.

Hope for a reply, thx!

**Comment by ajinabraham** [comment]
The app might have some Anti-VM or root detection code that can cause this.

**Comment by difcareer** [comment]
how could I bypass this problem without modify app? I think this is something with vm, will you slove this kind problem later?

**Comment by ajinabraham** [comment]
You can try with a real device then, Check: https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/wiki/1.-Documentation#configuring-rooted-android-devicecustom-vm-with-mobsf
