### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by adithyanaresh** [ajinabraham/Mobile-Security-Framework-MobSF#102]
Based on commercial tools out there, these additional things could be thought of in the later releases.

packet capturing
port scanning
MITM
A file tree and its contents in the rooted mobile device (basically /data/data)
memory dump
proxy
ssl strip

**Comment by ajinabraham** [comment]
* Packet Capturing was there initially but removed it in the beta version.
* Port Scanning in the sense could you elaborate more? the ports in the VM/device or the web server of the mobile Apps API?
* MITM - already in place
* Device File Browser - This is under development
* Memory Dump - Exploring the possiblity of this.
* Proxy - Already in place
* SSL Strip - Whats the use case?

**Comment by woodspeed** [comment]
Hi,

Just small tips/asks:

1. Can you add a button or a refresh if there is a "File format not Supported!" message?
It is a little bit annoying refreshing manually.

2. Can you also add the version number in the About menu?
When somebody found a bug, it would be easier to look for which version it was found.

**Comment by ajinabraham** [comment]
@woodspeed 

2. when you run MobSF, it shows version
```
python manage.py runserver


Mobile Security Framework v0.9.1 Beta

[INFO] Finding JDK Location in Linux/MAC....
```
