### ISSUE TITLE
Allow server to connect to the internet via a proxy

### ISSUE THREAD

**Issue by mrpinghe** [ajinabraham/Mobile-Security-Framework-MobSF#104]
Hi Ajin,

Is there currently a way to configure a upstream proxy on the server? For example, the VM is proxying its traffic to the server, and when I'm in a lab/intranet environment, I'd like the server to connect to the internet via a proxy, either picking up my "http_proxy" variable or letting me separately configure one.

Is it currently possible? If not, is this some feature you can add?

Thanks!!

**Comment by ajinabraham** [comment]
It is possible. The feature is available in NULLCON branch. This will be merged to master in few days. You can wait till then or c Lm

**Comment by mrpinghe** [comment]
Thank you! Good luck at Nullcon!
