### ISSUE TITLE
PDF Generate can't deal chinese  charactors rightly ?

### ISSUE THREAD

**Issue by xtxwy** [ajinabraham/Mobile-Security-Framework-MobSF#108]
In "def PDF" function...

**Comment by ajinabraham** [comment]
Looks like unicode problem to me. Try replacing this line
https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/blob/master/StaticAnalyzer/views.py#L136
`pdf = pisa.pisaDocument(StringIO( "{0}".format(html.encode('utf-8'))), result)`
with
`pdf = pisa.pisaDocument(StringIO( "{0}".format(html.encode('utf-8'))), result, encoding='utf-8')` in `StaticAnalyzer/views.py`

**Comment by ajinabraham** [comment]
let me know if this works.

**Comment by ajinabraham** [comment]
@xtxwy does that fix your problem?

**Comment by ajinabraham** [comment]
closing this bug due to lack of response.

**Comment by t880216t** [comment]
I use docker images from master and I also had this problem.
It look like a system error for ubuntu ,that it havn't  a Chinese  font,
if you use from docker ,do it like this:
`$ docker exec -it blissful_kowalevski /bin/sh` 
`# apt-get install -y --force-yes --no-install-recommends fonts-wqy-microhei`
`# apt-get install -y --force-yes --no-install-recommends ttf-wqy-zenhei`
it's usefull for me , try it.
