### ISSUE TITLE
DynamicAnalyzer  [Unfortunately **(the app's name) has stopped]

### ISSUE THREAD

**Issue by LFernandoC** [ajinabraham/Mobile-Security-Framework-MobSF#109]
The MobSF starts **.apk after it has been installed, but not succeed.
It shows " Unfortunately **(the app's name) has stopped." 
I do follows all steps you say.

the following are console log,it seems everything is ok?:

Restoring snapshot 33698d67-bfae-43c2-a97a-b660c6517805
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%

[INFO] VM Restore Snapshot
Waiting for VM "eb796362-eee1-421e-9c8d-e47ddc565036" to power on...
VM "eb796362-eee1-421e-9c8d-e47ddc565036" has been successfully started.

[INFO] VM Starting
[16/Mar/2016 06:32:15]"POST /DynamicAnalyzer/ HTTP/1.1" 200 30380
[16/Mar/2016 06:32:15]"GET /static/screen/screen.png HTTP/1.1" 404 1664

[INFO] Setting up Dynamic Analysis Environment

[INFO] Starting Web Proxy

[INFO] Started Web Proxy at 192.168.56.1:1337

[INFO] Starting App for Dynamic Analysis

[INFO] Getting ADB Location
* daemon not running. starting it now on port 5037 *
* daemon started successfully *

[INFO] ADB Started

[INFO] Waiting for 5 seconds...

[INFO] Connecting to VM/Device
connected to 192.168.56.101:5555

[INFO] Mounting

[INFO] Installing APK
7997 KB/s (15734827 bytes in 1.921s)
WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.
WARNING: linker: app_process has text relocations. This is wasting memory and is a security risk. Please fix.
	pkg: /data/local/tmp/c292bf1bd847e2046dd4a24c68bdeb95.apk
Success

[INFO] Launching APK Main Activity
WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.
WARNING: linker: app_process has text relocations. This is wasting memory and is a security risk. Please fix.
Starting: Intent { cmp=com.csii.tiannongshang.mobilebank/com.csii.mobilebank.FirstStartActivity }
[INFO] Testing Environment is Ready!

[INFO] Getting Screen Resolution

[INFO] Getting ADB Location
[16/Mar/2016 06:32:42]"POST /GetEnv/ HTTP/1.1" 200 65

[INFO] Getting ADB Location

[INFO] Installing MobSF RootCA
280 KB/s (1119 bytes in 0.003s)
[16/Mar/2016 06:32:42]"POST /MobSFCA/ HTTP/1.1" 200 19

**Comment by ajinabraham** [comment]
This is pretty is normal. This can happen due to a lot of reasons.
1. The app may not work in the VM due to some library issues.
2. The app might be using some sophisticated checks 

In such scenarios configure a different VM/Device with mobsfy.py script and do dynamic analysis over there.
