### ISSUE TITLE
failed to copy ca.crt

### ISSUE THREAD

**Issue by LFernandoC** [ajinabraham/Mobile-Security-Framework-MobSF#111]
first,thanks for your MobSF.I did this dynamic analysis with android device,
and when  i clicked "Finish" button on dynamic analysis page, it stuck ,the program just stopped there..

[INFO] Installing MobSF Root
failed to copy '/Users/fernando/MobSF/DynamicAnalyzer/pyWebProxy/ca.crt' to '/data/local/0025aabb.0': Permission denied
cp: /data/local/0025aabb.0: No such file or directory
rm failed for /data/local/0025aabb.0, No such file or directory
[19/Mar/2016 08:21:05]"POST /MobSFCA/ HTTP/1.1" 200 19

[INFO] Taking Screenshot

[INFO] Getting ADB Location
Error opening file: /data/local/screen.png (Permission denied)
remote object '/data/local/screen.png' does not exist

[INFO] Screenshot Taken
[19/Mar/2016 08:21:32]"POST /TakeScreenShot/ HTTP/1.1" 200 21

**Comment by LFernandoC** [comment]
I have solved this problem out，thank you

**Comment by rajath1989** [comment]
Hi LFernandoC,

Could you please elaborate how you could resolve this issue? I'm stuck on the same page.

**Comment by ajinabraham** [comment]
Did you followed this https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/wiki/2.-Configure-MobSF-Dynamic-Analysis-Environment-in-your-Android-Device-or-VM

**Comment by tachencko** [comment]
Hi guys!, I have same problem.

Error opening file: /data/local/screen.png (Permission denied)
