### ISSUE TITLE
Link provided into the documentation section for MobSF VM download not working

### ISSUE THREAD

**Issue by varshachavan15** [ajinabraham/Mobile-Security-Framework-MobSF#113]
Hi ajin,

I am unable to download the VM, can u please assist?

**Comment by ajinabraham** [comment]
working fine for me: https://docs.google.com/uc?id=0B_Ci-1YbMqshUnhHOU1LTDllRUE&export=download

**Comment by ajinabraham** [comment]
closing

**Comment by varshachavan15** [comment]
Thanks ajin its working
