### ISSUE TITLE
Cant start on REAL_DEVICE

### ISSUE THREAD

**Issue by aTastyCookie** [ajinabraham/Mobile-Security-Framework-MobSF#119]
Hi, 
Change install on device all apps from mobsfy.py, start ADB WIFI, MobSF/settings.py like

> REAL_DEVICE = True 
> DEVICE_IP = '192.168.88.34'
> DEVICE_ADB_PORT = 5555
> DEVICE_TIMEOUT = 300

But MobSF start VM and dont see device under WIFI.

> root@ddrt:/opt/mobsf# python manage.py runserver 666
> 
> 
> Mobile Security Framework v0.9.1 Beta
> 
> [INFO] Finding JDK Location in Linux/MAC....
> 
> [INFO] Oracle Java is installed!
> 
> [INFO] JDK 1.7 or above is available
> 
> [WARNING] Could not find VirtualBox path.
> 
> 
> Mobile Security Framework v0.9.1 Beta
> 
> [INFO] Finding JDK Location in Linux/MAC....
> 
> [INFO] Oracle Java is installed!
> 
> [INFO] JDK 1.7 or above is available
> 
> [WARNING] Could not find VirtualBox path.
> Performing system checks...
> 
> System check identified no issues (0 silenced).
> March 23, 2016 - 10:30:09
> Django version 1.8, using settings 'MobSF.settings'
> Starting development server at http://127.0.0.1:666/
> Quit the server with CONTROL-C.

![screenshot from 2016-03-23 13-31-48](https://cloud.githubusercontent.com/assets/2944373/13982529/b40ad196-f0fb-11e5-8bd7-5c9cc17f82e5.png)
![screenshot from 2016-03-23 13-34-04](https://cloud.githubusercontent.com/assets/2944373/13982581/ff8f6f96-f0fb-11e5-995a-2acde2638c12.png)

**Comment by ajinabraham** [comment]
This `[WARNING] Could not find VirtualBox path` is fine as MobSF will always check for VirtualBox path. I will track this as a bug. The fix will make sure that MobSF won't check for VirtualBox path if the settings is configured as `REAL_DEVICE

**Comment by ajinabraham** [comment]
Fixed https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/commit/99d1750a5a1dda35238acfdee31a1fe0b3461938
