### ISSUE TITLE
dynamic analysis with real device，something stuck

### ISSUE THREAD

**Issue by LFernandoC** [ajinabraham/Mobile-Security-Framework-MobSF#121]
I click "Finish" button ,and it got stuck without printing info..

[INFO] ADB Started

[INFO] Waiting for 5 seconds...

[INFO] Connecting to VM/Device
connected to 192.168.1.123:5555

[INFO] Mounting

[INFO] Installing APK
605 KB/s (10258457 bytes in 16.549s)
	pkg: /data/local/tmp/3a3263f3192019dbaa5946c78070bb83.apk
Success

[INFO] Launching APK Main Activity
Starting: Intent { cmp=com.nuomi/com.baidu.bainuo.splash.SplashActivity }
[INFO] Testing Environment is Ready!

[INFO] Getting Screen Resolution

[INFO] Getting ADB Location
[26/Mar/2016 06:33:43]"POST /GetEnv/ HTTP/1.1" 200 65

[INFO] Getting ADB Location

[INFO] Installing MobSF RootCA
25 KB/s (1119 bytes in 0.042s)
[26/Mar/2016 06:33:43]"POST /MobSFCA/ HTTP/1.1" 200 19

**Comment by ajinabraham** [comment]
There was a small bug in v0.9.0, make sure your are using v0.9.1 and is connected to Internet while doing the analysis

**Comment by ajinabraham** [comment]
Closing this. Reopen if this is not fixed.

**Comment by LFernandoC** [comment]
thanks ， the bug has been fixed~!
