### ISSUE TITLE
Can not run dynamic analysis in real device

### ISSUE THREAD

**Issue by Holalalee** [ajinabraham/Mobile-Security-Framework-MobSF#123]
I am new to MobSF,  now I can run static analyzer at http://127.0.0.1:8000/ in my laptop, but I got no idea to start dynamic analyzer, I have followed the steps to configure MobSF Dynamic analysis environment in my device, and below is my settings in MobSF, please advise me how to perform dynamic analyzer, thanks

#===============DEVICE Settings=================
REAL_DEVICE = True
DEVICE_IP = '10.4.0.235'
DEVICE_ADB_PORT = 5555
DEVICE_TIMEOUT = 300
#===============================================

#================VM SETTINGS ==================
#VBoxManage showhdinfo "MobSF_VM_0.1-disk3.vdi"
#VM UUID
UUID='614ed770-9c61-4543-8a7a-5330f4ae7847'
#Snapshot UUID
SUUID='d99eafb6-ae09-4b6d-9e7d-91f48b0de49b'
#IP of the MobSF VM
VM_IP='192.168.56.101'
VM_ADB_PORT = 5555
VM_TIMEOUT = 100
#=============================================

#================HOST/PROXY SETTINGS ===========
PROXY_IP='10.4.0.75' #Host/Server/Proxy IP
PORT=1337 #Proxy Port
ROOT_CA='0025aabb.0'

SCREEN_IP = PROXY_IP #ScreenCast IP
SCREEN_PORT = 9339 #ScreenCast Port
#===============================================

**Comment by ajinabraham** [comment]
Settings looks good to me. Have run the mobsfy.py script to setup Dynamic Analysis environment in your device? 
https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/wiki/2.-Configure-MobSF-Dynamic-Analysis-Environment-in-your-Android-Device-or-VM

**Comment by Holalalee** [comment]
Yes, I run the mobsfy.py and enable all three modules and enabled WiFi ADB, I can enter adb shell from windows CMD, 


[INFO] Finding JDK Location in Windows....

[INFO] Multiple JDK Instances Identified. Looking for JDK 1.7 or above

[INFO] Oracle Java (JDK >= 1.7) is installed!
Performing system checks...

System check identified no issues (0 silenced).
March 31, 2016 - 17:38:02
Django version 1.8, using settings 'MobSF.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

is below link correct for entering dynamicanalyzer webpage??
http://127.0.0.1:8000/DynamicAnalyzer

if YES, I got below error code 

[INFO] Dynamic Analysis Started
[31/Mar/2016 17:38:46]"GET /DynamicAnalyzer/ HTTP/1.1" 302 0
[31/Mar/2016 17:38:46]"GET /error/ HTTP/1.1" 200 4602

**Comment by ajinabraham** [comment]
You are not supposed to hit that URL directly to access DynamicAnalzyer

**Comment by ajinabraham** [comment]
Do a static Analysis and from there click on the Dynamic Analyzer button

**Comment by Holalalee** [comment]
Yes, thanks so much, now I can enter Dynamic Analyzer after pressed the button, it's awesome.
