### ISSUE TITLE
Anything need to setup first before pressing Start Web API Fuzzer button 

### ISSUE THREAD

**Issue by Holalalee** [ajinabraham/Mobile-Security-Framework-MobSF#124]
hi, 
I have no ideas to start wep api testing, after I pressed Start Web API Fuzzer button I got below error information, please advise me which steps I need to setup first before testing, I can not find any useful information from Internet, thanks a lot.

ImportError at /APIFuzzer
No module named lxml
Request Method:	GET
Request URL:	http://127.0.0.1:8000/APIFuzzer?md5=746a8aaa7bd98a7539525ba795e041fa
Django Version:	1.8
Exception Type:	ImportError
Exception Value:	
No module named lxml
Exception Location:	C:\MobSF\APITester\views.py in <module>, line 17
Python Executable:	C:\Python27\python.exe
Python Version:	2.7.11
Python Path:	
['C:\\MobSF',
 'C:\\WINDOWS\\SYSTEM32\\python27.zip',
 'C:\\Python27\\DLLs',
 'C:\\Python27\\lib',
 'C:\\Python27\\lib\\plat-win',
 'C:\\Python27\\lib\\lib-tk',
 'C:\\Python27',
 'C:\\Python27\\lib\\site-packages']

**Comment by ajinabraham** [comment]
You don't have lxml module. 
Install the python lxml module
