### ISSUE TITLE
Dynamic Analysis Error

### ISSUE THREAD

**Issue by brsgdc** [ajinabraham/Mobile-Security-Framework-MobSF#127]
Hello,

I got these error messages when I run dynamic analysis.

**Comment by brsgdc** [comment]
![selection_001](https://cloud.githubusercontent.com/assets/5054820/14534501/2444bbde-0272-11e6-9501-41408c235e2f.png)

**Comment by ajinabraham** [comment]
Can try this and let me know it it works

got to MobSF root directory and run the command

 `chmod -R a+x *`

see if that fixes the errors. 
Also make sure you have necessary files here : https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/tree/master/DynamicAnalyzer/tools/adb

**Comment by brsgdc** [comment]
I tried that command but no work. Also, I have installed adb shell. Any different idea for solution ?

**Comment by brsgdc** [comment]
I added logs file.



[logs.zip](https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/files/219582/logs.zip)

**Comment by brsgdc** [comment]
I don't understand. What's wrong. It is working on my second pc well with same settings.

**Comment by ajinabraham** [comment]
Can you try these

go to `/home/baris/Tools/Mobile-Security-Framework-MobSF/DynamicAnalyzer/tools/adb/linux/` 
and try executing `./adb`
Please note that you have to try `./adb` and not `adb`

See if you can get the default adb output.

Another thing to try is to change this function here https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/blob/master/DynamicAnalyzer/views.py#L573-L590

from 

```
def getADB(TOOLSDIR):
    print "\n[INFO] Getting ADB Location"
    try:
        adb='adb'
        if platform.system()=="Darwin":
            adb_dir=os.path.join(TOOLSDIR, 'adb/mac/')
            subprocess.call(["chmod", "777", adb_dir])
            adb=os.path.join(TOOLSDIR , 'adb/mac/adb')
        elif platform.system()=="Linux":
            adb_dir=os.path.join(TOOLSDIR, 'adb/linux/')
            subprocess.call(["chmod", "777", adb_dir])
            adb=os.path.join(TOOLSDIR , 'adb/linux/adb')
        elif platform.system()=="Windows":
            adb=os.path.join(TOOLSDIR , 'adb/windows/adb.exe')
        return adb
    except:
        PrintException("[ERROR] Getting ADB Location")
        return "adb"
```

to this

```
def getADB(TOOLSDIR):
    return "adb"
```

Let me know the outcomes.

**Comment by brsgdc** [comment]
The output is "bash: ./adb: No such file or director"

**Comment by ajinabraham** [comment]
Oh that means adb binary is not suitable with the linux distro you are using. Download adb that is suitable for your Linux and put it along with the supporting files to `/DynamicAnalyzer/tools/adb/linux/`

**Comment by brsgdc** [comment]
I fixed it with installing `sudo apt-get install lib32stdc++6`

**Comment by SkPratihar1** [comment]
![image](https://user-images.githubusercontent.com/107917285/191971452-17d03632-6bc8-403a-8613-908a38f644dd.png)
 how to solve in emulator
