### ISSUE TITLE
Host only adapter name

### ISSUE THREAD

**Issue by xghrtkl** [ajinabraham/Mobile-Security-Framework-MobSF#128]
Hi,

When i follow guidance to import ova file (https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/wiki/1.-Documentation), i got stuck on setting up the network, i cannot choose the name of the adapter? I didnt change anything after import, i just make sure that adapter1 set to Host-only Adapter, and adapter 2 set to NAT.

I tried to re-import the file so many times but it cannot work, once i choose "internal network" and type custom adapter name, i have IP: 10.0.x.x? I tried to run the ova file on vmware but it cannot import due to invalid type. Could someone help me on this issue please? Thank you in advance.

ps: i already use virtualbox many times, and yes i can run another VM normaly and yes i can connect to the another VM, also can access internet from the another VM

**Comment by ajinabraham** [comment]
What options do you have under "Attached to:" in Adapter1 or Adapter2 tab in Network section of VirtualBox?

**Comment by ajinabraham** [comment]
This could be a VirtualBox problem. Please open the issue in VirtualBox forum
