### ISSUE TITLE
Filename and extension bugs

### ISSUE THREAD

**Issue by woodspeed** [ajinabraham/Mobile-Security-Framework-MobSF#129]
1. If you upload the following app https://apkpure.com/id%C5%91k%C3%A9p/hu.idokep.idokep you wil get the following error: [ERROR] Uploading File: (/MobSF/MobSF/views.py, LINE 49 "print "[INFO] MIME Type: " + file_type + " FILE: " + str(request.FILES['file'].name)"): 'ascii' codec can't encode character u'\u0151' in position 2: ordinal not in range(128)

2. If the file extension is APK you will get the following message: "File format not Supported!" If you rename the extension to apk, it will work.

The README.md contiains: Version: v0.9.1 beta

**Comment by ajinabraham** [comment]
Unicode problem. Try renaming your apk to some English name.
I will fix the second thing, the problem with upper case extensions.

**Comment by ajinabraham** [comment]
Fixed the upper case extension problem on latest commit
