### ISSUE TITLE
 Data storage outside of code repository directory.

### ISSUE THREAD

**Issue by anantshri** [ajinabraham/Mobile-Security-Framework-MobSF#130]
Can we try to ensure that all user uploaded / created data is kept away from code repository.
We can select a location such as HOME_DIRECTORY/.mobsf/ and use it for all functionalities.
This can also allow us to run mobsf multiple instances per user and each maintaining there own data.

Right now there is a temp fix implemented on an older codebase on MobSF for AndroidTamer here : https://github.com/AndroidTamer/Mobile-Security-Framework-MobSF/commit/4badfd7644dbad952abeaeeacce39494170b778d

**Comment by ajinabraham** [comment]
Will investigate and test this on multiple platforms and come up with a conclusion.

**Comment by ajinabraham** [comment]
Moving uploads and database to Home directory is fine. but downloads can not be moved as this is a web framework.

**Comment by ajinabraham** [comment]
checking if downloads can be moved to a static location

**Comment by ajinabraham** [comment]
I found an alternate way to do this

**Comment by ajinabraham** [comment]
This is done!
https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/tree/0.9.2
Needs to be tested across multiple platforms before merging to master.
