### ISSUE TITLE
Android: permission mapping

### ISSUE THREAD

**Issue by ajinabraham** [ajinabraham/Mobile-Security-Framework-MobSF#133]
https://github.com/LifeForm-Labs/lobotomy/blob/71d7ef019d7b172dfef5a2aac84b04823ad1ddec/framework/brains/apk/enumeration/api/enum.py

**Comment by ajinabraham** [comment]
This is very primitive, Need a better list

**Comment by matandobr** [comment]
What did you mean here?

**Comment by ajinabraham** [comment]
Map Permission usage to code.
