### ISSUE TITLE
Some code is not available in /MobSF/java.py so that it cause some problems when I installed

### ISSUE THREAD

**Issue by LeeHDsniper** [ajinabraham/Mobile-Security-Framework-MobSF#134]
After I installed all requirements,I run this command as readme.md said.`python manage.py runserver`
I got two error tips:
`[2016-04-27 07:07:30]
[ERROR] Finding Java path - Cannot Run Process (/home/marine/MobSF/MobSF/java.py, LINE 65 "proc = subprocess.Popen(args,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,)"): [Errno 2] No such file or directory

[2016-04-27 07:07:30]
[ERROR] Oracle Java JDK 1.7 or above is not found! (/home/marine/MobSF/MobSF/settings.py, LINE 28 "SECRET_KEY = open(SECRET_FILE).read().strip()"): [Errno 2] No such file or directory: '/home/marine/MobSF/MobSF/secret'`
Then I checked code in  java.py,and I don't think this paragraph is not available for most situation:

......snap line 41 .......
else:
			print "\n[INFO] Finding JDK Location in Linux/MAC...."
			MAC_LINUX_JAVA="/usr/bin/"
			args=[MAC_LINUX_JAVA+"java"]
			dat=RunProcess(args)
			if "oracle" in dat:
				print "\n[INFO] Oracle Java is installed!"
				args=[MAC_LINUX_JAVA+"java", '-version']
				dat=RunProcess(args)
				f_line=dat.split("\n")[0]
				if  re.findall(JAVA_VER,f_line):
					print "\n[INFO] JDK 1.7 or above is available"
					return MAC_LINUX_JAVA
				else:
					PrintException("[ERROR] Please install Oracle JDK 1.7 or above")
					return ""
			else:
				PrintException("[ERROR] Oracle Java JDK 1.7 or above is not found!")
				return ""

I don't think every user will install java at "/usr/bin/" definately.People will create or move a file directory like "jdk1.8.0_91" at /usr/bin commonly.
I think read file "/etc/environment" to find java is a good idea here.
Another problem is if args which will be used at method "subprocess.Popen()" is a list,it will occur a error.I don't know the reason of this error ,but I modified the method "RunProcess()".Actually I just change args to a string,and declare "shell=True" which is  a parameter  subprocess.Popen
At last. I modified java.py  to let it work:

import subprocess,platform,re,os
from MobSF.exception_printer import PrintException
#Maintain JDK Version
JAVA_VER='1.7|1.8|1.9|2.0|2.1|2.2|2.3'
def FindJava():
	try:
		if platform.system()=="Windows":
			print "\n[INFO] Finding JDK Location in Windows...."
			WIN_JAVA_LIST=["C:/Program Files/Java/","C:/Program Files (x86)/Java/"] #JDK 7 jdk1.7.0_17/bin/
			for WIN_JAVA_BASE in WIN_JAVA_LIST:
				JDK=[]
				for dirname in os.listdir(WIN_JAVA_BASE):
					if "jdk" in dirname:
						JDK.append(dirname)
				if len(JDK)==1:
					print "\n[INFO] Oracle JDK Identified. Looking for JDK 1.7 or above"
					j=''.join(JDK)
					if re.findall(JAVA_VER,j):
						WIN_JAVA=WIN_JAVA_BASE+j+"/bin/"
						args=[WIN_JAVA+"java"]
						dat=RunProcess(args)
						if "oracle" in dat:
							print "\n[INFO] Oracle Java (JDK >= 1.7) is installed!"
							return WIN_JAVA
				elif len(JDK)>1:
					print "\n[INFO] Multiple JDK Instances Identified. Looking for JDK 1.7 or above"
					for j in JDK:
						if re.findall(JAVA_VER,j):
							WIN_JAVA=WIN_JAVA_BASE+j+"/bin/"
							break
						else:
							WIN_JAVA=""
					if len(WIN_JAVA)>1:
						args=[WIN_JAVA+"java"]
						dat=RunProcess(args)
						if "oracle" in dat:
							print "\n[INFO] Oracle Java (JDK >= 1.7) is installed!"
							return WIN_JAVA
			PrintException("[ERROR] Oracle JDK 1.7 or above is not found!")
			return ""
		else:
			print "\n[INFO] Finding JDK Location in Linux/MAC...."
			MAC_LINUX_JAVA="/usr/bin/jdk1.8.0_91/bin"
			args=MAC_LINUX_JAVA+"/java"
			dat=RunProcess(args)
			if "oracle" in dat:
				print "\n[INFO] Oracle Java is installed!"
				args=MAC_LINUX_JAVA+"/java"+' -version'
				dat=RunProcess(args)
				print "\n"+dat
				f_line=dat.split("\n")[0]
				if  re.findall(JAVA_VER,f_line):
					print "\n[INFO] JDK 1.7 or above is available"
					return MAC_LINUX_JAVA
				else:
					PrintException("[ERROR] Please install Oracle JDK 1.7 or above")
					return ""
			else:
				PrintException("[ERROR] Oracle Java JDK 1.7 or above is not found!")
				return ""
	except:
		PrintException("[ERROR] Oracle Java (JDK >=1.7) is not found!")
		return ""
def RunProcess(args):
	try:
		proc = subprocess.Popen(args,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,shell=True)
		dat=''
		while True:
			line = proc.stdout.readline()\

			if not line:
				break
			dat+=line
		return dat
	except:
		PrintException("[ERROR] Finding Java path - Cannot Run Process")
		return ""

I am glad to see the author can fix this problem.

**Comment by ajinabraham** [comment]
I had tested the script on Mac OSX, Windows 10 and Ubuntu 14.05.
It works without any issues. 

You have to install oracle java and configure it as the default java
http://ubuntuhandbook.org/index.php/2014/09/install-oracle-java-ubuntu-1410/
once that is done, it should be available in `/urs/bin/`
