### ISSUE TITLE
Framework: Move from Debug Mode to Production

### ISSUE THREAD

**Issue by ajinabraham** [ajinabraham/Mobile-Security-Framework-MobSF#136]

**Comment by anantshri** [comment]
What all changes do you plan to do with this. 

I suppose one of the changes you had in mind was to use mysql instead of sqlite3 i would suggest making this a user configurable option.

**Comment by ajinabraham** [comment]
Will follow most of the things https://docs.djangoproject.com/ja/1.9/howto/deployment/checklist/
* Some security additions that to protect the framework

**Comment by bugwrangler** [comment]
I had used MOB SF with Mysql, found lots of DB structure issue. 
PostgreSQL is working awesome, I have been using since last 6 months. I belive PGSQL is bettern compare to MySQL.

**Comment by bugwrangler** [comment]
Django model is awesome and working excellent with small change. 

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'myproject',
        'USER': 'myprojectuser',
        'PASSWORD': 'password',
        'HOST': 'localhost',
        'PORT': '',
    }

**Comment by ajinabraham** [comment]
This is completely upto user. 
Since I want to provide everything in bundled form without much dependencies, I will go forward with sqlite. 

But probably It will be good to document on how to configure with postgresql with MobSF and yeah django itself is not suggesting mysql.

**Comment by DinaHkr** [comment]
Hi i got this error when i tried to configure on my lap may i know what is the reason ? ..
![mobsf](https://cloud.githubusercontent.com/assets/22589368/19104449/281cd618-8afa-11e6-8eda-daafb12bf22c.JPG)

**Comment by ajinabraham** [comment]
Have a look into: https://www.digitalocean.com/community/tutorials/how-to-use-postgresql-with-your-django-application-on-ubuntu-14-04

**Comment by DinaHkr** [comment]
Hi Ajin thank you its worked . . 

one more query how to access mobsf with locally,Righnow i can access in my pc it has ipaddress:portnumber i can not able to access this to another system can you guide how to accesss with that . .

**Comment by ajinabraham** [comment]
`python manage.py runserver 0.0.0.0:8000`
will expose it to public IP. You can access it like `http://<LAN_IP>:8000/`

**Comment by DinaHkr** [comment]
Hi ajin 

Thank you works perfect ..
