### ISSUE TITLE
Framework: giving already existing tools precedence

### ISSUE THREAD

**Issue by anantshri** [ajinabraham/Mobile-Security-Framework-MobSF#138]
At this point MobSF assumes user will not have a specific tool installed and always keep a copy of specific tool and use it including setting permissions to 755 everytime. however this is something which might not be required if the user already has the tools. 

Ideally what i would expect is if i have enjarify or simmilar tools installed MobSF respect it and let me use them for all work. I may have specifically customized enjarify to cover scenario's or i may have more up to date version of a specific package. So i would assume if the tool is found in path MobSF uses it if its > version in use within mobsf and if less then stick with mobsf version.

This should be easy to achieve if we check path for tools before adding new path and then if tool found in path a version check with version number stored in the config.

**Comment by ajinabraham** [comment]
To make things simpler.

User can specify path to tools in settings.py
if not found, MobSF will rollback to inbuilt versions

**Comment by anantshri** [comment]
One request can we make sure we have sample entries in settings.py either pointing to inbuilt version or a commented out entry so that user knows that this option exists. 
P.S. I know we can do the documentation and user should read the documentation but large number of userbase will directly go to settings file and will do whatever is required / stated and will not bother to read about it

**Comment by ajinabraham** [comment]
added

**Comment by anantshri** [comment]
So Now we have option to specify custom binary path's however interestingly enough even if no path is provided but existing binary is present it is used in case your self provided binary can't get execute rights. Why don't we just check if binary is in path without adding your custom path's then we don't do the chmod steps. What do you say?

**Comment by ajinabraham** [comment]
I couldn't grab that. Can you elaborate ?
