### ISSUE TITLE
Framework: Moving Setting's File outside of Gitcode

### ISSUE THREAD

**Issue by anantshri** [ajinabraham/Mobile-Security-Framework-MobSF#139]
Like all setting files the settings.py of this project too is something very very system specific and hence i would recommend keeping it out of code repo and generate it on first run. and with https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/issues/130 in mind might be a good idea to place the settings.py in user controlled directory. 

May be you might want to use a ini or simmilar format for settings which is then loaded by settings.py when its run but giving customized per user settings should be one of the items in list.

**Comment by ajinabraham** [comment]
I don't like the idea of moving a setting file.

But you can load a different settings file like 

`python manage.py runserver 8001 --settings=<settings>`

**Comment by ajinabraham** [comment]
Having that feature implemented will affect the default documentation, and will make the `settings.py` look more like a python code file.

**Comment by ajinabraham** [comment]
I think some settings can be loaded from home dir

**Comment by ajinabraham** [comment]
Added
https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/pull/137/commits/16d587f96acbd8999eabfea5ea91b51df1de9825

I made it this way.

Settings is divided into 
* mobsf framework configuration - framework related configs can only be changed through editing `MobSF/settings.py` that will affect all users.
* mobsf user configuration - user related configs can be changed by modifying the user config section in `MobSF/settings.py` or by modifying `<HOM_DIR>/.MobSF/config.py` if MobSF is configured to support HOME_DIR mode . Any errors in loading config.py will fallback to default user config from `MobSF/settings.py`

By default MobSF will be shipped in self contained mode.
HOME_DIR mode can be enabled by setting https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/blob/0.9.2/MobSF/settings.py#L25 to `True` 
This will create the db, secret, uploads, downloads, logs,  in .MobSF directory under user's home directory.
This will also generate `config.py` in .MobSF directory with predefined settings from `settings.py`
User can change that later to change certain user configurations for him.

**Comment by anantshri** [comment]
Awesome this save a lot of my repackaging time. So all i need to do is change line25 to True and i am good to go. Thanks for a quick closure of this issue.

**Comment by ajinabraham** [comment]
Yep that's all!

**Comment by ajinabraham** [comment]
It would be great if you can test it.
Testing is pending on Linux and Windows
