### ISSUE TITLE
UI needs to be adjusted for the reporting - content gets out from table view

### ISSUE THREAD

**Issue by bugwrangler** [ajinabraham/Mobile-Security-Framework-MobSF#14]
![image](https://cloud.githubusercontent.com/assets/6933052/7135139/620c2014-e2c1-11e4-8a49-045e2cb4c589.png)

**Comment by ajinabraham** [comment]
Not the final UI. Will be working with an UI expert to adjust the same.

**Comment by bugwrangler** [comment]
Cool, no worries

**Comment by ajinabraham** [comment]
fixed in nullcon branch
