### ISSUE TITLE
Keeping MobSF up to date

### ISSUE THREAD

**Issue by koehntopp** [ajinabraham/Mobile-Security-Framework-MobSF#141]
Hi Ajin,
can you please add a section to the guide on how to update? If I do a git pull it will fail due to changes is settings.py (my VM UUID) and db.sqlite3
Thanks!

**Comment by ajinabraham** [comment]
"How to update" will be added on v0.9.2 release.
From v0.9.2, you should be able to move all your Database file and user configurations in settings to Home dir. 

alternately for now you can do

```
git stash
git pull
git stash pop
```

**Comment by koehntopp** [comment]
Wow you're fast ;)

Thanks!
