### ISSUE TITLE
USE_HOME Test 

### ISSUE THREAD

**Issue by anantshri** [ajinabraham/Mobile-Security-Framework-MobSF#145]
OS: Linux
USE_HOME: True
MobSF code is in a directory non writable by the user running the code.

Error
```
[2016-05-07 20:35:33]
[ERROR] Malware DB Update (/usr/share/MobSF/MalwareAnalyzer/views.py, LINE 21 "os.makedirs(TMP_DIR)"): [Errno 13] Permission denied: '/usr/share/MobSF/MalwareAnalyzer/malwaredb/tmp/'
```
If this is just tmp why are we not leverage OS specific temp locations like %TEMP% in windows and /tmp in linux

**Comment by anantshri** [comment]
Second Issue:
same setup as above
dynamic testing
When testing is stopped

```
[INFO] Waiting for TAR dump to complete...

[INFO] Dumping Application Files from Device/VM
remote object '/data/local/jakhar.aseem.diva.tar' does not exist
```

Looks like tar is not created by data dumper. any ways we can debug this.

**Comment by ajinabraham** [comment]
@anantshri  The first one is happening as you don't have permissions in MobSF dir.
MobSF expects read, write and execute permission there as it supports self contained mode by default than using home dir. But I think it's reasonable to use the os provided temp dirs/files.

**Comment by ajinabraham** [comment]
checking into second issue

**Comment by anantshri** [comment]
Thats' the surprising path coz i have set USE_HOME to true and then i expect all read write operations on my home directory and not the directory. 

On second issue if it helps i did following.
1) Marked REAL DEVICE
2) REAL DEVICE is actually a genymotion instance running on a different computer.

**Comment by ajinabraham** [comment]
The tempfile will be moved to os provided paths so that the issue won't happen in future. HOME_DIR concept is only to accomodate user specific files and settings. The framework specific settings and files are still self contained. So I would recommend to give needed permissions.

**Comment by ajinabraham** [comment]
The second one, I am debugging

**Comment by ajinabraham** [comment]
For second issue, it's working fine for me

Are you using the default MobSF VM version 0.2?

```
[INFO] Waiting for TAR dump to complete...

[INFO] Dumping Application Files from Device/VM
10078 KB/s (4617728 bytes in 0.447s)

[INFO] Stopping ADB
[08/May/2016 08:05:33]"POST /DumpData/ HTTP/1.1" 200 15

[INFO] Dynamic Analysis Report Generation

[INFO] Dynamic API Analysis

[INFO] Dynamic File Analysis
```

**Comment by anantshri** [comment]
Nope i have used my own VM, I will have to investigate further on this from my end also. will check and revert.

Also as for first issue point for me is give permission to whom. The idea of USE_HOME is for users specific directory but it also allows various users to run the tool. When different users will be executing the same code how can i give one user write access to that folder. That will solve problem for one user but the other user will still have same issues.

**Comment by ajinabraham** [comment]
Issue 1 is fixed https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/commit/0cd29690b480d2346864e714f1808d202f722b71

**Comment by ajinabraham** [comment]
USE_HOME won't hamper form multiple users to run the framework at the same time. But framework specific settings and files are same for all the users. for example the tools used by MobSF will be same for all the users. so that's why necessary permissions are required on MobSF dir. 

Most of the 3rd party tools, user already have can be defined and pointed by modifying in settings.py or config.py. But there are some internal tools which are always running from within MobSF dir (now and also in future). They might need permission on the directory according to how they are designed.

**Comment by ajinabraham** [comment]
If you are doing in a different VM, I think you need to check out for these

`/sdcard/mobsec_status` is the file created by data pusher to inform framework that tar file which contains the tar of the application specific dir (/data/data/bla.cla)  is created.
you can run datapusher individually and see if this file as well as the tar is generated

`[adb, "-s", getIdentifier(), "shell", "am", "startservice", "-a", PACKAGE, "opensecurity.ajin.datapusher/.GetPackageLocation"]` 

PACKAGE can be com.blaa.foo 

This is what data pusher does: https://github.com/ajinabraham/MobSF-DataPusher/blob/master/DataPusher/app/src/main/java/opensecurity/ajin/datapusher/GetPackageLocation.java#L45-L69

Make sure you have all the required permission in 
`/data/local`

**Comment by anantshri** [comment]
again getting back to the point what permissions. In unix permission model i can do following.
1) run mobsf as one user and give that user full control of the repository. (mutes the point of having USE_HOME as everything would be in that specific user)
2) allow users to run mobsf only when they are part of a specific group and allow that group write access over the said folder. (not tested but might solve problem, but adds an overhead on OS administrators. also what happens when a specific file is being modified by multiple users again not tested)
3) We ensure no read write operations happen on the framework folder. (if you are concerned about a specific tool please point we will try and sort this issue at there end. however as per my usage only mobsf written tools are accessing that directory no external tools that are bundled have accessed that specific directory)

**Comment by ajinabraham** [comment]
Regarding 1

For MobSF, `USE_HOME` only means to store user specific settings, files generated and created are stored in user's home directory.

Regarding 2

All user specific stuffs are in user's home DIR. but if some one changes anything that's framework specific that will be reflected to all users (This is a requirement) Everything in settings.py will be instantly reloaded and other changes will be loaded only at next server restart.

Regarding 3
Executable permission is required for tools used by MobSF. This is a requirement  in both USE_HOME and self contained mode as tools are used from the same location.

Also in some cases 3rd party tools like dex2jar create error or log file in the current working directory which inside MobSF dir, so not giving permission can break things for users. I think if you specify executable path in settings.py or config.py, you don't have to provide permissions to MobSF dir. (not tested)

The ultimate goal of MobSF is less configurations for users. That's the reason all the required tools are bundled now.

**Comment by anantshri** [comment]
Agreed with 1 and 2. Lets discuss 3 where we were discussing this earlier.
