### ISSUE TITLE
mobsfy within scripts / automation

### ISSUE THREAD

**Issue by anantshri** [ajinabraham/Mobile-Security-Framework-MobSF#146]
Mobsfy doesn't seem to have an option to take user input via commandline.

Also i realized there is no main function created https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/blob/master/mobsfy.py#L35

Can i request a main function as well as a user input variable consumption. something like 

`python mobsfy.py <IP or SERIALNO>`
and we configure that specific device.

**Comment by ajinabraham** [comment]
This is doable

**Comment by ajinabraham** [comment]
added https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/commit/9a377a277209bfff934c01f5be3d7bbc8bbef0a7

**Comment by ajinabraham** [comment]
sample usage ` python mobsfy.py -i 192.168.56.101:5555 -t 1`
