### ISSUE TITLE
Android: Pulling apps from device

### ISSUE THREAD

**Issue by anantshri** [ajinabraham/Mobile-Security-Framework-MobSF#147]
What if i have a running and properly installed application on my device. There should be an option where i connect my device to computer via adb start mobsf and then mobsf shows application list installed on the device and i can pick apk's for analysis and mobsf then pulls them down and start analysis.

**Comment by ajinabraham** [comment]
This is something I had in mind :) like the `Attach` stuff

**Comment by bugwrangler** [comment]
Will you be running scan against paid app also ?

**Comment by anantshri** [comment]
If we get the app apk then why not.. We are not pirating we are just extracting what's already available. I don't see a point which could go against us.

**Comment by ajinabraham** [comment]
@bugwrangler All the EULA and Terms are between the user and the app's creator/ company.
MobSF is just a tool like a Knife :)
