### ISSUE TITLE
[Enc] Add some graphs in reports 

### ISSUE THREAD

**Issue by bugwrangler** [ajinabraham/Mobile-Security-Framework-MobSF#149]
some graphs w.r.t. Total of vulnerabilities Vs severity etc. 
<img width="330" alt="screen shot 2016-05-10 at 12 56 47 am" src="https://cloud.githubusercontent.com/assets/6933052/15125375/1df6f526-164a-11e6-8d84-523218a7c9eb.png">

**Comment by bugwrangler** [comment]
Any API pointers which supports graph @ PDF report in Django ?

**Comment by ajinabraham** [comment]
Will be tracked under https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/issues/144

**Comment by ajinabraham** [comment]
For Graph, I think you will have to generate an image out of graph and add it to the PDF generation template

**Comment by bugwrangler** [comment]
perfect, let me give a try.

**Comment by bugwrangler** [comment]
Web UX shows the same but I'm unable to get graph at pdf, Any plan to change PDF report ?

**Comment by ajinabraham** [comment]
No plans to work on reports at the moment. There are things with higher priority in the bucket.
