### ISSUE TITLE
Analysing IPA file

### ISSUE THREAD

**Issue by AlexandreVargas** [ajinabraham/Mobile-Security-Framework-MobSF#150]
I choose any file (ipa) and show this message:

Don't Play Around. An Error just popped in!
no such table: StaticAnalyzer_staticanalyzeripa

I follow all steps to install x-code, according: http://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/

I did this command: pip install -r requirements.txt

Can you help me to solve it?

**Comment by AlexandreVargas** [comment]
Alexandres-Mac:/ alexandrevargas$ java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
Alexandres-Mac:/ alexandrevargas$ python --version
Python 2.7.11
Alexandres-Mac:/ alexandrevargas$ python --version
Python 2.7.11

**Comment by ajinabraham** [comment]
`no such table: StaticAnalyzer_staticanalyzeripa`
The problem is with your database. You are using a new version of MobSF and the database structure is old.

Try running

* migrate, which is responsible for applying migrations, as well as unapplying and listing their status.
* makemigrations, which is responsible for creating new migrations based on the changes you have made to your models.
 
`python manage.py migrate`
`python manage.py makemigrations`

still the issue is not resolved, try deleting the db.sqlite3 file and run `python manage.py migrate`

**Comment by TiagoHenriqueM** [comment]
Any other suggestions?

I tried to run the migrate and makemigrations commands and did not work.
I also tried to delete the db.sqlit3 file and then run the migrate command.

Best regards,
Tiago.

**Comment by AlexandreVargas** [comment]
So sorry my delay Tiago.

I try simulate your error, and to me occur this error:

/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/ios.py, LINE 527 "strings=escape(strings.replace(BIN_DIR + "/",""))"): 'ascii' codec can't decode byte 0xbd in position 13155: ordinal not in range(128)

Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/ios.py, LINE 86 "INFO_PLIST,BIN_NAME,ID,VER,SDK,PLTFM,MIN,LIBS,BIN_ANAL,STRINGS=BinaryAnalysis(BIN_DIR,TOOLS_DIR,APP_DIR)"): 'NoneType' object is not iterable


Hi Ajinabraham,

Help us about these issues.

Follow up more information:

Alexandres-Mac:~ alexandrevargas$ java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

Alexandres-Mac:~ alexandrevargas$ python --version
Python 2.7.11

But I have django 1.9 version, and I don't believe that, it is cause theses errors.

Kind regards,
Alexandre

**Comment by ajinabraham** [comment]
It should be in this order
delete db.sqlite3
```
python manage.py makemigrations
python manage.py migrate
```

**Comment by dsnmpx** [comment]
I have same issue.
@ajinabraham, provided steps did not work.
Any idea?

**Comment by yazananwar** [comment]
try this 

python manage.py makemigrations

python manage.py migrate --run-syncdb

**Comment by cwaazywabbit** [comment]
Running `python manage.py migrate --run-syncdb` fixed it for me. Deleting the DB file didn't seem to have any effect.
