### ISSUE TITLE
VirtualBox show error when start MobSF_VM_0.2

### ISSUE THREAD

**Issue by Malayke** [ajinabraham/Mobile-Security-Framework-MobSF#153]
I got some error when start MobSF VM

> 不能为虚拟电脑 MobSF_VM_0.2 打开一个新任务.
> 
> The virtual machine 'MobSF_VM_0.2' has terminated unexpectedly during startup with exit code -1073741819 (0xc0000005).  More details may be available in 'C:\Users\xxxx\VirtualBox VMs\MobSF_VM_0.2\Logs\VBoxHardening.log'.
> 
> 返回 代码:E_FAIL (0x80004005)
> 组件:MachineWrap
> 界面:IMachine {f30138d4-e5ea-4b3a-8858-a059de4c93fd}

**VBoxHardening.log**
===============================

b78.2d24: Log file opened: 5.0.20r106931 g_hStartupLog=00000000000000b0 g_uNtVerCombined=0xa0295a00
b78.2d24: \SystemRoot\System32\ntdll.dll:
b78.2d24:     CreationTime:    2016-03-03T12:40:50.813234600Z
b78.2d24:     LastWriteTime:   2016-02-23T11:25:45.858135200Z
b78.2d24:     ChangeTime:      2016-03-04T05:40:55.620447100Z
b78.2d24:     FileAttributes:  0x20
b78.2d24:     Size:            0x1bc048
b78.2d24:     NT Headers:      0xe0
b78.2d24:     Timestamp:       0x56cbf9dd
b78.2d24:     Machine:         0x8664 - amd64
b78.2d24:     Timestamp:       0x56cbf9dd
b78.2d24:     Image Version:   10.0
b78.2d24:     SizeOfImage:     0x1c1000 (1839104)
b78.2d24:     Resource Dir:    0x159000 LB 0x66220
b78.2d24:     ProductName:     Microsoft® Windows® Operating System
b78.2d24:     ProductVersion:  10.0.10586.122
b78.2d24:     FileVersion:     10.0.10586.122 (th2_release_inmarket.160222-1549)
b78.2d24:     FileDescription: NT Layer DLL
b78.2d24: \SystemRoot\System32\kernel32.dll:
b78.2d24:     CreationTime:    2015-10-30T07:17:46.221743200Z
b78.2d24:     LastWriteTime:   2015-10-30T07:17:46.221743200Z
b78.2d24:     ChangeTime:      2016-01-25T04:01:13.114347100Z
b78.2d24:     FileAttributes:  0x20
b78.2d24:     Size:            0xac430
b78.2d24:     NT Headers:      0xf0
b78.2d24:     Timestamp:       0x5632d5aa
b78.2d24:     Machine:         0x8664 - amd64
b78.2d24:     Timestamp:       0x5632d5aa
b78.2d24:     Image Version:   10.0
b78.2d24:     SizeOfImage:     0xad000 (708608)
b78.2d24:     Resource Dir:    0xab000 LB 0x528
b78.2d24:     ProductName:     Microsoft® Windows® Operating System
b78.2d24:     ProductVersion:  10.0.10586.0
b78.2d24:     FileVersion:     10.0.10586.0 (th2_release.151029-1700)
b78.2d24:     FileDescription: Windows NT BASE API Client DLL
b78.2d24: \SystemRoot\System32\KernelBase.dll:
b78.2d24:     CreationTime:    2016-03-09T03:52:41.401323500Z
b78.2d24:     LastWriteTime:   2016-02-24T09:52:06.910200800Z
b78.2d24:     ChangeTime:      2016-03-11T02:10:46.953130100Z
b78.2d24:     FileAttributes:  0x20
b78.2d24:     Size:            0x1e7a10
b78.2d24:     NT Headers:      0xf0
b78.2d24:     Timestamp:       0x56cd45b4
b78.2d24:     Machine:         0x8664 - amd64
b78.2d24:     Timestamp:       0x56cd45b4
b78.2d24:     Image Version:   10.0
b78.2d24:     SizeOfImage:     0x1e8000 (1998848)
b78.2d24:     Resource Dir:    0x1d1000 LB 0x548
b78.2d24:     ProductName:     Microsoft® Windows® Operating System
b78.2d24:     ProductVersion:  10.0.10586.162
b78.2d24:     FileVersion:     10.0.10586.162 (th2_release_sec.160223-1728)
b78.2d24:     FileDescription: Windows NT BASE API Client DLL
b78.2d24: \SystemRoot\System32\apisetschema.dll:
b78.2d24:     CreationTime:    2015-10-30T07:17:57.502957900Z
b78.2d24:     LastWriteTime:   2015-10-30T07:17:57.502957900Z
b78.2d24:     ChangeTime:      2016-01-25T03:54:09.578363500Z
b78.2d24:     FileAttributes:  0x20
b78.2d24:     Size:            0x16d60
b78.2d24:     NT Headers:      0xc8
b78.2d24:     Timestamp:       0x5632d94c
b78.2d24:     Machine:         0x8664 - amd64
b78.2d24:     Timestamp:       0x5632d94c
b78.2d24:     Image Version:   10.0
b78.2d24:     SizeOfImage:     0x18000 (98304)
b78.2d24:     Resource Dir:    0x17000 LB 0x400
b78.2d24:     ProductName:     Microsoft® Windows® Operating System
b78.2d24:     ProductVersion:  10.0.10586.0
b78.2d24:     FileVersion:     10.0.10586.0 (th2_release.151029-1700)
b78.2d24:     FileDescription: ApiSet Schema DLL
b78.2d24: NtOpenDirectoryObject failed on \Driver: 0xc0000022
b78.2d24: supR3HardenedWinFindAdversaries: 0x0
b78.2d24: supR3HardenedWinInitAppBin(0x0): '\Device\HarddiskVolume1\Program Files\Oracle\VirtualBox'
b78.2d24: Calling main()
b78.2d24: SUPR3HardenedMain: pszProgName=VirtualBox fFlags=0x2
b78.2d24: supR3HardenedWinInitAppBin(0x2): '\Device\HarddiskVolume1\Program Files\Oracle\VirtualBox'
b78.2d24: SUPR3HardenedMain: Respawn #1
b78.2d24: System32:  \Device\HarddiskVolume1\Windows\System32
b78.2d24: WinSxS:    \Device\HarddiskVolume1\Windows\WinSxS
b78.2d24: KnownDllPath: C:\Windows\system32
b78.2d24: '\Device\HarddiskVolume1\Program Files\Oracle\VirtualBox\VirtualBox.exe' has no imports
b78.2d24: supHardenedWinVerifyImageByHandle: -> 0 (\Device\HarddiskVolume1\Program Files\Oracle\VirtualBox\VirtualBox.exe)
b78.2d24: supR3HardNtEnableThreadCreation:
b78.2d24: supR3HardNtDisableThreadCreation: pvLdrInitThunk=00007ffd1c936d50 pvNtTerminateThread=00007ffd1c965b20
b78.2d24: supR3HardenedWinDoReSpawn(1): New child 2aa8.1864 [kernel32].
b78.2d24: supR3HardNtChildGatherData: PebBaseAddress=000000000025b000 cbPeb=0x388
b78.2d24: supR3HardNtPuChFindNtdll: uNtDllParentAddr=00007ffd1c8c0000 uNtDllChildAddr=00007ffd1c8c0000
b78.2d24: supR3HardenedWinSetupChildInit: uLdrInitThunk=00007ffd1c936d50
b78.2d24: supR3HardenedWinSetupChildInit: Start child.
b78.2d24: supR3HardNtChildWaitFor: Found expected request 0 (PurifyChildAndCloseHandles) after 0 ms.
b78.2d24: supR3HardNtChildPurify: Startup delay kludge #1/0: 257 ms, 30 sleeps
b78.2d24: supHardNtVpScanVirtualMemory: enmKind=CHILD_PURIFICATION
b78.2d24:  *0000000000000000-fffffffffffeffff 0x0001/0x0000 0x0000000
b78.2d24:  *0000000000010000-fffffffffffeffff 0x0004/0x0004 0x0020000
b78.2d24:  *0000000000030000-000000000001afff 0x0002/0x0002 0x0040000
b78.2d24:   0000000000045000-0000000000039fff 0x0001/0x0000 0x0000000
b78.2d24:  *0000000000050000-fffffffffff54fff 0x0000/0x0004 0x0020000
b78.2d24:   000000000014b000-0000000000147fff 0x0104/0x0004 0x0020000
b78.2d24:   000000000014e000-000000000014bfff 0x0004/0x0004 0x0020000
b78.2d24:  *0000000000150000-000000000014bfff 0x0002/0x0002 0x0040000
b78.2d24:   0000000000154000-0000000000147fff 0x0001/0x0000 0x0000000
b78.2d24:  *0000000000160000-000000000015dfff 0x0004/0x0004 0x0020000
b78.2d24:   0000000000162000-00000000000c3fff 0x0001/0x0000 0x0000000
b78.2d24:  *0000000000200000-00000000001a4fff 0x0000/0x0004 0x0020000
b78.2d24:   000000000025b000-0000000000257fff 0x0004/0x0004 0x0020000
b78.2d24:   000000000025e000-00000000000bbfff 0x0000/0x0004 0x0020000
b78.2d24:   0000000000400000-000000000003ffff 0x0001/0x0000 0x0000000
b78.2d24:  *00000000007c0000-00000000007befff 0x0040/0x0040 0x0020000 !!
b78.2d24: supHardNtVpFreeOrReplacePrivateExecMemory: Freeing exec mem at 00000000007c0000 (LB 0x1000, 00000000007c0000 LB 0x1000)
b78.2d24: supHardNtVpFreeOrReplacePrivateExecMemory: Free attempt #1 succeeded: 0x0 [00000000007c0000/00000000007c0000 LB 0/0x1000]
b78.2d24: supHardNtVpFreeOrReplacePrivateExecMemory: QVM after free 0: [0000000000000000]/00000000007c0000 LB 0x7f820000 s=0x10000 ap=0x0 rp=0x00000100000001
b78.2d24:   00000000007c1000-ffffffff80fa1fff 0x0001/0x0000 0x0000000
b78.2d24:  *000000007ffe0000-000000007ffdefff 0x0002/0x0002 0x0020000
b78.2d24:   000000007ffe1000-000000007ffd1fff 0x0000/0x0002 0x0020000
b78.2d24:   000000007fff0000-ffff8009d232ffff 0x0001/0x0000 0x0000000
b78.2d24:  *00007ff72dcb0000-00007ff72dc7cfff 0x0002/0x0002 0x0040000
b78.2d24:   00007ff72dce3000-00007ff72d5c5fff 0x0001/0x0000 0x0000000
b78.2d24:  *00007ff72e400000-00007ff72e400fff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume1\Program Files\Oracle\VirtualBox\VirtualBox.exe
b78.2d24:   00007ff72e401000-00007ff72e470fff 0x0020/0x0080 0x1000000  \Device\HarddiskVolume1\Program Files\Oracle\VirtualBox\VirtualBox.exe
b78.2d24:   00007ff72e471000-00007ff72e471fff 0x0080/0x0080 0x1000000  \Device\HarddiskVolume1\Program Files\Oracle\VirtualBox\VirtualBox.exe
b78.2d24:   00007ff72e472000-00007ff72e4b6fff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume1\Program Files\Oracle\VirtualBox\VirtualBox.exe
b78.2d24:   00007ff72e4b7000-00007ff72e4b7fff 0x0004/0x0080 0x1000000  \Device\HarddiskVolume1\Program Files\Oracle\VirtualBox\VirtualBox.exe
b78.2d24:   00007ff72e4b8000-00007ff72e4b8fff 0x0008/0x0080 0x1000000  \Device\HarddiskVolume1\Program Files\Oracle\VirtualBox\VirtualBox.exe
b78.2d24:   00007ff72e4b9000-00007ff72e4bdfff 0x0004/0x0080 0x1000000  \Device\HarddiskVolume1\Program Files\Oracle\VirtualBox\VirtualBox.exe
b78.2d24:   00007ff72e4be000-00007ff72e4befff 0x0008/0x0080 0x1000000  \Device\HarddiskVolume1\Program Files\Oracle\VirtualBox\VirtualBox.exe
b78.2d24:   00007ff72e4bf000-00007ff72e4bffff 0x0004/0x0080 0x1000000  \Device\HarddiskVolume1\Program Files\Oracle\VirtualBox\VirtualBox.exe
b78.2d24:   00007ff72e4c0000-00007ff72e4c3fff 0x0008/0x0080 0x1000000  \Device\HarddiskVolume1\Program Files\Oracle\VirtualBox\VirtualBox.exe
b78.2d24:   00007ff72e4c4000-00007ff72e50bfff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume1\Program Files\Oracle\VirtualBox\VirtualBox.exe
b78.2d24:   00007ff72e50c000-00007ff140157fff 0x0001/0x0000 0x0000000
b78.2d24:  *00007ffd1c8c0000-00007ffd1c8c0fff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume1\Windows\System32\ntdll.dll
b78.2d24:   00007ffd1c8c1000-00007ffd1c9bdfff 0x0020/0x0080 0x1000000  \Device\HarddiskVolume1\Windows\System32\ntdll.dll
b78.2d24:   00007ffd1c9be000-00007ffd1c9fefff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume1\Windows\System32\ntdll.dll
b78.2d24:   00007ffd1c9ff000-00007ffd1ca07fff 0x0008/0x0080 0x1000000  \Device\HarddiskVolume1\Windows\System32\ntdll.dll
b78.2d24:   00007ffd1ca08000-00007ffd1ca14fff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume1\Windows\System32\ntdll.dll
b78.2d24:   00007ffd1ca15000-00007ffd1ca15fff 0x0004/0x0080 0x1000000  \Device\HarddiskVolume1\Windows\System32\ntdll.dll
b78.2d24:   00007ffd1ca16000-00007ffd1ca18fff 0x0008/0x0080 0x1000000  \Device\HarddiskVolume1\Windows\System32\ntdll.dll
b78.2d24:   00007ffd1ca19000-00007ffd1ca80fff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume1\Windows\System32\ntdll.dll
b78.2d24:   00007ffd1ca81000-00007ffa39521fff 0x0001/0x0000 0x0000000
b78.2d24:  *00007ffffffe0000-00007ffffffcffff 0x0001/0x0002 0x0020000
b78.2d24: VirtualBox.exe: timestamp 0x57220aaf (rc=VINF_SUCCESS)
b78.2d24: '\Device\HarddiskVolume1\Program Files\Oracle\VirtualBox\VirtualBox.exe' has no imports
b78.2d24: '\Device\HarddiskVolume1\Windows\System32\ntdll.dll' has no imports
b78.2d24: supR3HardNtChildPurify: cFixes=1 g_fSupAdversaries=0x80000000
b78.2d24: supR3HardNtChildPurify: Startup delay kludge #1/1: 514 ms, 60 sleeps
b78.2d24: supHardNtVpScanVirtualMemory: enmKind=CHILD_PURIFICATION
b78.2d24:  *0000000000000000-fffffffffffeffff 0x0001/0x0000 0x0000000
b78.2d24:  *0000000000010000-fffffffffffeffff 0x0004/0x0004 0x0020000
b78.2d24:  *0000000000030000-000000000001afff 0x0002/0x0002 0x0040000
b78.2d24:   0000000000045000-0000000000039fff 0x0001/0x0000 0x0000000
b78.2d24:  *0000000000050000-fffffffffff54fff 0x0000/0x0004 0x0020000
b78.2d24:   000000000014b000-0000000000147fff 0x0104/0x0004 0x0020000
b78.2d24:   000000000014e000-000000000014bfff 0x0004/0x0004 0x0020000
b78.2d24:  *0000000000150000-000000000014bfff 0x0002/0x0002 0x0040000
b78.2d24:   0000000000154000-0000000000147fff 0x0001/0x0000 0x0000000
b78.2d24:  *0000000000160000-000000000015dfff 0x0004/0x0004 0x0020000
b78.2d24:   0000000000162000-00000000000c3fff 0x0001/0x0000 0x0000000
b78.2d24:  *0000000000200000-00000000001a4fff 0x0000/0x0004 0x0020000
b78.2d24:   000000000025b000-0000000000257fff 0x0004/0x0004 0x0020000
b78.2d24:   000000000025e000-00000000000bbfff 0x0000/0x0004 0x0020000
b78.2d24:   0000000000400000-ffffffff8081ffff 0x0001/0x0000 0x0000000
b78.2d24:  *000000007ffe0000-000000007ffdefff 0x0002/0x0002 0x0020000
b78.2d24:   000000007ffe1000-000000007ffd1fff 0x0000/0x0002 0x0020000
b78.2d24:   000000007fff0000-ffff8009d232ffff 0x0001/0x0000 0x0000000
b78.2d24:  *00007ff72dcb0000-00007ff72dc7cfff 0x0002/0x0002 0x0040000
b78.2d24:   00007ff72dce3000-00007ff72d5c5fff 0x0001/0x0000 0x0000000
b78.2d24:  *00007ff72e400000-00007ff72e400fff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume1\Program Files\Oracle\VirtualBox\VirtualBox.exe
b78.2d24:   00007ff72e401000-00007ff72e470fff 0x0020/0x0080 0x1000000  \Device\HarddiskVolume1\Program Files\Oracle\VirtualBox\VirtualBox.exe
b78.2d24:   00007ff72e471000-00007ff72e471fff 0x0040/0x0080 0x1000000  \Device\HarddiskVolume1\Program Files\Oracle\VirtualBox\VirtualBox.exe
b78.2d24:   00007ff72e472000-00007ff72e4b6fff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume1\Program Files\Oracle\VirtualBox\VirtualBox.exe
b78.2d24:   00007ff72e4b7000-00007ff72e4c3fff 0x0004/0x0080 0x1000000  \Device\HarddiskVolume1\Program Files\Oracle\VirtualBox\VirtualBox.exe
b78.2d24:   00007ff72e4c4000-00007ff72e50bfff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume1\Program Files\Oracle\VirtualBox\VirtualBox.exe
b78.2d24:   00007ff72e50c000-00007ff140157fff 0x0001/0x0000 0x0000000
b78.2d24:  *00007ffd1c8c0000-00007ffd1c8c0fff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume1\Windows\System32\ntdll.dll
b78.2d24:   00007ffd1c8c1000-00007ffd1c9bdfff 0x0020/0x0080 0x1000000  \Device\HarddiskVolume1\Windows\System32\ntdll.dll
b78.2d24:   00007ffd1c9be000-00007ffd1c9fefff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume1\Windows\System32\ntdll.dll
b78.2d24:   00007ffd1c9ff000-00007ffd1ca02fff 0x0008/0x0080 0x1000000  \Device\HarddiskVolume1\Windows\System32\ntdll.dll
b78.2d24:   00007ffd1ca03000-00007ffd1ca07fff 0x0004/0x0080 0x1000000  \Device\HarddiskVolume1\Windows\System32\ntdll.dll
b78.2d24:   00007ffd1ca08000-00007ffd1ca14fff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume1\Windows\System32\ntdll.dll
b78.2d24:   00007ffd1ca15000-00007ffd1ca15fff 0x0004/0x0080 0x1000000  \Device\HarddiskVolume1\Windows\System32\ntdll.dll
b78.2d24:   00007ffd1ca16000-00007ffd1ca18fff 0x0008/0x0080 0x1000000  \Device\HarddiskVolume1\Windows\System32\ntdll.dll
b78.2d24:   00007ffd1ca19000-00007ffd1ca80fff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume1\Windows\System32\ntdll.dll
b78.2d24:   00007ffd1ca81000-00007ffa39521fff 0x0001/0x0000 0x0000000
b78.2d24:  *00007ffffffe0000-00007ffffffcffff 0x0001/0x0002 0x0020000
b78.2d24: supR3HardNtChildPurify: Done after 853 ms and 1 fixes (loop #1).
2aa8.1864: Log file opened: 5.0.20r106931 g_hStartupLog=0000000000000004 g_uNtVerCombined=0xa0295a00
2aa8.1864: supR3HardenedVmProcessInit: uNtDllAddr=00007ffd1c8c0000 g_uNtVerCombined=0xa0295a00
b78.2d24: supR3HardNtEnableThreadCreation:
2aa8.1864: ntdll.dll: timestamp 0x56cbf9dd (rc=VINF_SUCCESS)
2aa8.1864: New simple heap: #1 0000000000500000 LB 0x400000 (for 1839104 allocation)
2aa8.1864: supR3HardenedWinInitAppBin(0x0): '\Device\HarddiskVolume1\Program Files\Oracle\VirtualBox'
2aa8.1864: System32:  \Device\HarddiskVolume1\Windows\System32
2aa8.1864: WinSxS:    \Device\HarddiskVolume1\Windows\WinSxS
2aa8.1864: KnownDllPath: C:\Windows\system32
2aa8.1864: supR3HardenedVmProcessInit: Opening vboxdrv stub...
2aa8.1864: supR3HardenedVmProcessInit: Restoring LdrInitializeThunk...
2aa8.1864: supR3HardenedVmProcessInit: Returning to LdrInitializeThunk...
2aa8.1864: Registered Dll notification callback with NTDLL.
2aa8.1864: supHardenedWinVerifyImageByHandle: -> 0 (\Device\HarddiskVolume1\Windows\System32\kernel32.dll)
2aa8.1864: supR3HardenedWinVerifyCacheInsert: \Device\HarddiskVolume1\Windows\System32\kernel32.dll
2aa8.1864: supR3HardenedMonitor_LdrLoadDll: pName=C:\Windows\system32\KERNEL32.DLL (Input=KERNEL32.DLL, rcNtResolve=0xc0150008) *pfFlags=0xffffffff pwszSearchPath=0000000000000801:<flags> [calling]
2aa8.1864: supR3HardenedDllNotificationCallback: load   00007ffd199d0000 LB 0x001e8000 C:\Windows\system32\KERNELBASE.dll [fFlags=0x0]
2aa8.1864: supHardenedWinVerifyImageByHandle: -> 0 (\Device\HarddiskVolume1\Windows\System32\KernelBase.dll)
2aa8.1864: supR3HardenedWinVerifyCacheInsert: \Device\HarddiskVolume1\Windows\System32\KernelBase.dll
2aa8.1864: supR3HardenedDllNotificationCallback: load   00007ffd1b4d0000 LB 0x000ad000 C:\Windows\system32\KERNEL32.DLL [fFlags=0x0]
2aa8.1864: supR3HardenedScreenImage/LdrLoadDll: cache hit (VINF_SUCCESS) on \Device\HarddiskVolume1\Windows\System32\kernel32.dll [lacks WinVerifyTrust]
2aa8.1864: supR3HardenedMonitor_LdrLoadDll: returns rcNt=0x0 hMod=00007ffd1b4d0000 'C:\Windows\system32\KERNEL32.DLL'
2aa8.1864: supR3HardenedDllNotificationCallback: load   00007ff72e400000 LB 0x0010c000 C:\Program Files\Oracle\VirtualBox\VirtualBox.exe [fFlags=0x0]
2aa8.1864: '\Device\HarddiskVolume1\Program Files\Oracle\VirtualBox\VirtualBox.exe' has no imports
2aa8.1864: supHardenedWinVerifyImageByHandle: -> 0 (\Device\HarddiskVolume1\Program Files\Oracle\VirtualBox\VirtualBox.exe)
2aa8.1864: supR3HardenedWinVerifyCacheInsert: \Device\HarddiskVolume1\Program Files\Oracle\VirtualBox\VirtualBox.exe
b78.2d24: supR3HardNtChildWaitFor[1]: Quitting: ExitCode=0xc0000005 (rcNtWait=0x0, rcNt1=0x0, rcNt2=0x103, rcNt3=0x103, 123 ms, CloseEvents);

`

**Comment by Malayke** [comment]
I solved this problem after uninstall MacType

**Comment by luener** [comment]
Same as you.@Malayke Solved it after uninstall MacType

**Comment by larry011** [comment]
thx!!!!!! @Malayke

**Comment by DanielKneipp** [comment]
It seems to be a VirtualBox issue. I had the same problem here with all my VMs when MacType was installed.

**Comment by JeongYoungHo** [comment]
You do not have to delete the mactype. Only ignore virtualbox in process manager of mactype.
