### ISSUE TITLE
ImportError in DynamicAnalyzer

### ISSUE THREAD

**Issue by windyzxcui** [ajinabraham/Mobile-Security-Framework-MobSF#154]
Hi Ajin,

when I click "DynamicAnalyzer", it returns the following error, do you have any idea ?
I have followed the configuration guide to setup the Dynamic Analyzer in MAC, I don't know why the error came out.
-------------------------------Error start here---------------------------

dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyOpenSSL-0.13-py2.7-win32.egg/OpenSSL/crypto.pyd, 10): no suitable image found.  Did find:
	/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyOpenSSL-0.13-py2.7-win32.egg/OpenSSL/crypto.pyd: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
Request Method:	POST
Request URL:	http://127.0.0.1:8000/DynamicAnalyzer/
Django Version:	1.9.5
Exception Type:	ImportError
Exception Value:	
dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyOpenSSL-0.13-py2.7-win32.egg/OpenSSL/crypto.pyd, 10): no suitable image found.  Did find:
	/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyOpenSSL-0.13-py2.7-win32.egg/OpenSSL/crypto.pyd: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
Exception Location:	/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyOpenSSL-0.13-py2.7-win32.egg/OpenSSL/crypto.py in __bootstrap__, line 6
Python Executable:	/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Python Version:	2.7.11
Python Path:	
['/Users/windycui/Desktop/windy/Work/HSBC/tools/Mobile-Security-Framework-MobSF-0.9.1',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/six-1.10.0-py2.7.egg',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Twisted-10.2.0-py2.7-macosx-10.6-intel.egg',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/zope.interface-4.1.3-py2.7-macosx-10.6-intel.egg',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/drozer-2.3.4-py2.7.egg',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyOpenSSL-0.13-py2.7-win32.egg',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/protobuf-2.4.1-py2.7.egg',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/psutil-4.0.0-py2.7-macosx-10.6-intel.egg',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload',
 '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages',
 '/Library/Python/2.7/site-packages']
Server time:	Fri, 13 May 2016 10:13:32 +0000
-----------------End------------------------------

**Comment by ajinabraham** [comment]
MobSF requires `pyOpenSSL` version 0.15
https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/blob/master/requirements.txt#L2

What you have is pyOpenSSL 0.13. update that

Also it seems you are using `Mobile-Security-Framework-MobSF-0.9.1`. download the latest: https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/releases/tag/v0.9.2
