### ISSUE TITLE
There is a bug(Although it is not important) at StaticAnalyser/views.py 

### ISSUE THREAD

**Issue by LeeHDsniper** [ajinabraham/Mobile-Security-Framework-MobSF#155]
I found that if a service has a attribute :android:exported="true" ,it will appear twice at  Manifest Analysis of report page.
I found the problem at StaticAnalyser/views.py:from line 1150 to 1158,and from line 1205 to 1216.

**Comment by ajinabraham** [comment]
I am not able to reproduce this. I scanned an apk with an exported service.
```
        <service
            android:name="vlokal.vagent.AgentService"
            android:enabled="true"
            android:exported="true"
            >
        </service>
```

MobSF showed the entry only once. Do you have an APK that causes MobSF to show the exported service twice?

**Comment by LeeHDsniper** [comment]
I checked your code again.I think you have fixed this problem yet.Anyway
,thank you for response and just forget this.I found this problem about a
month ago and I did't update local version.

2016-06-02 16:58 GMT+08:00 Ajin Abraham <notifications@github.com>:

**Comment by ajinabraham** [comment]
Fixed
