### ISSUE TITLE
Make mobsf Kali compatible 

### ISSUE THREAD

**Issue by ajinabraham** [ajinabraham/Mobile-Security-Framework-MobSF#158]
https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/issues/143#issuecomment-219762617

**Comment by c0dist** [comment]
Any specific issues that you faced while setting it up in Kali? The install instructions look pretty distro-neutral.

**Comment by ajinabraham** [comment]
Bunded ADB is Ubuntu specific. Kali being Debian based needs a different adb binary. 
To keep the bundled nature of MobSF, the adb binaries for Win, Mac and Linux are bundled.
Solution is
1. Always first try to load adb installed by user, if possible (this is the best solution)
2. If users don't have adb installed, fall back to MobSF adb. But here prolly for Debian, adb binaries can be added. This will become complicated when platform changes or like x64 - x86 dependencies

**Comment by ajinabraham** [comment]
I wish adb was written and maintained in Java or Python😉

**Comment by ajinabraham** [comment]
I saw jadb before (Java based adb client), but haven't tested it across various platforms and since it's not official, not sure how long it will be maintained.

**Comment by AkshayJainG** [comment]
Dynamic analyzer is not working in kali linux  but in ubuntu it works like charm

**Comment by ajinabraham** [comment]
The same adb will cause issues.

**Comment by c0dist** [comment]
That's strange. Kali and Ubuntu are both Debian-based and as such the binaries should work mostly. I will try to see if I can figure anything out.

**Comment by ajinabraham** [comment]
Some differences are there http://unix.stackexchange.com/questions/41407/is-ubuntu-lts-binary-compatible-with-debian
Also some libs might be different or missing

**Comment by ajinabraham** [comment]
See the last comment https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/issues/143#issuecomment-220322226

That was the fix for Kali users. May be we should try installing those libs and see if MobSF adb binaries are working. Or diff the binary to see what is the diff

**Comment by c0dist** [comment]
Hi @ajinabraham,

I seem to have found a working solution that allows me to run the `adb`, `fastboot`, etc. binaries provided by you with the latest MobSF version. Here are the steps that I followed:

- Ran Live CD of Kali 2016.1 version.
- Downloaded latest MobSF zip from Github.
- Then ran following commands on the terminal before testing:
```bash
dpkg --add-architecture i386
apt-get update
apt-get install libstdc++6:i386 zlib1g:i386 libncurses5:i386
```
- After this I was able to run the commands such as `adb`, `sqlite3` and others inside tools/adb/linux

I think MobSF should work now since you can run the above commands now.

Thank you. Let me know if this works.

**Comment by c0dist** [comment]
This was most probably the cause for failure - http://askubuntu.com/a/133460

**Comment by ajinabraham** [comment]
Yeah prolly that's the issue. I will verify this in a VM.
and Send a PR, you can cross verify this. Huge thanks for investigating on this 👍

**Comment by anantshri** [comment]
"I wish adb was written and maintained in Java or Python😉"
Worst choice of tool for something like adb.

"1. Always first try to load adb installed by user, if possible (this is the best solution)" 
while you are at it can we also do the same for dex2jar, enjarify, or simmilar all tools. see if they are in path then please use them directly if not then resort to your own tools.

if you just need adb binary which works on debian 64 bits, have a look at https://github.com/AndroidTamer/adb_wrapper/blob/master/adb AOSP 6.X compiled adb for debian working flawlessly on debian 8 / AndroidTamer

**Comment by ajinabraham** [comment]
@anantshri 
I will disagree here, We are talking about adb client. IIUC it's just a TCP client that communicates with the adbd in device / VM using a simple protocol. 
https://github.com/android/platform_system_core/blob/master/adb/OVERVIEW.TXT#L77
I can create a client in any lang and send these commands via a socket to get my job done, a simple example: http://blog.kmckk.com/archives/4092210.html
This already done in java: https://github.com/vidstige/jadb The only reason I stay away from this is that it's not officially maintained by Google.

Other than for Tamer, I don't think those tools will be in PATH or environment variable for most Linux distro. 

I don't want to bundle more platform specific binaries if that is possible, it will be difficult to update and maintain them. 
Apart from Windows, for Mac and Linux, I will still prefer to use the existing ones if available. If adding 32bit support for Kali is not troublesome, I will try the fix mentioned by @c0dist . Otherwise, I can use the binary that you have pointed.

**Comment by anantshri** [comment]
> I will disagree here, We are talking about adb client. IIUC it's just a TCP client that communicates with the adbd in device / VM using a simple protocol.
> https://github.com/android/platform_system_core/blob/master/adb/OVERVIEW.TXT#L77
> I can create a client in any lang and send these commands via a socket to get my job done, a simple example: http://blog.kmckk.com/archives/4092210.html
> This already done in java: https://github.com/vidstige/jadb The only reason I stay away from this is that it's not officially maintained by Google.
lets agree to disagree on this one.

> 
> I don't want to bundle more platform specific binaries if that is possible, it will be difficult to update and maintain them.
> Apart from Windows, for Mac and Linux, I will still prefer to use the existing ones if available. If adding 32bit support for Kali is not troublesome, I will try the fix mentioned by @c0dist . Otherwise, I can use the binary that you have pointed.

You are contradicting yourself here. you need to decide two things.
1) I will support every available platform where my users might run it.
2) I will try best support but i will let them be the owners and if they have tools they can use it.

For 2 you need to look at path and use tools from the path if available otherwise use your tools and then be prepared if it doesn't work then give out warning things are wrong.
For 1 You need to buckle up and give binaries of all possible combinations.

> Other than for Tamer, I don't think those tools will be in PATH or environment variable for most Linux distro. 
I can see many many examples where people will have android sdk and simmilar stuff pre installed / will then be using your tool in which case a lot of these tools might be already available.

**Comment by ajinabraham** [comment]
Most things are fine for Windows and Mac. The diversity in Linux comes with distro problems.
I will go with 2. This will be restricted to few standard tools. The pain is only with platform specific tools, rest everything written in Java or Python works flawlessly. Another problem is whether to use the user installed one or the bundled one. Bundled ones are always tested in known platforms for how well they integrate. Problem that can arise are like user may be using an old version of tool and framework uses a newer one and so. These problems need a proper solution. Till then giving priority for user installed tools is a problem. (I am not sure how practical it is to do version checks and all as these are all custom code that may break on updates)

Bundling stuff is an overhead, but the mission is pre configured analysis env with very little one time initial configuration. 

Looking in path for non standard tool is a pain, I need to look more into this like how a default installation of Android studio will place their tools across diff distros. Where can I look in etc. For non standard tools like dex2jar, enjarify I doubt on this mainly due to non-standard nature.

**Comment by ajinabraham** [comment]
@c0dist I verified the fix on Linux kali 4.3.0-kali1-amd64 #1 SMP Debian 4.3.3-7kali2 (2016-01-27) x86_64 GNU/Linux

Now for automating this 
```
dpkg --add-architecture i386
apt-get update
```

These above two commands can be automated easily.

`apt-get -y install libstdc++6:i386 zlib1g:i386 libncurses5:i386`

produces a linux terminal dialog like this 
![screen shot 2016-06-07 at 2 09 30 pm](https://cloud.githubusercontent.com/assets/4301109/15851405/337c3470-2cba-11e6-8220-74a78990bace.png)

I need to see how we can automate this in unattended way if possible without using any other 3rd party python dependency or expect.

**Comment by c0dist** [comment]
@ajinabraham Why don't we let Kali user run these commands before setting up MobSF? You can add these packages as prerequisites on Kali OS.

Or if you really want to automate it, maybe you can check out following posts:
- https://askubuntu.com/questions/556385/how-can-i-install-apt-packages-non-interactively
- http://www.microhowto.info/howto/perform_an_unattended_installation_of_a_debian_package.html
- https://serverfault.com/questions/48724/100-non-interactive-debian-dist-upgrade

These might or might not help. I am sure @anantshri would have better inputs on this problem.

**Comment by ajinabraham** [comment]
We are trying to automate things so If possible we should avoid manual configs as much as possible. It make sense to keep an instruction set for installing some dependencies for say Windows, Mac and Linux. But going at distro level will complicate things in future. 

Another thing is we have to take a decision on whether to forcefully go with `yes` or let the user choose it. Kali being a typical non production environment and as other softwares are already doing this, I think it's ok to do a forceful yes. I will check those links. Thanks for the heads up.

**Comment by c0dist** [comment]
I think you can run following commands to install packages without intervention.

```bash
export DEBIAN_FRONTEND=noninteractive
apt-get update -q
apt-get install -q -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" libstdc++6:i386 zlib1g:i386 libncurses5:i386
```

This does not prompt the user, so can be used. The commands have been taken from this blog - http://www.microhowto.info/howto/perform_an_unattended_installation_of_a_debian_package.html and I have tested them on my Kali VM.

Let me know if you come across same results.

**Comment by ajinabraham** [comment]
Fixed in https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/commit/2c94370df36ac654d6b185fbb6da3aaa7a6b11a8

**Comment by ajinabraham** [comment]
@c0dist  Thanks for the contribution.
