### ISSUE TITLE
Cannot import name FileWrapper and support for DJango 1.10

### ISSUE THREAD

**Issue by virqdroid** [ajinabraham/Mobile-Security-Framework-MobSF#159]
Fixes

- _Support for DJango 1.10_
**urls.py** 
`import MobSF.views`

- _Cannot import name FileWrapper_ 

> Exception Type:	ImportError
> Exception Value:	
> cannot import name FileWrapper
> Exception Location:	C:\Users\abcdef\Desktop\Mobile-Security-Framework-MobSF-0.9.2\MobSF\views.py in <module>, line 8

**views.py** :
`from django.core.servers.basehttp import FileWrapper`
to
`from wsgiref.util import FileWrapper`

**Comment by ajinabraham** [comment]
MobSF needs Django 1.8, 
higher versions are not tested properly.

**Comment by konkakarthik** [comment]
@virqdroid browse through C:\Users\abcdef\Desktop\Mobile-Security-Framework-MobSF-0.9.2/MobSF/views.py then make sure to comment line8 as #from django.core.servers.basehttp import FileWrapper then restart the server and see if it works.!

**Comment by ajinabraham** [comment]
Fixed and updated to support Django 1.10b on latest commit

**Comment by ajinabraham** [comment]
https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/commit/28ec75113b8589319b5549f5751ad3d88a9e6d5b
