### ISSUE TITLE
Don't Play Around. An Error just popped in! 'NoneType' object is not iterable  Inappropriate argument type.

### ISSUE THREAD

**Issue by angeldebone** [ajinabraham/Mobile-Security-Framework-MobSF#160]
Only this apk error.

**My log files:**

[2016-05-19 22:48:22]
[ERROR] Oracle Java (JDK >=1.7) is not found! (C:\iBLISS\Tools\Mobile\Tools\Mobile-Security-Framework-MobSF-master\MobSF\utils.py, LINE 110 "for dirname in os.listdir(WIN_JAVA_BASE):"): [Error 3] O sistema não pode encontrar o caminho especificado: 'C:/Program Files/Java/*.*'
[2016-05-19 22:48:26]
[ERROR] Oracle Java (JDK >=1.7) is not found! (C:\iBLISS\Tools\Mobile\Tools\Mobile-Security-Framework-MobSF-master\MobSF\utils.py, LINE 110 "for dirname in os.listdir(WIN_JAVA_BASE):"): [Error 3] O sistema não pode encontrar o caminho especificado: 'C:/Program Files/Java/*.*'
[2016-05-19 23:11:14]
[ERROR] Malware DB Update (C:\iBLISS\Tools\Mobile\Tools\Mobile-Security-Framework-MobSF-master\MalwareAnalyzer\views.py, LINE 21 "if sha256(TMP_DWD.name) != sha256(DB):"): [Errno 13] Permission denied: 'c:\\users\\angeld~1\\appdata\\local\\temp\\tmpwuy8lw'
[2016-05-20 10:03:48]
[ERROR] Reading Code Signing Certificate (C:\Mobile-Security-Framework-MobSF-master\StaticAnalyzer\views.py, LINE 996 "dat=escape(subprocess.check_output(args)).replace('\n', '</br>')"): 'utf8' codec can't decode byte 0xe3 in position 73: invalid continuation byte. You passed in '[\n[\n  Version: V3\n  Subject: CN=SinergyRH, OU=SinergyRH, O=SinergyRH, L=S\xe3o Paulo, ST=SP, C=55\n  Signature Algorithm: SHA256withRSA, OID = 1.2.840.113549.1.1.11\n\n  Key:  \n  Validity: [From: Tue Aug 04 15:20:42 BRT 2015,\n               To: Sat Jul 28 15:20:42 BRT 2040]\n  Issuer: CN=SinergyRH, OU=SinergyRH, O=SinergyRH, L=S\xe3o Paulo, ST=SP, C=55\n  SerialNumber: [    4bac7605]\n\nCertificate Extensions: 1\n[1]: ObjectId: 2.5.29.14 Criticality=false\nSubjectKeyIdentifier [\nKeyIdentifier [\n0000: 59 A6 DD C4 49 4A D7 40   A4 F6 7C CC 24 B6 2A 72  Y...IJ.@....$.*r\r\n0010: 58 F6 36 93                                        X.6.\r\n]\n]\n\n]\n  Algorithm: [SHA256withRSA]\n  Signature:\n0000: 54 A7 83 80 7D 6A EB BB   0F 90 AA E0 53 6B 5D C9  T....j......Sk].\r\n0010: 66 8B 7A 92 E5 65 F0 35   F7 2D 24 01 E5 07 E0 D8  f.z..e.5.-$.....\r\n0020: 35 F9 51 64 97 94 F8 08   F1 70 E2 5A 68 DF CC B3  5.Qd.....p.Zh...\r\n0030: 4D 5F 17 74 17 D7 56 BA   CA C1 28 D6 20 59 D6 71  M_.t..V...(. Y.q\r\n0040: C0 7F 19 41 C2 E2 C1 D3   87 F5 86 AF 9A 59 99 A6  ...A.........Y..\r\n0050: BC 5D 20 7B F0 45 EF A2   4C 01 EE 7E C5 05 94 BB  .] ..E..L.......\r\n0060: 80 84 88 7A A0 0A 80 4D   F5 93 90 64 4A EC 55 1D  ...z...M...dJ.U.\r\n0070: 06 C9 EA B9 77 11 BC AA   CD 8F CE B0 18 F1 08 FA  ....w...........\r\n0080: A4 05 7D B2 98 D1 1E 1F   49 E0 B8 00 F8 34 5E 82  ........I....4^.\r\n0090: 4F BB A9 B3 07 35 4F 2E   54 8F CD 91 6B CE 9D C2  O....5O.T...k...\r\n00A0: 4E 1B B2 6C 37 4E 94 E5   09 38 39 40 37 8A C3 D6  N..l7N...89@7...\r\n00B0: 03 76 71 D8 2D DF A7 C2   0F 87 68 A8 39 57 FF DC  .vq.-.....h.9W..\r\n00C0: 61 E8 C5 F3 0E E5 0F 1A   A7 3F C8 AA 6C E4 02 C0  a........?..l...\r\n00D0: 1A 07 86 C7 AC 13 34 9B   89 83 F7 75 A6 CF 96 A8  ......4....u....\r\n00E0: DE 7B AA F7 68 AE 70 24   A9 4D C6 CC DA CA 95 14  ....h.p$.M......\r\n00F0: C6 01 B4 AB 14 40 FB 0F   35 7F C5 B9 CB 3D 9D 4D  .....@..5....=.M\r\n\n]\r\n' (<type 'str'>)
[2016-05-20 10:03:48]
[ERROR] Static Analyzer (C:\Mobile-Security-Framework-MobSF-master\StaticAnalyzer\views.py, LINE 411 "CERT_INFO,ISSUED=CertInfo(APP_DIR,TOOLS_DIR)"): 'NoneType' object is not iterable
[2016-05-20 10:13:18]
[ERROR] Malware DB Update (C:\Mobile-Security-Framework-MobSF-master\MalwareAnalyzer\views.py, LINE 21 "if sha256(TMP_DWD.name) != sha256(DB):"): [Errno 13] Permission denied: 'c:\\users\\angeld~1\\appdata\\local\\temp\\tmpcdnfih'
[2016-05-20 10:31:35]
[ERROR] Malware DB Update (C:\Mobile-Security-Framework-MobSF-master\MalwareAnalyzer\views.py, LINE 21 "if sha256(TMP_DWD.name) != sha256(DB):"): [Errno 13] Permission denied: 'c:\\users\\angeld~1\\appdata\\local\\temp\\tmpxoq_7z'
[2016-05-20 10:33:38]
[ERROR] Reading Code Signing Certificate (C:\Mobile-Security-Framework-MobSF-master\StaticAnalyzer\views.py, LINE 996 "dat=escape(subprocess.check_output(args)).replace('\n', '</br>')"): 'utf8' codec can't decode byte 0xe3 in position 73: invalid continuation byte. You passed in '[\n[\n  Version: V3\n  Subject: CN=SinergyRH, OU=SinergyRH, O=SinergyRH, L=S\xe3o Paulo, ST=SP, C=55\n  Signature Algorithm: SHA256withRSA, OID = 1.2.840.113549.1.1.11\n\n  Key:  \n  Validity: [From: Tue Aug 04 15:20:42 BRT 2015,\n               To: Sat Jul 28 15:20:42 BRT 2040]\n  Issuer: CN=SinergyRH, OU=SinergyRH, O=SinergyRH, L=S\xe3o Paulo, ST=SP, C=55\n  SerialNumber: [    4bac7605]\n\nCertificate Extensions: 1\n[1]: ObjectId: 2.5.29.14 Criticality=false\nSubjectKeyIdentifier [\nKeyIdentifier [\n0000: 59 A6 DD C4 49 4A D7 40   A4 F6 7C CC 24 B6 2A 72  Y...IJ.@....$.*r\r\n0010: 58 F6 36 93                                        X.6.\r\n]\n]\n\n]\n  Algorithm: [SHA256withRSA]\n  Signature:\n0000: 54 A7 83 80 7D 6A EB BB   0F 90 AA E0 53 6B 5D C9  T....j......Sk].\r\n0010: 66 8B 7A 92 E5 65 F0 35   F7 2D 24 01 E5 07 E0 D8  f.z..e.5.-$.....\r\n0020: 35 F9 51 64 97 94 F8 08   F1 70 E2 5A 68 DF CC B3  5.Qd.....p.Zh...\r\n0030: 4D 5F 17 74 17 D7 56 BA   CA C1 28 D6 20 59 D6 71  M_.t..V...(. Y.q\r\n0040: C0 7F 19 41 C2 E2 C1 D3   87 F5 86 AF 9A 59 99 A6  ...A.........Y..\r\n0050: BC 5D 20 7B F0 45 EF A2   4C 01 EE 7E C5 05 94 BB  .] ..E..L.......\r\n0060: 80 84 88 7A A0 0A 80 4D   F5 93 90 64 4A EC 55 1D  ...z...M...dJ.U.\r\n0070: 06 C9 EA B9 77 11 BC AA   CD 8F CE B0 18 F1 08 FA  ....w...........\r\n0080: A4 05 7D B2 98 D1 1E 1F   49 E0 B8 00 F8 34 5E 82  ........I....4^.\r\n0090: 4F BB A9 B3 07 35 4F 2E   54 8F CD 91 6B CE 9D C2  O....5O.T...k...\r\n00A0: 4E 1B B2 6C 37 4E 94 E5   09 38 39 40 37 8A C3 D6  N..l7N...89@7...\r\n00B0: 03 76 71 D8 2D DF A7 C2   0F 87 68 A8 39 57 FF DC  .vq.-.....h.9W..\r\n00C0: 61 E8 C5 F3 0E E5 0F 1A   A7 3F C8 AA 6C E4 02 C0  a........?..l...\r\n00D0: 1A 07 86 C7 AC 13 34 9B   89 83 F7 75 A6 CF 96 A8  ......4....u....\r\n00E0: DE 7B AA F7 68 AE 70 24   A9 4D C6 CC DA CA 95 14  ....h.p$.M......\r\n00F0: C6 01 B4 AB 14 40 FB 0F   35 7F C5 B9 CB 3D 9D 4D  .....@..5....=.M\r\n\n]\r\n' (<type 'str'>)
[2016-05-20 10:33:38]
[ERROR] Static Analyzer (C:\Mobile-Security-Framework-MobSF-master\StaticAnalyzer\views.py, LINE 411 "CERT_INFO,ISSUED=CertInfo(APP_DIR,TOOLS_DIR)"): 'NoneType' object is not iterable
[2016-05-20 10:39:24]
[ERROR] Reading Code Signing Certificate (C:\Mobile-Security-Framework-MobSF-master\StaticAnalyzer\views.py, LINE 996 "dat=escape(subprocess.check_output(args)).replace('\n', '</br>')"): 'utf8' codec can't decode byte 0xe3 in position 73: invalid continuation byte. You passed in '[\n[\n  Version: V3\n  Subject: CN=SinergyRH, OU=SinergyRH, O=SinergyRH, L=S\xe3o Paulo, ST=SP, C=55\n  Signature Algorithm: SHA256withRSA, OID = 1.2.840.113549.1.1.11\n\n  Key:  \n  Validity: [From: Tue Aug 04 15:20:42 BRT 2015,\n               To: Sat Jul 28 15:20:42 BRT 2040]\n  Issuer: CN=SinergyRH, OU=SinergyRH, O=SinergyRH, L=S\xe3o Paulo, ST=SP, C=55\n  SerialNumber: [    4bac7605]\n\nCertificate Extensions: 1\n[1]: ObjectId: 2.5.29.14 Criticality=false\nSubjectKeyIdentifier [\nKeyIdentifier [\n0000: 59 A6 DD C4 49 4A D7 40   A4 F6 7C CC 24 B6 2A 72  Y...IJ.@....$.*r\r\n0010: 58 F6 36 93                                        X.6.\r\n]\n]\n\n]\n  Algorithm: [SHA256withRSA]\n  Signature:\n0000: 54 A7 83 80 7D 6A EB BB   0F 90 AA E0 53 6B 5D C9  T....j......Sk].\r\n0010: 66 8B 7A 92 E5 65 F0 35   F7 2D 24 01 E5 07 E0 D8  f.z..e.5.-$.....\r\n0020: 35 F9 51 64 97 94 F8 08   F1 70 E2 5A 68 DF CC B3  5.Qd.....p.Zh...\r\n0030: 4D 5F 17 74 17 D7 56 BA   CA C1 28 D6 20 59 D6 71  M_.t..V...(. Y.q\r\n0040: C0 7F 19 41 C2 E2 C1 D3   87 F5 86 AF 9A 59 99 A6  ...A.........Y..\r\n0050: BC 5D 20 7B F0 45 EF A2   4C 01 EE 7E C5 05 94 BB  .] ..E..L.......\r\n0060: 80 84 88 7A A0 0A 80 4D   F5 93 90 64 4A EC 55 1D  ...z...M...dJ.U.\r\n0070: 06 C9 EA B9 77 11 BC AA   CD 8F CE B0 18 F1 08 FA  ....w...........\r\n0080: A4 05 7D B2 98 D1 1E 1F   49 E0 B8 00 F8 34 5E 82  ........I....4^.\r\n0090: 4F BB A9 B3 07 35 4F 2E   54 8F CD 91 6B CE 9D C2  O....5O.T...k...\r\n00A0: 4E 1B B2 6C 37 4E 94 E5   09 38 39 40 37 8A C3 D6  N..l7N...89@7...\r\n00B0: 03 76 71 D8 2D DF A7 C2   0F 87 68 A8 39 57 FF DC  .vq.-.....h.9W..\r\n00C0: 61 E8 C5 F3 0E E5 0F 1A   A7 3F C8 AA 6C E4 02 C0  a........?..l...\r\n00D0: 1A 07 86 C7 AC 13 34 9B   89 83 F7 75 A6 CF 96 A8  ......4....u....\r\n00E0: DE 7B AA F7 68 AE 70 24   A9 4D C6 CC DA CA 95 14  ....h.p$.M......\r\n00F0: C6 01 B4 AB 14 40 FB 0F   35 7F C5 B9 CB 3D 9D 4D  .....@..5....=.M\r\n\n]\r\n' (<type 'str'>)
[2016-05-20 10:39:24]
[ERROR] Static Analyzer (C:\Mobile-Security-Framework-MobSF-master\StaticAnalyzer\views.py, LINE 411 "CERT_INFO,ISSUED=CertInfo(APP_DIR,TOOLS_DIR)"): 'NoneType' object is not iterable

**Comment by ajinabraham** [comment]
MobSF is not properly configured, It cannot find JAVA PATH, you don't have permission on the temp dir.
First you need to fix thoese

**Comment by angeldebone** [comment]
Thank you, Sir!

**Comment by vmsv** [comment]
I have a similar error, however it seems like the an error due to the lack of code signing. Is this possible?
