### ISSUE TITLE
Suggestion: Active Clipboard Monitoring: Dynamic analysis

### ISSUE THREAD

**Issue by anantshri** [ajinabraham/Mobile-Security-Framework-MobSF#161]
Can't seem to find this feature
While we are doing dynamic analysis and user is interacting at that point a active hook on clipboard could be kept which keeps checking if anything is stored in clipboard or not and if state changes then just add details in report.

P.S. Have not checked if its possible and hence raised as an issues

**Comment by ajinabraham** [comment]
Available on Master Branch (v0.9.2.1)
<img width="671" alt="screen shot 2016-10-17 at 8 21 45 pm" src="https://cloud.githubusercontent.com/assets/4301109/19443626/eaea3208-94aa-11e6-847d-ff8c5dca8487.png">
