### ISSUE TITLE
When I uploaded some APK, the following error occurred:

### ISSUE THREAD

**Issue by bitian** [ajinabraham/Mobile-Security-Framework-MobSF#163]
When I uploaded some APK, the following error occurred:
-----------------
Don't Play Around. An Error just popped in!

'NoneType' object is not iterable

Inappropriate argument type.
------------
And the logs is：
[INFO] Starting Analysis on : aa.apk
[INFO] Generating Hashes
[INFO] Unzipping
[INFO] Getting Hardcoded Certificates/Keystores
[INFO] APK Extracted
[INFO] Getting Manifest from Binary
[INFO] AXML -> XML
[INFO] Parsing AndroidManifest.xml

[2016-05-24 11:57:03]
[ERROR] Pasrsing AndroidManifest.xml (C:\MobSF1\StaticAnalyzer\views.py, LINE 86
5 "mfest=minidom.parseString(dat)"): not well-formed (invalid token): line 531,
column 19
[WARNING] Using Fake XML to continue the Analysis
[INFO] Extracting Manifest Data
[INFO] Manifest Analysis Started
[INFO] Formatting Permissions
[INFO] Reading Code Signing Certificate

[2016-05-24 11:57:03]
[ERROR] Reading Code Signing Certificate (C:\MobSF1\StaticAnalyzer\views.py, LIN
E 996 "dat=escape(subprocess.check_output(args)).replace('\n', '</br>')"): 'utf8
' codec can't decode byte 0xc0 in position 63: invalid start byte. You passed in
 '[\n[\n  Version: V3\n  Subject: CN=lzbank, OU=lzbank, O=lzbank, L=\xc0\xbc\xd6
\xdd, ST=\xb8\xca\xcb\xe0, C=CN\n  Signature Algorithm: SHA256withRSA, OID = 1.2
.840.113549.1.1.11\n\n  Key:  \n  Validity: [From: Fri May 24 09:46:27 CST 2013,
\n               To: Sat Apr 30 09:46:27 CST 2112]\n  Issuer: CN=lzbank, OU=lzba
nk, O=lzbank, L=\xc0\xbc\xd6\xdd, ST=\xb8\xca\xcb\xe0, C=CN\n  SerialNumber: [
  21a4dfd0]\n\nCertificate Extensions: 1\n[1]: ObjectId: 2.5.29.14 Criticality=f
alse\nSubjectKeyIdentifier [\nKeyIdentifier [\n0000: 8E BF ED FD 98 73 D0 7D   B
6 FA 79 CD F2 A1 D0 15  .....s....y.....\r\n0010: D9 41 37 27
                     .A7\'\r\n]\n]\n\n]\n  Algorithm: [SHA256withRSA]\n  Signatu
re:\n0000: 52 53 88 FA 7F 1D 87 5B   EE 4C BB EA 48 33 CD EC  RS.....[.L..H3..\r
\n0010: DC 59 14 97 E3 00 21 1C   4D 42 3B D1 3E DB 8E 1B  .Y....!.MB;.>...\r\n0
020: 26 C0 2C 17 CB CE CC D7   D2 81 E8 71 5B B6 22 E0  &.,........q[.".\r\n0030
: 15 99 E6 69 F0 71 2D E5   5E 13 08 4E 81 FB 1C 09  ...i.q-.^..N....\r\n0040: 5
5 2B 40 F6 B8 28 88 1C   58 6B 42 EA EB 2F 72 DF  U+@..(..XkB../r.\r\n0050: B1 0
8 A4 04 36 8B DF B3   79 A2 50 71 C7 27 07 C0  ....6...y.Pq.\'..\r\n0060: 9B 8C
57 9D 5F 39 44 7E   92 DD 89 AA 32 E7 F3 FB  ..W._9D.....2...\r\n0070: 23 D0 FE
29 D8 77 8A DD   71 B0 AA BA 11 A8 F1 3A  #..).w..q......:\r\n0080: 09 FB 8C B1
4B 64 71 04   C8 99 38 03 17 42 85 CB  ....Kdq...8..B..\r\n0090: 98 F4 6E 23 5D
9E 67 DF   94 D3 E8 CE A2 55 07 3D  ..n#].g......U.=\r\n00A0: C4 F4 F2 50 3A 71
FE 60   AA 2F A5 66 62 D5 28 7B  ...P:q.`./.fb.(.\r\n00B0: 3E E1 42 58 37 92 A6
1E   91 EE C8 21 18 E1 C4 36  >.BX7......!...6\r\n00C0: DA 77 2B BF 1C 76 5F 1C
  67 42 72 59 D0 AF 45 53  .w+..v_.gBrY..ES\r\n00D0: ED F9 62 A5 75 B7 CD DB   1
9 7A 28 F2 87 20 CA 49  ..b.u....z(.. .I\r\n00E0: F3 7F 13 5D 62 94 FF 1D   8B A
1 8E F8 71 EB 39 66  ...]b.......q.9f\r\n00F0: E5 62 EA 61 D2 67 26 5E   60 36 C
D D3 F1 A5 C8 DC  .b.a.g&^`6......\r\n\n]\r\n' (<type 'str'>)

[2016-05-24 11:57:03]
[ERROR] Static Analyzer (C:\MobSF1\StaticAnalyzer\views.py, LINE 411 "CERT_INFO,
ISSUED=CertInfo(APP_DIR,TOOLS_DIR)"): 'NoneType' object is not iterable
[24/May/2016 11:57:04]"GET /StaticAnalyzer/?name=aa.apk&type=apk&checksum=04e55b
eec58885813487577dd532e648 HTTP/1.1" 200 4671
--------------------------
Hope to get help,thank you！

**Comment by ajinabraham** [comment]
This is because of APK's certificate and manifest files containing non utf-8 characters. Unicode can break lot of things at the moment.

**Comment by ADPJeffrey** [comment]
Hi, do you have a fix at the moment? I have the same problem too!

Thank  you!
