### ISSUE TITLE
VM Image unable to Access HTTP

### ISSUE THREAD

**Issue by BigNoseSec** [ajinabraham/Mobile-Security-Framework-MobSF#165]
Hello,

The VM image provided is resolve HTTP traffic. It can ping servers outside of the network fine (from the android command line) but is unable to resolve sites in the browser. I tried removing the RootCA from the MobSF webapp but it seems it is still not functioning.

**Comment by ajinabraham** [comment]
Have you configured the network adapters as mentioned in the documentation wiki?
Make sure your VirtualBox adapters can connect to internet.

**Comment by abhi78sen** [comment]
Hi,

Same problem here

**Comment by ajinabraham** [comment]
Also If you try to access sites through VM without running MobSF dynamic analyzer, It won't work as the proxy is not running. You might need to run the dynamic analyzer or remove proxy settings for connecting to internet directly.

**Comment by ajinabraham** [comment]
Closing as further response is not seen
