### ISSUE TITLE
Failed to gather basic information of an APK

### ISSUE THREAD

**Issue by whitehatpanda** [ajinabraham/Mobile-Security-Framework-MobSF#167]
I got below error while doing static analysis on an application:

> [INFO] Performing Static Analysis of Android APK
> [30/May/2016 03:32:33]"POST /Upload/ HTTP/1.1" 200 148
> [INFO] Starting Analysis on : com.xxxx.ipay-1.apk
> [INFO] Generating Hashes
> [INFO] Unzipping
> 
> [2016-05-30 03:32:35]
> [ERROR] Unzipping Error (/Users/whitehatpanda/Mobile-Security-Framework-MobSF/StaticAnalyzer/views.py, LINE 945 "z.extractall(EXT_PATH)"): 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
> 
> [INFO] Using the Default OS Unzip Utility.
> mapname:  conversion of ^I^I^K failed
> mapname:  conversion of ^^^I failed
> mapname:  conversion of ^^^^^I failed
> mapname:  conversion of ^_^L failed
> mapname:  conversion of ^_^I failed
> mapname:  conversion of ^_^\^I failed
> mapname:  conversion of ^L^^^I failed
> mapname:  conversion of ^K^L^I failed
> mapname:  conversion of ^I^^^I failed
> mapname:  conversion of ^I^_ failed
> mapname:  conversion of ^_^]^I failed
> mapname:  conversion of ^K^_^I failed
> mapname:  conversion of ^_^I^K failed
> mapname:  conversion of ^\^I failed
> mapname:  conversion of ^]^\^I failed
> mapname:  conversion of ^L^I failed
> mapname:  conversion of ^\^_^I failed
> mapname:  conversion of ^I^] failed
> mapname:  conversion of ^K^] failed
> mapname:  conversion of ^L^_^I failed
> mapname:  conversion of ^]^I failed
> mapname:  conversion of ^L^\^I failed
> mapname:  conversion of ^K^L failed
> mapname:  conversion of ^]^_^I failed
> mapname:  conversion of ^\^^^I failed
> mapname:  conversion of ^K^K^I failed
> mapname:  conversion of ^I^I^I failed
> mapname:  conversion of ^K^]^I failed
> mapname:  conversion of ^]^_ failed
> mapname:  conversion of ^^^_^I failed
> mapname:  conversion of ^\^I^I failed
> mapname:  conversion of ^K failed
> mapname:  conversion of ^]^^^I failed
> mapname:  conversion of ^L^_ failed
> mapname:  conversion of ^\^\^I failed
> mapname:  conversion of ^_^\ failed
> mapname:  conversion of ^K^_ failed
> mapname:  conversion of ^I^_^I failed
> mapname:  conversion of ^]^I^I failed
> mapname:  conversion of ^\^K^I failed
> mapname:  conversion of ^_^^^I failed
> mapname:  conversion of ^K^\^I failed
> mapname:  conversion of ^L^^ failed
> mapname:  conversion of ^I^K^I failed
> mapname:  conversion of ^_^K failed
> mapname:  conversion of ^^^] failed
> mapname:  conversion of ^^^I^K failed
> mapname:  conversion of ^L^] failed
> mapname:  conversion of ^]^^ failed
> mapname:  conversion of ^I^I failed
> mapname:  conversion of ^L^K^I failed
> mapname:  conversion of ^]^\ failed
> mapname:  conversion of ^L^L^I failed
> mapname:  conversion of ^L failed
> mapname:  conversion of ^\^I^K failed
> mapname:  conversion of ^I failed
> mapname:  conversion of ^I^K failed
> mapname:  conversion of ^_^_^I failed
> mapname:  conversion of ^]^K failed
> mapname:  conversion of ^\^L failed
> mapname:  conversion of ^^^L failed
> mapname:  conversion of ^\^\ failed
> mapname:  conversion of ^_^L^I failed
> mapname:  conversion of ^] failed
> mapname:  conversion of ^^ failed
> mapname:  conversion of ^^^L^I failed
> mapname:  conversion of ^_ failed
> mapname:  conversion of ^\^_ failed
> mapname:  conversion of ^I^L failed
> mapname:  conversion of ^^^^ failed
> mapname:  conversion of ^^^K failed
> mapname:  conversion of ^I^\^I failed
> mapname:  conversion of ^\^]^I failed
> mapname:  conversion of ^L^\ failed
> mapname:  conversion of ^I^]^I failed
> mapname:  conversion of ^K^I^K failed
> mapname:  conversion of ^K^^^I failed
> mapname:  conversion of ^\^] failed
> mapname:  conversion of ^]^K^I failed
> mapname:  conversion of ^\ failed
> mapname:  conversion of ^\^K failed
> mapname:  conversion of ^K^^ failed
> mapname:  conversion of ^K^I failed
> mapname:  conversion of ^I^^ failed
> mapname:  conversion of ^_^_ failed
> mapname:  conversion of ^^^I^I failed
> mapname:  conversion of ^^^]^I failed
> mapname:  conversion of ^K^I^I failed
> mapname:  conversion of ^L^K failed
> mapname:  conversion of ^^^K^I failed
> mapname:  conversion of ^\^^ failed
> mapname:  conversion of ^\^L^I failed
> mapname:  conversion of ^L^I^K failed
> mapname:  conversion of ^]^]^I failed
> mapname:  conversion of ^I^L^I failed
> mapname:  conversion of ^^^\^I failed
> mapname:  conversion of ^_^] failed
> mapname:  conversion of ^^^\ failed
> mapname:  conversion of ^K^\ failed
> mapname:  conversion of ^_^^ failed
> mapname:  conversion of ^_^K^I failed
> mapname:  conversion of ^]^] failed
> mapname:  conversion of ^]^L^I failed
> mapname:  conversion of ^]^I^K failed
> mapname:  conversion of ^L^I^I failed
> mapname:  conversion of ^K^K failed
> mapname:  conversion of ^I^\ failed
> mapname:  conversion of ^L^L failed
> mapname:  conversion of ^^^_ failed
> mapname:  conversion of ^_^I^I failed
> mapname:  conversion of ^L^]^I failed
> mapname:  conversion of ^]^L failed
> [INFO] Getting Hardcoded Certificates/Keystores
> [INFO] APK Extracted
> [INFO] Getting Manifest from Binary
> [INFO] AXML -> XML
> [INFO] Parsing AndroidManifest.xml
> 
> [2016-05-30 03:32:36]
> [ERROR] Pasrsing AndroidManifest.xml (/Users/whitehatpanda/Mobile-Security-Framework-MobSF/StaticAnalyzer/views.py, LINE 865 "mfest=minidom.parseString(dat)"): not well-formed (invalid token): line 1, column 132
> [WARNING] Using Fake XML to continue the Analysis
> [INFO] Extracting Manifest Data
> [INFO] Manifest Analysis Started
> [INFO] Formatting Permissions
> [INFO] Reading Code Signing Certificate
> [INFO] DEX -> JAR
> [INFO] Using JAR converter - dex2jar
> dex2jar /Users/whitehatpanda/Mobile-Security-Framework-MobSF/uploads/81a4d5f38431ebede520954ff4a80036/classes.dex -> /Users/whitehatpanda/Mobile-Security-Framework-MobSF/uploads/81a4d5f38431ebede520954ff4a80036/classes.jar
> [INFO] DEX -> SMALI
> [INFO] JAR -> JAVA
> java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
> 	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
> 	at java.util.ArrayList.get(ArrayList.java:429)
> 	at jd.fE.a(Unknown Source)
> 	at jd.fI.a(Unknown Source)
> 	at jd.fI.a(Unknown Source)
> 	at jd.af.b(Unknown Source)
> 	at jd.af.a(Unknown Source)
> 	at jd.af.a(Unknown Source)
> 	at jd.i.a(Unknown Source)
> 	at jd.ide.intellij.JavaDecompiler.decompile(Native Method)
> 	at jd.core.Decompiler.decompile(Decompiler.java:47)
> 	at jd.core.Decompiler.decompileToDir(Decompiler.java:56)
> 	at jd.core.Main.main(Main.java:16)
> java.lang.RuntimeException: Unexpected structure for finally block

On the UI, it's resulting on fail to get package name and similar things:
![image](https://cloud.githubusercontent.com/assets/5643884/15639237/851f9442-2653-11e6-9369-1df1c423d6bb.png)

**Comment by ajinabraham** [comment]
This is a badly crafted APK (corrupted) or may be the work of an obfuscator.
`'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)` seems like unicode is involved.  It fails to unzip even using the OS default unzip tool. This is a won't fix.
