### ISSUE TITLE
Mounting error

### ISSUE THREAD

**Issue by Roslekas** [ajinabraham/Mobile-Security-Framework-MobSF#171]
1. What is this problem in mounting section, please help...?:

[INFO] Setting up Dynamic Analysis Environment
[INFO] Starting Web Proxy
[INFO] Started Web Proxy at 192.168.56.1:1337
[INFO] Starting App for Dynamic Analysis
[INFO] Getting ADB Location
- daemon not running. starting it now on port 5037 *
- daemon started successfully *
  [INFO] ADB Started
  [INFO] Waiting for 5 seconds...
  [INFO] Connecting to VM/Device
  connected to 192.168.56.101:5555

**[INFO] Mounting
su: invalid option -- o
Usage: su [options] [--] [-] [LOGIN] [--] [args...]
Options:
  --daemon                      start the su daemon agent
  -c, --command COMMAND         pass COMMAND to the invoked shell
  -h, --help                    display this help message and exit
  -, -l, --login                pretend the shell to be a login shell
  -m, -p,
  --preserve-environment        do not change environment variables
  -s, --shell SHELL             use SHELL instead of the default /system/bin/sh
  -u                            display the multiuser mode and exit
  -v, --version                 display version number and exit
  -V                            display version code and exit,
                                this is used almost exclusively by Superuser.apk
mount: Operation not permitted**

[INFO] Installing APK
4393 KB/s (10348322 bytes in 2.300s)
        pkg: /data/local/tmp/d78af39354ad282c6998f6fdeb8dd168.apk
Success
[INFO] Launching APK Main Activity
Starting: Intent { cmp=com.siauliu.bankas.mobile/com.etronika.cpyellow.StartupActivity }
[INFO] Testing Environment is Ready!
[INFO] Getting Screen Resolution
[INFO] Getting ADB Location
[03/Jun/2016 13:13:37]"POST /GetEnv/ HTTP/1.1" 200 64
[INFO] Getting ADB Location
[INFO] Installing MobSF RootCA
23 KB/s (1119 bytes in 0.046s)
**Unknown id: /data/local/tmp/0025aabb.0**
[03/Jun/2016 13:13:38]"POST /MobSFCA/ HTTP/1.1" 200 19
1. and also, is it OK **Unknown id: /data/local/tmp/0025aabb.0** ?

after that screen looks like that
![image](https://cloud.githubusercontent.com/assets/16913780/15776178/c4484bd0-298e-11e6-8927-c996a9708e44.png)

and

in my app on virtual box i can't login to app, no internet access, no access to server.

![image](https://cloud.githubusercontent.com/assets/16913780/15776235/0dd473b4-298f-11e6-99f3-669fff80d771.png)

Please help :(
Big thanks.

Paulius

**Comment by Roslekas** [comment]
I forgot to mention, that internet access is good, working in to interfaces (Host only adapter and NAT). I can ping google.com and so on, access google play....

**Comment by ajinabraham** [comment]
Which is this VM ? The VM shipped with MobSF or a different one ?

**Comment by ajinabraham** [comment]
The reason why you can't Login is due to the Fact that MobSF proxy Root CA is not installed and that will cause error on all https connection.

**Comment by Roslekas** [comment]
Hi,

1. VM is different android 4.4.2 kitkat, not witch is shipped with MobSF. I also tried with MobSF_VM_0.2, but i could't even start app, got message "Unfortunately, app has stopped", so i tried a different VM...
2. Could You tell me, where can i found and manualy install MobSF proxy Root CA ? because strange message got in terminal when creating environment for dynamic analysis:

**[INFO] Installing MobSF RootCA
23 KB/s (1119 bytes in 0.046s)
**Unknown id: /data/local/tmp/0025aabb.0**
[03/Jun/2016 13:13:38]"POST /MobSFCA/ HTTP/1.1" 200 19**

THANKS

**Comment by ajinabraham** [comment]
The VM should be rooted and configured like this: https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/wiki/2.-Configure-MobSF-Dynamic-Analysis-Environment-in-your-Android-Device-or-VM

**Comment by ajinabraham** [comment]
This can be a problem with the the VM you use. If the default command does not works for you, then please find a mounting command that works on your device and replace it here:
https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/blob/master/DynamicAnalyzer/views/android.py#L734-L741
