### ISSUE TITLE
Can't upload .IPA format for static analysis

### ISSUE THREAD

**Issue by Roslekas** [ajinabraham/Mobile-Security-Framework-MobSF#172]
Hello,

why can't i upload .ipa srouce code for static analysis ?
![image](https://cloud.githubusercontent.com/assets/16913780/15816517/cf31caf4-2bdb-11e6-8f3f-27943a15c93e.png)

In Readme says that "It can be used for effective and fast security analysis of Android and iOS Applications and supports both binaries (APK & **IPA**)"

thanks

**Comment by ajinabraham** [comment]
For security analysis of iOS binaries, MobSF needs to be installed on a Mac OSX.
This prerequisite is mentioned in the documentaion.
https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/wiki/1.-Documentation#requirements
