### ISSUE TITLE
update libs if possible

### ISSUE THREAD

**Issue by ajinabraham** [ajinabraham/Mobile-Security-Framework-MobSF#173]
Pointed out by @anantshri 
updates libs https://requires.io/github/ajinabraham/Mobile-Security-Framework-MobSF/requirements/?branch=master

This has to be done without affecting existing users and breaking code.

**Comment by anantshri** [comment]
Alarming point xtml2pdf is now abandoned https://github.com/xhtml2pdf/xhtml2pdf/ suggested alternative http://weasyprint.org/

**Comment by ajinabraham** [comment]
weasyprint requires platform dependent dependencies and install.
http://weasyprint.readthedocs.io/en/latest/install.html#by-platform
Need to look out for another candidate.

**Comment by ajinabraham** [comment]
Updated
