### ISSUE TITLE
error show screen

### ISSUE THREAD

**Issue by yazananwar** [ajinabraham/Mobile-Security-Framework-MobSF#174]
Hi

when i installed MOBSF previous version v0.9.1 Beta,the features show screen  its ok, and image in dynamic report appear good

but there are problem in new release for MOBSF,show screen is crashed and there are problem in image in dynamic report

**Comment by ajinabraham** [comment]
Please elaborate on the problem add your `logs/MobSF.log` file

**Comment by yazananwar** [comment]
[INFO] Installing APK
6944 KB/s (8657689 bytes in 1.217s)
WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.
WARNING: linker: app_process has text relocations. This is wasting memory and is a security risk. Please fix.
        pkg: /data/local/tmp/fbefa2910e3551371de1129806680dfb.apk
Success

[INFO] Launching APK Main Activity
WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.
WARNING: linker: app_process has text relocations. This is wasting memory and is a security risk. Please fix.
Starting: Intent { cmp=jo.com.ehs.physician.hakeem/.SplashActivity }
[INFO] Testing Environment is Ready!

[INFO] Getting Screen Resolution

[INFO] Getting ADB Location
[10/Jun/2016 19:07:59]"POST /GetEnv/ HTTP/1.1" 200 65

[INFO] Getting ADB Location

[INFO] Installing MobSF RootCA
186 KB/s (1119 bytes in 0.005s)
[10/Jun/2016 19:07:59]"POST /MobSFCA/ HTTP/1.1" 200 19

[INFO] Invoking ScreenCast Service in VM/Device
[INFO] Invoking ScreenCast Service in VM/Device


[INFO] Getting ADB Location
[INFO] Getting ADB Location


[INFO] Invoking ScreenCast Service in VM/Device

[INFO] Getting ADB Location
WARNING: linker: WlARNING: linker: ibdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.
WARNING: linker: app_process has text relocations. This is wasting memory and is a security risk. Please fix.
libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.
WARNING: linker: app_process has text relocations. This is wasting memory and is a security risk. Please fix.
WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.
WARNING: linker: app_process has text relocations. This is wasting memory and is a security risk. Please fix.
Starting service: Intent { act=192.168.56.1:9339 cmp=opensecurity.screencast/.StartScreenCast }
Starting service: Intent { act=192.168.56.1:9339 cmp=opensecurity.screencast/.StartScreenCast }

[INFO] ScreenCast Service Status: on[
10/Jun/2016 19:09:00]"POST /ScreenCast/ HTTP/1.1" 200 17

[INFO] ScreenCast Service Status: on[
10/Jun/2016 19:09:00]"POST /ScreenCast/ HTTP/1.1" 200 16

[INFO] ScreenCast Service Status: on[
10/Jun/2016 19:09:00]"POST /ScreenCast/ HTTP/1.1" 200 16
[10/Jun/2016 19:09:00]"GET /download/screen/screen.png?1465574940946 HTTP/1.1" 302 0
[10/Jun/2016 19:09:00]"GET /download/screen/screen.png?1465574940952 HTTP/1.1" 302 0
[10/Jun/2016 19:09:00]"GET /error/ HTTP/1.1" 200 4602
Got Connection from:  192.168.56.101
[10/Jun/2016 19:09:01]"GET /download/screen/screen.png?1465574941252 HTTP/1.1" 200 219508
Got Connection from:  192.168.56.101
[10/Jun/2016 19:09:01]"GET /download/screen/screen.png?1465574941547 HTTP/1.1" 200 8305
[10/Jun/2016 19:09:01]"GET /download/screen/screen.png?1465574941552 HTTP/1.1" 200 8305
[10/Jun/2016 19:09:01]"GET /download/screen/screen.png?1465574941847 HTTP/1.1" 200 8305
[10/Jun/2016 19:09:01]"GET /download/screen/screen.png?1465574941852 HTTP/1.1" 200 8305
Got Connection from:  192.168.56.101
[10/Jun/2016 19:09:02]"GET /download/screen/screen.png?1465574942151 HTTP/1.1" 200 8305
[10/Jun/2016 19:09:02]"GET /download/screen/screen.png?1465574942448 HTTP/1.1" 200 8305
[10/Jun/2016 19:09:02]"GET /download/screen/screen.png?1465574942451 HTTP/1.1" 200 8305

[INFO] Invoking ScreenCast Service in VM/Device

[INFO] Getting ADB Location
WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.
WARNING: linker: app_process has text relocations. This is wasting memory and is a security risk. Please fix.
[10/Jun/2016 19:09:02]"GET /download/screen/screen.png?1465574942747 HTTP/1.1" 200 8305
[10/Jun/2016 19:09:02]"GET /download/screen/screen.png?1465574942752 HTTP/1.1" 200 8305
[10/Jun/2016 19:09:03]"GET /download/screen/screen.png?1465574943047 HTTP/1.1" 200 8305
[
10/Jun/2016 19:09:03]"GET /download/screen/screen.png?1465574943053 HTTP/1.1" 200 8305
[INFO] ScreenCast Service Status: off[
10/Jun/2016 19:09:03]"POST /ScreenCast/ HTTP/1.1" 200 17

**Comment by yazananwar** [comment]
logs/MobSF.log



[2016-06-10 19:15:13]
[ERROR] Malware DB Update (C:\Mobile-Security-Framework-MobSF-master\MalwareAnalyzer\views.py, LINE 21 "if sha256(TMP_DWD.name) != sha256(DB):"): [Errno 13] Permission denied: 'c:\\users\\admini~1\\appdata\\local\\temp\\tmpoprkd2'

**Comment by ajinabraham** [comment]
Looks like you don't have permission on your temp dir.
`[Errno 13] Permission denied: 'c:\users\admini~1\appdata\local\temp\tmpoprkd2'`
Run from a privileged account.

Also see if the file `screen.png

**Comment by yazananwar** [comment]
Hi dear

I solve the issue of temporary file and i make sure that the screen.png is created in MobSF/downloads/screen/

The problem still exists

**Comment by ajinabraham** [comment]
Does your screen.png changes when you enable screencast and navigate through the VM? If not, this can be that your firewall is blocking tcp connections made to MobSF Screencast server.

**Comment by yazananwar** [comment]
yes dear when enable screencast the image change in folder download but not appear in mobsf browser

**Comment by ajinabraham** [comment]
Can you try the latest master and latest MobSF VM Image?

**Comment by yazananwar** [comment]
Already i used latest VM and latest master

when i installed MOBSF previous version v0.9.1 Beta,the features show screen its ok, and image in dynamic report appear good

**Comment by ajinabraham** [comment]
I am not able to understand the problem at your end, with few debug info. I have it all good and working in Windows, Linux and Mac. Can we have a teamviewer session to explore more on this?

**Comment by ajinabraham** [comment]
Tracking:
 https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/issues/125
and https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/issues/239

**Comment by yazananwar** [comment]
yes we can any time

**Comment by ajinabraham** [comment]
Can you drop me an email at ajin25 AT gmail DOT com

**Comment by tachencko** [comment]
Hi, i have the same problem. I have installed Mobsf on Kali and ScreenCast fail.

The error code:

[2016-11-25 15:21:45]
[ERROR] ScreenCast Server (/root/Mobsf/DynamicAnalyzer/views/android.py, LINE 1100 "s.bind(ADDR)"): [Errno 99] Cannot assign requested address
[25/Nov/2016 15:21:45]"GET /download/screen/screen.png?1480087305364 HTTP/1.1" 302 0
[25/Nov/2016 15:21:45]"GET /error/ HTTP/1.1" 200 4603
[25/Nov/2016 15:21:45]"GET /download/screen/screen.png?1480087305662 HTTP/1.1" 302 0
[25/Nov/2016 15:21:45]"GET /error/ HTTP/1.1" 200 4603
[25/Nov/2016 15:21:45]"GET /download/screen/screen.png?1480087305964 HTTP/1.1" 302 0


Thanks!

**Comment by ajinabraham** [comment]
ScreenCast runs on port 9339. See if any other process in Kali is running on that port no.

**Comment by tachencko** [comment]
Thanks! I'll see.


Also when I give it a finish, it gives me this error:
[2016-11-25 16:50:19]
[ERROR] Dynamic API Analysis (/root/Mobsf/DynamicAnalyzer/views/android.py, LINE 821 "with open(LOCATION, "r") as f:"): [Errno 2] No such file or directory: u'/root/Mobsf/uploads/40f9f2a4d86eb90f0a572e9077fcd6ce/x_logcat.txt'

[INFO] Dynamic File Analysis

[2016-11-25 16:50:19]
[ERROR] Dynamic Analysis Report Generation (/root/Mobsf/DynamicAnalyzer/views/android.py, LINE 598 "APP_DIR, MD5, PKG)"): [Errno 2] No such file or directory: '/root/Mobsf/uploads/40f9f2a4d86eb90f0a572e9077fcd6ce/x_logcat.txt'

**Comment by psattarzadeh** [comment]
hi again
i have problem in taking screenshots in dynamic analysis. during the Exported Activity Testing, it attempts to take an screen shot but it fails. i got this warning and the images are not shown in the report and in the downloads\screen.

![untitled](https://user-images.githubusercontent.com/28703934/28750982-42a22522-7511-11e7-9dcc-3a28d677c226.png)


![screen](https://user-images.githubusercontent.com/28703934/28750983-48a08d7e-7511-11e7-8e7f-e9277aba4c5b.png)

could you please help me fix this error?

**Comment by ajinabraham** [comment]
ScreenCast has known issues in some windows versions due to OS file locks. The feature works only in Linux or Mac
