### ISSUE TITLE
Don't Play Around. An Error just popped in!

### ISSUE THREAD

**Issue by konkakarthik** [ajinabraham/Mobile-Security-Framework-MobSF#175]
m trying to use MOBSF in kali initially there was an error something similar to #159 then just tried to browse /root/Documents/MobSF/MobSF/views.py then made sure to comment line8 as from django.core.servers.basehttp import FileWrapper to #from django.core.servers.basehttp import FileWrapper then i was able to access upload a file but then after uploading the file it says something like 
no such table: StaticAnalyzer_staticanalyzerandroid
None

Thanks!

**Comment by ajinabraham** [comment]
Are you using the version of the Django as specified in the requirements.txt?
Looks like there is some issue with db migration.
run `python manage.py migrate` and `python manage.py makemigrations`

**Comment by abhiinos111abhi** [comment]
this solution worked like magic nd also i want to say great framework i have ever seen

**Comment by Fazalcs13** [comment]
Thanks a lot. You have made my day. Stunning framework

**Comment by Kamakshya-kar** [comment]
While uploading apk file I'm getting following error

Inappropriate argument type.

'NoneType' object does not support item assignment

Help me out

**Comment by ani070** [comment]
same issue in mobsf v1.1 
if i am try to run this  run " python manage.py migrate" and "python manage.py makemigrations"
pop an error ""ImportError: cannot import name settings""

**Comment by ajinabraham** [comment]
That's not how you run MobSF read documentation
