### ISSUE TITLE
PYTHON3 path with spaces at Windows systems

### ISSUE THREAD

**Issue by allyshka** [ajinabraham/Mobile-Security-Framework-MobSF#176]
If you use enjarify as DEX to JAR converter and path to python 3 executable contain spaces (ex.: C:\Program Files\Python 3.5\) MobSF cannot execute "enjarify" from bat file. You get error like this:

> [INFO] Running Python 3 path fix in Windows
'C:/Program' is not recognized as an internal or external command, operable program or batch file.
[INFO] DEX -> SMALI

Because bat file _enjarify.bat_ contains wrong path to python 3 in Windows you must use quotes for paths with spaces.

Problem in **WinFixPython3** function [https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/blob/9a377a277209bfff934c01f5be3d7bbc8bbef0a7/StaticAnalyzer/views.py#L1029](url):
`
        PYTHON3 = os.path.join(PYTHON3_PATH,"python")
`

Simple fix:
`
        PYTHON3 = "\"" + os.path.join(PYTHON3_PATH,"python") + "\""
`

**Comment by ajinabraham** [comment]
see if this branch works for youhttps://github.com/ajinabraham/Mobile-Security-Framework-MobSF/tree/python3_pathfix

I am also testing the same.

**Comment by allyshka** [comment]
Yes, it's works fine

**Comment by ajinabraham** [comment]
Verified at my end as well. Thanks for pointing out. :+1:  The fix is merged with master.

**Comment by shahriarshayan** [comment]
Does MobSF 0.9.5.5 works with Python 3.6 in sierra 10.12.6?? When I try to run python3 manage.py runserver, it shows syntax error. What will be the solution??

**Comment by ajinabraham** [comment]
Use python3 branch. Master is still python2

**Comment by shahriarshayan** [comment]
Any helpful link for using python3 branch??

**Comment by ajinabraham** [comment]
Just clone the branch install the dependencies that's it.

**Comment by shahriarshayan** [comment]
Do I need to clone from homebrew source or git source??

**Comment by ajinabraham** [comment]
Git obviously

**Comment by shahriarshayan** [comment]
I installed both python 2.7  and python 3.6. If I enter python --version it shows python 2.7.  If I use python setup.py install for instaling dependencies then, it shows No such file or directory: /usr/lib/python2.7/site-packages/test-easy-install-13091.write-test'. What to do??

**Comment by ajinabraham** [comment]
Sorry, but fix your Python first. Also for discussions, use slack channel and not this issue tracker.

**Comment by shahriarshayan** [comment]
https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/tree/python3_pathfix this link is not working.
