### ISSUE TITLE
Size IPA file

### ISSUE THREAD

**Issue by TiagoHenriqueM** [ajinabraham/Mobile-Security-Framework-MobSF#178]
I tried to upload a file IPA, but  appeared the following error message:
"File is too big"
How can I fix this? Is there a file that I can edit?

Att.,

**Comment by ajinabraham** [comment]
https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/blob/master/templates/index.html#L173

**Comment by georgepetz** [comment]
Hi Aji

This link is offline, could you see that?

Att.

**Comment by tyago19** [comment]
C:\MobSF\templates\general\index.html 
-> maxFilesize: 100, // MB

**Comment by georgepetz** [comment]
Thx Ty!!

**Comment by ajinabraham** [comment]
Here: https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/templates/general/index.html#L173
