### ISSUE TITLE
Dynamic Analyser issue 

### ISSUE THREAD

**Issue by Ashroyal** [ajinabraham/Mobile-Security-Framework-MobSF#184]
When i click on finish. It is showing the below status and struck at this point. I already installed xposed with Droidmon module. When i manually locate to this "/data/data/de.robv.android.xposed.installer/log/error.log'" file exits.

[INFO] Downloading Logcat logs
remote object '/data/data/de.robv.android.xposed.installer/log/error.log' does not exist

[INFO] Downloading Droidmon API Monitor Logcat logs

[INFO] Downloading Dumpsys logs

[INFO] Stopping Application

[INFO] Stopping ScreenCast Service
[02/Jul/2016 10:41:58]"POST /FinalTest/ HTTP/1.1" 200 16

[INFO] Device Data Dump

[INFO] Getting ADB Location

[INFO] Stopping any running instance of WebProxy

[INFO] Deleting Dump Status File

[INFO] Saving Captured Web Proxy Data

[INFO] Saving URLS

[INFO] Saving WebTraffic

[INFO] Saving Request Objects

[INFO] Stopped WebProxy and Data Saved
rm: /sdcard/mobsec_status: No such file or directory

[INFO] Creating TAR of Application Files.
[ERROR] TAR Generation Failed. Process timed out.

[INFO] Dumping Application Files from Device/VM
remote object '/data/local/com.test.test1.tar' does not exist

[INFO] Stopping ADB
[02/Jul/2016 11:11:21]"POST /DumpData/ HTTP/1.1" 200 15

**Comment by vincentcox-ordina** [comment]
How did you fix this?

**Comment by flamecopper** [comment]
Same here:
[ERROR] 06/Apr/2019 13:23:40 - TAR Generation Failed. Process timed out.
[INFO] 06/Apr/2019 13:23:40 - Dumping Application Files from Device/VM
[ERROR] 06/Apr/2019 13:23:40 - 
Running ADB Command (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/shared.py, LINE 70 "result = subprocess.check_output(args)"): Command '['/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/tools/adb/linux/adb', '-s', '192.168.56.101:5555', 'pull', '/data/local/jakhar.aseem.diva.tar', '/root/.MobSF/uploads/82ab8b2193b3cfb1c737e3a786be363a/jakhar.aseem.diva.tar']' returned non-zero exit status 1.

**Comment by flamecopper** [comment]
[ERROR] 06/Apr/2019 13:24:34 - 
TAR EXTRACTION FAILED (/root/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/analysis.py, LINE 189 "with tarfile.open(tar_loc) as tar:"): [Errno 2] No such file or directory: '/root/.MobSF/uploads/82ab8b2193b3cfb1c737e3a786be363a/jakhar.aseem.diva.tar'
[INFO] 06/Apr/2019 13:24:34 - Generating Downloads
[INFO] 06/Apr/2019 13:24:34 - 
Fetching Exported Activity & Activity List from DB
[ERROR] 06/Apr/2019 13:25:56 - Error Downloading File 82ab8b2193b3cfb1c737e3a786be363a-WebTraffic.txt
[ERROR] 06/Apr/2019 13:25:56 - Internal Server Error: /download/82ab8b2193b3cfb1c737e3a786be363a-WebTraffic.txt
[ERROR] 06/Apr/2019 13:26:02 - Error Downloading File 82ab8b2193b3cfb1c737e3a786be363a-AppData.tar
[ERROR] 06/Apr/2019 13:26:02 - Internal Server Error: /download/82ab8b2193b3cfb1c737e3a786be363a-AppData.tar
