### ISSUE TITLE
Name Error at /Upload/ global name 'Print Exception' is not defined

### ISSUE THREAD

**Issue by TiagoHenriqueM** [ajinabraham/Mobile-Security-Framework-MobSF#190]
Hi,

When I drag the file to upload on Static Analyzer on IOS Yosemite , the following error occurs:

"Name Error at /Upload/ global name 'PrintException' is not defined Request Method: POST Request 
URL: http://localhost:8000/Upload/
 Django Version: 1.9.7 Python Executable: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python Python Version: 2.7.12 Python Path: ['/Users/tiago/Desktop/Mobile-Security-Framework-MobSF-0.9.2', '/Library/Framework"

Has anyone had this issue?

Best regards,
Tiago.

**Comment by ajinabraham** [comment]
Are you using the latest master ? Django is upgraded to 1.10
https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/blob/master/requirements.txt#L1

**Comment by ajinabraham** [comment]
The error looks strange. `PrintException` is always defined.
Have you configured everything as per MobSF wiki

**Comment by TiagoHenriqueM** [comment]
Same problem with Django 1.10.
Yes I configured everything according to the wiki.

**Comment by ajinabraham** [comment]
delete your existing MobSF and Try these step as it is.
```
git clone https://github.com/ajinabraham/Mobile-Security-Framework-MobSF.git
cd Mobile-Security-Framework-MobSF
git pull
pip install -r requirements.txt --user
python manage.py runserver
```

See if this fixes your issue

**Comment by TiagoHenriqueM** [comment]
Solved.
Thank you!
