### ISSUE TITLE
mount Permission denied

### ISSUE THREAD

**Issue by xl7dev** [ajinabraham/Mobile-Security-Framework-MobSF#192]
[INFO] Getting ADB Location
- daemon not running. starting it now on port 5037 *
- daemon started successfully *

[INFO] ADB Started

[INFO] Waiting for 5 seconds...

[INFO] Connecting to VM/Device
connected to 10.0.0.10:5555

[INFO] Mounting
mount: Permission denied

[INFO] Installing APK
341 KB/s (7234096 bytes in 20.659s)
    pkg: /data/local/tmp/e79a425d3ce2443f77463ecc8bded3a6.apk
Success

**Comment by ajinabraham** [comment]
Are you using a different VM/ Device other than MobSF shipped VM?

**Comment by xl7dev** [comment]
real android device

**Comment by ajinabraham** [comment]
Have you configured the device using MbSFy script?
Make sure device is rooted and allows root access on request without asking for a prompt. Also see if MobSF.py script is running without errors

**Comment by xl7dev** [comment]
1. nexus6,system V6.0.1,have root access,xposed
2. host run MobSF and the Android Device is via wifi-adb tool connected to same WiFi network

**Comment by ajinabraham** [comment]
It should be failing here: https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/blob/master/DynamicAnalyzer/views/android.py#L617

Try running `adb -s <IP>:5555 shell su -c mount -o rw,remount,rw /system` separately from adb and see what is failing. I think the `su` binary you are using is not taking `-c` option. Try to execute the command separately and see if it's working.

**Comment by xl7dev** [comment]
>adb -s 10.0.0.10:5555 shell su -c mount -o rw,remount,rw /system
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
error: device '10.0.0.10:5555' not found
>adb connect 10.0.0.10:5555
connected to 10.0.0.10:5555
>adb shell
shell@shamu:/ $

**Comment by ajinabraham** [comment]
from `shell@shamu:/$` run ` su -c mount -o rw,remount,rw /system` and let me know what output  you get

**Comment by xl7dev** [comment]
shell@shamu:/ $ su -c mount -o rw,remount,rw /system
device output：mount -o rw_remount_rw /system

**Comment by ajinabraham** [comment]
This can be a problem with the the device you use. If the default command doesnot works for you, then please find a mounting command that works on your device and replace it here: 

https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/blob/master/DynamicAnalyzer/views/android.py#L734-L735

**Comment by xl7dev** [comment]
@ajinabraham i'm sorry,Not see this Supported Versions: Android 4.03 - 4.4,My Android Version:Android 6.0.1,Can be upgraded to 6.0.1 ?

**Comment by ajinabraham** [comment]
Version's above Android 4.4 are not directly supported at the moment.

**Comment by xl7dev** [comment]
ok
