### ISSUE TITLE
can I use usb adb  instead of Wifi adb

### ISSUE THREAD

**Issue by YaphetsH** [ajinabraham/Mobile-Security-Framework-MobSF#193]
when I used my nexus4 which is rooted,I found that the connection is not stable during dynamic analyze,so Can I use usb adb instead of wifi adb .

**Comment by ajinabraham** [comment]
Haven't tested.
You might need to patch this function to return the device id, if you are trying with adb usb
https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/blob/master/DynamicAnalyzer/views/android.py#L996

**Comment by YaphetsH** [comment]
thanks

**Comment by zym-wade** [comment]
> thanks

hello!Can you tell me how did you use usb adbde at the time?I have some troble

**Comment by zym-wade** [comment]
> Haven't tested.
> You might need to patch this function to return the device id, if you are trying with adb usb
> https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/blob/master/DynamicAnalyzer/views/android.py#L996

Hello!　The link you sent has expired，Can I use usb adb for dynamic detection now?
