### ISSUE TITLE
[Feature Request] Dockerfile 

### ISSUE THREAD

**Issue by awhitehatter** [ajinabraham/Mobile-Security-Framework-MobSF#194]
I see you provide a OVA file, what about a Dockerfile or compose.yaml ?

**Comment by pr4bh4sh** [comment]
+1

**Comment by bugwrangler** [comment]
In case you want android SAST automation, You can try out > https://github.com/bugwrangler/Vagrant_MobSF (I'm still working on this).

**Comment by ajinabraham** [comment]
https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/wiki/Docker-Container-for-MobSF-Static-Analysis

MobSF Static Analysis as docker image and dockerfile is available here
