### ISSUE TITLE
Don't Play Around. An Error just popped in! 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by TiagoHenriqueM** [ajinabraham/Mobile-Security-Framework-MobSF#196]
My log files:
[2016-07-17 06:49:58]
[ERROR] - Cannot perform class dump (/Users/tiago/Desktop/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios.py, LINE 510 "dat=subprocess.check_output([CLASSDUMPZ_BIN,BIN_PATH])"): Command '['/Users/tiago/Desktop/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/mac/class-dump-z', u'/Users/tiago/Desktop/Mobile-Security-Framework-MobSF/uploads/b869596cf244017643d6545ec1aca45f/Payload/teste.app/teste']' returned non-zero exit status -11

[2016-07-17 06:49:59]
[ERROR] iOS Binary Analysis (/Users/tiago/Desktop/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios.py, LINE 526 "strings=escape(strings.replace(BIN_DIR + "/",""))"): 'ascii' codec can't decode byte 0xcd in position 303415: ordinal not in range(128)

[2016-07-17 06:49:59]
[ERROR] Static Analyzer iOS (/Users/tiago/Desktop/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/ios.py, LINE 85 "INFO_PLIST,BIN_NAME,ID,VER,SDK,PLTFM,MIN,LIBS,BIN_ANAL,STRINGS=BinaryAnalysis(BIN_DIR,TOOLS_DIR,APP_DIR)"): 'NoneType' object is not iterable

Best regards,
Tiago

**Comment by ajinabraham** [comment]
Unicode Error it seems. MobSF is not completely unicode safe, atleast the ios module.

**Comment by TiagoHenriqueM** [comment]
Is it possible solve this issue?

**Comment by ajinabraham** [comment]
Should expect a fix sometime soon. iOS module is getting revamped

**Comment by TiagoHenriqueM** [comment]
When will be released the new version of MobSF?

Best regards,

**Comment by ajinabraham** [comment]
Is it possible to share the source code? Things would be easier to debug and apply a fix faster.

**Comment by TiagoHenriqueM** [comment]
I have only the ipa file.

**Comment by ajinabraham** [comment]
Tracking Separately.

**Comment by OrWest** [comment]
Hello. Also get this error with code -11

My log file:
> [28/Feb/2017 07:28:08] "GET / HTTP/1.1" 200 7690
> [INFO] MIME Type: application/octet-stream FILE: test.ipa
> 
> [INFO] Performing Static Analysis of iOS IPA
> [28/Feb/2017 07:28:11] "POST /upload/ HTTP/1.1" 200 135
> [INFO] iOS Static Analysis Started
> [INFO] iOS Binary (IPA) Analysis Started
> [INFO] Generating Hashes
> [INFO] Extracting IPA
> [INFO] Unzipping
> [INFO] Get Files, BIN Plist -> XML, and Normalize
> [INFO] iOS Info.plist Analysis Started
> [INFO] Finding Info.plist in iOS Binary
> [INFO] Checking Permissions
> [INFO] Checking for Insecure Connections
> [INFO] Starting Binary Analysis
> [INFO] Starting Otool Analysis
> [INFO] Running otool against Binary : test
> [INFO] Running class-dump-z against the Binary
> 
> [2017-02-28 07:28:12]
> [ERROR] - Cannot perform class dump (/Users/motarykinao/MobSF/StaticAnalyzer/views/ios/binary_analysis.py, LINE 207 "class_dump = subprocess.check_output([class_dump_z_bin, bin_path])"): Command '['/Users/motarykinao/MobSF/StaticAnalyzer/tools/mac/class-dump-z', u'/Users/motarykinao/MobSF/uploads/3427bddffa259aa1cbedb79bd362e8ef/Payload/test.app/test']' returned non-zero exit status -11
> [INFO] Running strings against the Binary
> 
> [2017-02-28 07:28:15]
> [ERROR] iOS Binary Analysis (/Users/motarykinao/MobSF/StaticAnalyzer/views/ios/binary_analysis.py, LINE 262 "binary_analysis_dict["bin_res"] = otool_dict["anal"] + cls_dump"): cannot concatenate 'str' and 'NoneType' objects
> 
> [INFO] Connecting to DB
> 
> [INFO] Saving to Database
> 
> [2017-02-28 07:28:15]
> [ERROR] Saving to DB (/Users/motarykinao/MobSF/StaticAnalyzer/views/ios/db_interaction.py, LINE 125 "BIN_ANAL=bin_dict["bin_res"],"): 'NoneType' object has no attribute '__getitem__'
> 
> [2017-02-28 07:28:15]
> [ERROR] Rendering to Template (/Users/motarykinao/MobSF/StaticAnalyzer/views/ios/db_interaction.py, LINE 33 "'bin_anal': bin_dict["bin_res"],"): 'NoneType' object has no attribute '__getitem__'
> [28/Feb/2017 07:28:15] "GET /StaticAnalyzer_iOS/?name=test.ipa&type=ipa&checksum=3427bddffa259aa1cbedb79bd362e8ef HTTP/1.1" 200 16173
