### ISSUE TITLE
[ERROR] xhtml2pdf is not installed. Cannot generate PDF reports (C:\tools\MobSF\ StaticAnalyzer\views\ios.py, LINE 24 "import xhtml2pdf.pisa as pisa"): cannot im port name inputstream

### ISSUE THREAD

**Issue by ahmatjan** [ajinabraham/Mobile-Security-Framework-MobSF#198]
[ERROR] xhtml2pdf is not installed. Cannot generate PDF reports (C:\tools\MobSF\
StaticAnalyzer\views\shared_func.py, LINE 27 "import xhtml2pdf.pisa as pisa"): c
annot import name inputstream
but xhtml2pdf  is installed
C:\tools\MobSF>pip install xhtml2pdf==0.0.6 --upgrade
Requirement already up-to-date: xhtml2pdf==0.0.6 in c:\python27\lib\site-package
s
Requirement already up-to-date: html5lib in c:\python27\lib\site-packages (from
xhtml2pdf==0.0.6)
Requirement already up-to-date: pyPdf2 in c:\python27\lib\site-packages (from xh
tml2pdf==0.0.6)
Requirement already up-to-date: Pillow in c:\python27\lib\site-packages (from xh
tml2pdf==0.0.6)
Requirement already up-to-date: reportlab>=2.2 in c:\python27\lib\site-packages
(from xhtml2pdf==0.0.6)
Requirement already up-to-date: six in c:\python27\lib\site-packages (from html5
lib->xhtml2pdf==0.0.6)
Requirement already up-to-date: webencodings in c:\python27\lib\site-packages (f
rom html5lib->xhtml2pdf==0.0.6)
Requirement already up-to-date: setuptools>=18.5 in c:\python27\lib\site-package
s (from html5lib->xhtml2pdf==0.0.6)
Requirement already up-to-date: pip>=1.4.1 in c:\python27\lib\site-packages (fro
m reportlab>=2.2->xhtml2pdf==0.0.6)

**Comment by ajinabraham** [comment]
`pip install pip install html5lib==1.0b8` will fix this.

**Comment by deepanshu0512** [comment]
Received same issue: It got resolved once below installation is executed

Django==1.8pyOpenSSL==0.15tornado==4.1xhtml2pdf==0.0.6psutil==3.2.1

Under Scripts folder C:\Python27\Scripts copy paste above dependency in a text file and execute

pip install -r textfilehavingabovedependncy.txt
