### ISSUE TITLE
[ERROR] Reading Code Signing Certificate (C:\MobSF\StaticAnalyzer\views.py, LINE 993 "args=[settings.JAVA_PATH+'java','-jar', CP_PATH, certfile]"): local variable 'certfile' referenced before assignment

### ISSUE THREAD

**Issue by koehntopp** [ajinabraham/Mobile-Security-Framework-MobSF#199]
[INFO] Performing Static Analysis of Android APK
[22/Jul/2016 12:37:45]"POST /Upload/ HTTP/1.1" 200 136
[INFO] Starting Analysis on : SECVALxxx.apk
[INFO] Generating Hashes
[INFO] Unzipping
[INFO] Getting Hardcoded Certificates/Keystores
[INFO] APK Extracted
[INFO] Getting Manifest from Binary
[INFO] AXML -> XML
[INFO] Parsing AndroidManifest.xml
[INFO] Extracting Manifest Data
[INFO] Manifest Analysis Started
[INFO] Formatting Permissions
[INFO] Reading Code Signing Certificate

[2016-07-22 12:37:51]
[ERROR] Reading Code Signing Certificate (C:\MobSF\StaticAnalyzer\views.py, LINE 993 "args=[settings.JAVA_PATH+'java','-jar', CP_PATH, certfile]"): local variable 'certfile' referenced before assignment

[2016-07-22 12:37:51]
[ERROR] Static Analyzer (C:\MobSF\StaticAnalyzer\views.py, LINE 411 "CERT_INFO,ISSUED=CertInfo(APP_DIR,TOOLS_DIR)"): 'NoneType' object is not iterable
[22/Jul/2016 12:37:51]"GET /StaticAnalyzer/?name=SECVALxxx.apk&type=apk&checksum=ca1314271d3b53977e6ad87ce0fdb74c HTTP/1.1" 200 4671

**Comment by koehntopp** [comment]
Happens both on Windows & MacOS, v0.9.2 beta

May be APK specific, other APKs work fine.

**Comment by ajinabraham** [comment]
https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/blob/master/StaticAnalyzer/views/android.py#L819-L828

Looks to me like that particular APK has a different type of code signing cert.

Unzip the APK and check the files in `META-INF`
Can you update the names of the files with extension.

**Comment by koehntopp** [comment]
Well, it's not signed at all ;)

Maybe that should be reported as a possible issue instead of a crash ;)

**Comment by ajinabraham** [comment]
Nice Catch!
Framework should be graceful.

**Comment by ajinabraham** [comment]
This is Fixed in the latest master. Give a try.

**Comment by koehntopp** [comment]
Works like a charm - thanks!
