### ISSUE TITLE
Docker image does not work

### ISSUE THREAD

**Issue by illnino** [ajinabraham/Mobile-Security-Framework-MobSF#201]
Hi, team

I downloaded the docker image and had a try. However, by running `docker run -i -t opensecurity/mobsf:latest`, I could see the server is running from the log. 

When I visited http://127.0.0.1:8000, the site couldnt open, but favicon could be found in the tab. Neither did http://0.0.0.0:8000, worse the favicon couldnt be found in the tab.

OS: MacOS 10.10.5.

Here is the log.

======
`➜  ~  docker pull opensecurity/mobsf
Using default tag: latest
latest: Pulling from opensecurity/mobsf

Digest: sha256:68616922d2b2ed681f17fa17db1f1d236343af9bd41d01309595543731ccf3af
Status: Image is up to date for opensecurity/mobsf:latest
➜  ~  docker run -i -t opensecurity/mobsf:latest

Mobile Security Framework v0.9.2 Beta

  __  __       _    ____  _____          ___   ___   ____
 |  \/  | ___ | |__/ ___||  ___| __   __/ _ \ / _ \ |___ \
 | |\/| |/ _ \| '_ \___ \| |_    \ \ / / | | | (_) |  __) |
 | |  | | (_) | |_) |__) |  _|    \ V /| |_| |\__, | / __/
 |_|  |_|\___/|_.__/____/|_|       \_/  \___(_) /_(_)_____|

Mobile Security Framework v0.9.2 Beta

  __  __       _    ____  _____          ___   ___   ____
 |  \/  | ___ | |__/ ___||  ___| __   __/ _ \ / _ \ |___ \
 | |\/| |/ _ \| '_ \___ \| |_    \ \ / / | | | (_) |  __) |
 | |  | | (_) | |_) |__) |  _|    \ V /| |_| |\__, | / __/
 |_|  |_|\___/|_.__/____/|_|       \_/  \___(_) /_(_)_____|

[INFO] Loading User config from: /root/.MobSF/config.py

[INFO] Finding JDK Location in Linux/MAC....

[INFO] Oracle Java is installed!

[INFO] JDK 1.7 or above is available

[WARNING] Could not find VirtualBox path.
Operations to perform:
  Apply all migrations: APITester, MobSF, StaticAnalyzer, auth, contenttypes, sessions
Running migrations:
  Rendering model states... DONE
  Applying APITester.0001_initial... OK
  Applying MobSF.0001_initial... OK
  Applying StaticAnalyzer.0001_initial... OK
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying sessions.0001_initial... OK
[INFO] Loading User config from: /root/.MobSF/config.py

[INFO] Finding JDK Location in Linux/MAC....

[INFO] Oracle Java is installed!

[INFO] JDK 1.7 or above is available

[WARNING] Could not find VirtualBox path.

Mobile Security Framework v0.9.2 Beta

  __  __       _    ____  _____          ___   ___   ____
 |  \/  | ___ | |__/ ___||  ___| __   __/ _ \ / _ \ |___ \
 | |\/| |/ _ \| '_ \___ \| |_    \ \ / / | | | (_) |  __) |
 | |  | | (_) | |_) |__) |  _|    \ V /| |_| |\__, | / __/
 |_|  |_|\___/|_.__/____/|_|       \_/  \___(_) /_(_)_____|

[INFO] Loading User config from: /root/.MobSF/config.py

[INFO] Finding JDK Location in Linux/MAC....

[INFO] Oracle Java is installed!

[INFO] JDK 1.7 or above is available

[WARNING] Could not find VirtualBox path.
Performing system checks...

System check identified no issues (0 silenced).
July 27, 2016 - 07:06:31
Django version 1.10b1, using settings 'MobSF.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
`

**Comment by ajinabraham** [comment]
This log looks good.

Get into shell and get the IP of the box
and try http://IP:8000/ 

To access the shell, try docker  `docker run -i -t opensecurity/mobsf:latest /bin/bash` to access the shell and `ifconfig` to get the local IP
Also do a curl/wget to 127.0.0.1:8000 from the shell to see if MobSF is started properly.

**Comment by illnino** [comment]
`root@86a836b018de:~/Mobile-Security-Framework-MobSF# uname -a
Linux 86a836b018de 4.4.15-moby #1 SMP Tue Jul 19 10:26:05 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@86a836b018de:~/Mobile-Security-Framework-MobSF# ifconfig
bash: ifconfig: command not found`

Any idea?

**Comment by ajinabraham** [comment]
Try `apt-get install net-tools` and `ifconfig` again

**Comment by illnino** [comment]
`root@86a836b018de:~/Mobile-Security-Framework-MobSF# apt-get install net-tools
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package net-tools`

**Comment by ajinabraham** [comment]
do a `apt-get update` and try again

**Comment by illnino** [comment]
`root@86a836b018de:~/Mobile-Security-Framework-MobSF# ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:ac:11:00:02
          inet addr:172.17.0.2  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:acff:fe11:2/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:17168 errors:0 dropped:0 overruns:0 frame:0
          TX packets:10543 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:25227400 (25.2 MB)  TX bytes:575261 (575.2 KB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
`

----

`➜  ~  curl http://127.0.0.1:8000
curl: (7) Failed to connect to 127.0.0.1 port 8000: Connection refused`

No luck.

**Comment by ajinabraham** [comment]
curl from within mobsf shell, not from your host.

**Comment by ajinabraham** [comment]
Also try http://172.17.0.2:8000 from your host and see if it's connecting.

**Comment by illnino** [comment]
Issue resolved. Need to run `docker run -it -p 8000:8000 opensecurity/mobsf:latest`.

-----
FYI.

ENV setup:

Mac OS X 10.10.3

```
➜  ~  docker version
Client:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc4
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   e4a0dbc
 Built:        Wed Jul 13 03:28:51 2016
 OS/Arch:      linux/amd64
 Experimental: true
➜  ~
```

**Comment by ajinabraham** [comment]
Oh my bad I didn't mentioned that in the Documentation on Exposing Ports to Host Machine.
Anyways Glad that you resolved it.

**Comment by justpentest** [comment]
Hello,
I was using mobsf docker on windows.
I had to do port forwarding as mentioned on the URL https://stackoverflow.com/questions/36286305/how-do-i-forward-a-docker-machine-port-to-my-host-port-on-osx

$ docker-machine env default
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"

Finally I can see mobsf on the URL http://192.168.99.100:8000
