### ISSUE TITLE
ERROR Reading Code Signing Certificate

### ISSUE THREAD

**Issue by Captain-Kludge** [ajinabraham/Mobile-Security-Framework-MobSF#202]
I'm trying to analyze an app that was made in Spain, and whoever signed the cert has some accents in their name, and it looks like the cert reader is assuming that the cert will be ASCII. 

summary of error log:

.....StaticAnalyzer\views.py, LINE 996 "dat=escape(subprocess.check_output(args)).replace('\n', '</br>'): 'ascii' codec can't decode byte 0xe1 in position 0: ordinal not in range

ERROR Static Analyzer (...\views.py, LINE 411 "CERT_INFO,ISSUED=CertInfo(APP_DIR,TOOLS_DIR)"): 'NoneType' object is not iterable

I've been trying various workarounds just so I can get in to the meat of the app itself, but none have succeeded so far (which is not surprising given my coding skills). 

Let me know if you need anything else to help!

It's a great program, glad I saw the presentation at AppSec EU!

**Comment by ajinabraham** [comment]
Unicode Problem it seems.

As a quick fix you can disable Cert Parsing. For that on Line 411, replace `CERT_INFO,ISSUED=CertInfo(APP_DIR,TOOLS_DIR)` with `CERT_INFO,ISSUED=['','']`

**Comment by Captain-Kludge** [comment]
That works great, thanks!
