### ISSUE TITLE
IPA static analysis(Bug?)

### ISSUE THREAD

**Issue by Hyet** [ajinabraham/Mobile-Security-Framework-MobSF#204]
Hi i tried to use MobSF for static analysis but it could not run showing this.
(with Mac os , APK static analysis is ok)
"
Don't Play Around. An Error just popped in!
global name 'platform' is not defined

Name not found globally.
"

The log file
"
[2016-07-29 06:48:30]
[ERROR] Unzipping Error (/Users/jenkins/Documents/MOBSF/StaticAnalyzer/views/shared_func.py, LINE 59 "z.extractall(EXT_PATH)"): 'ascii' codec can't decode byte 0xe6 in position 44: ordinal not in range(128)
[2016-07-29 06:48:30]
[ERROR] Static Analyzer iOS (/Users/jenkins/Documents/MOBSF/StaticAnalyzer/views/ios.py, LINE 84 "Unzip(APP_PATH,APP_DIR)               #EXTRACT IPA"): global name 'platform' is not defined
"

**Comment by ajinabraham** [comment]
platform should be an inbuilt module.
See if https://docs.python.org/2/library/platform.html is installed on your syste,m
Also some unicode problems, seems like a duplicate bug: #196
