### ISSUE TITLE
Don't Play Around. An Error just popped in! (ipa files)

### ISSUE THREAD

**Issue by AlexandreVargas** [ajinabraham/Mobile-Security-Framework-MobSF#205]
Hi,

To showed it:

Don't Play Around. An Error just popped in!
'NoneType' object is not utterable
Inappropriate argument type.

[INFO] Performing Static Analysis of iOS IPA
[30/Jul/2016 15:57:39] "POST /Upload/ HTTP/1.1" 200 144
[INFO] iOS Static Analysis Started
[INFO] iOS Binary (IPA) Analysis Started
[INFO] Generating Hashes
[INFO] Extracting IPA
[INFO] Unzipping
[INFO] Get Files, BIN Plist -> XML, and Normalize
[INFO] Starting Binary Analysis
[INFO] Reading Info.plist[2016-07-30 15:57:40]

[ERROR] - Reading from Info.plist (/.../Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/ios.py, LINE 396 "p=plistlib.readPlistFromString(XML)"): 'ascii' codec can't encode characters in position 3337-3338: ordinal not in range(128)

[2016-07-30 15:57:40]
[ERROR] iOS Binary Analysis (/.../Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/ios.py, LINE 527 "strings=escape(strings.replace(BIN_DIR + "/",""))"): 'ascii' codec can't decode byte 0xbd in position 13155: ordinal not in range(128)

[2016-07-30 15:57:40]
[ERROR] Static Analyzer iOS (/.../Documents/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/ios.py, LINE 86 "INFO_PLIST,BIN_NAME,ID,VER,SDK,PLTFM,MIN,LIBS,BIN_ANAL,STRINGS=BinaryAnalysis(BIN_DIR,TOOLS_DIR,APP_DIR)"): 'NoneType' object is not iterable

Help me about these issues.

Follow up more information:

Alexandres-Mac:~ alexandrevargas$ java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

Alexandres-Mac:~ alexandrevargas$ python --version
Python 2.7.11

But I have django 1.9.8 version, and I don't believe that, it is cause theses errors.

Kind regards,
Alexandre

**Comment by ajinabraham** [comment]
The errors are due to unicode characters in the IPA/zip file you are uploading. This is a known bug. I am working on a fix now

**Comment by ajinabraham** [comment]
Duplicate of #196

**Comment by VijaySokkala** [comment]
Hi Ajin,

Please help out me to solve below issue

[17/May/2018 12:19:05] "GET / HTTP/1.1" 200 7727
[INFO] MIME Type: application/octet-stream FILE: MyContact.ipa

[INFO] Performing Static Analysis of iOS IPA
[17/May/2018 12:19:16] "POST /upload/ HTTP/1.1" 200 147
[INFO] iOS Static Analysis Started
[INFO] iOS Binary (IPA) Analysis Started
[INFO] Generating Hashes
[INFO] Extracting IPA
[INFO] Unzipping

[2018-05-17 12:19:17]
[ERROR] Unzipping Error (/Users/TECH/Downloads/Mobile-Security-Framework-MobSF-0.9.5.5/StaticAnalyzer/views/shared_func.py, LINE 75 "with zipfile.ZipFile(app_path, "r") as zipptr:"): File is not a zip file

[INFO] Using the Default OS Unzip Utility.
[/Users/TECH/Downloads/Mobile-Security-Framework-MobSF-0.9.5.5/uploads/8rt4f38ad3ecc01cd4d35ac15a104713e4b/8f38ad3ecc01cd4dge344hg5104713e4b.ipa]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/TECH/Downloads/Mobile-Security-Framework-MobSF-0.9.5.5/uploads/8f38ad3ecc01cd4dge344hg5104713e4b/8f38ad3ecc01cd4dge344hg5104713e4b.ipa or
        /Users/TECH/Downloads/Mobile-Security-Framework-MobSF-0.9.5.5/uploads/8f38ad3ecc01cd4dge344hg5104713e4b/8f38ad3ecc01cd4dge344hg5104713e4b.ipa.zip, and cannot find /Users/TECH/Downloads/Mobile-Security-Framework-MobSF-0.9.5.5/uploads/8f38ad3ecc01cd4dge344hg5104713e4b/8f38ad3ecc01cd4dge344hg5104713e4b.ipa.ZIP, period.
[/Users/TECH/Downloads/Mobile-Security-Framework-MobSF-0.9.5.5/uploads/8f38ad3ecc01cd4dge344hg5104713e4b/8f38ad3ecc01cd4dge344hg5104713e4b.ipa]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/TECH/Downloads/Mobile-Security-Framework-MobSF-0.9.5.5/uploads/8f38ad3ecc01cd4dge344hg5104713e4b/8f38ad3ecc01cd4dge344hg5104713e4b.ipa or
        /Users/TECH/Downloads/Mobile-Security-Framework-MobSF-0.9.5.5/uploads/8f38ad3ecc01cd4dge344hg5104713e4b/8f38ad3ecc01cd4dge344hg5104713e4b.ipa.zip, and cannot find /Users/TECH/Downloads/Mobile-Security-Framework-MobSF-0.9.5.5/uploads/8f38ad3ecc01cd4dge344hg5104713e4b/8f38ad3ecc01cd4dge344hg5104713e4b.ipa.ZIP, period.

[2018-05-17 12:19:17]
[ERROR] Unzipping Error (/Users/TECH/Downloads/Mobile-Security-Framework-MobSF-0.9.5.5/StaticAnalyzer/views/shared_func.py, LINE 93 "dat = subprocess.check_output(['unzip', '-qq', '-l', app_path])"): Command '['unzip', '-qq', '-l', u'/Users/TECH/Downloads/Mobile-Security-Framework-MobSF-0.9.5.5/uploads/8f38ad3ecc01cd4dge344hg5104713e4b/8f38ad3ecc01cd4dge344hg5104713e4b.ipa']' returned non-zero exit status 9
[INFO] Get Files, BIN Plist -> XML, and Normalize
[INFO] iOS Info.plist Analysis Started
[INFO] Finding Info.plist in iOS Binary

[2018-05-17 12:19:17]
[ERROR] - Reading from Info.plist (/Users/TECH/Downloads/Mobile-Security-Framework-MobSF-0.9.5.5/StaticAnalyzer/views/ios/plist_analysis.py, LINE 214 "dirs = os.listdir(src)"): [Errno 2] No such file or directory: '/Users/TECH/Downloads/Mobile-Security-Framework-MobSF-0.9.5.5/uploads/8f38ad3ecc01cd4dge344hg5104713e4b/Payload/'
[INFO] Starting Binary Analysis

[2018-05-17 12:19:17]
[ERROR] iOS Binary Analysis (/Users/TECH/Downloads/Mobile-Security-Framework-MobSF-0.9.5.5/StaticAnalyzer/views/ios/binary_analysis.py, LINE 242 "dirs = os.listdir(src)"): [Errno 2] No such file or directory: '/Users/TECH/Downloads/Mobile-Security-Framework-MobSF-0.9.5.5/uploads/8f38ad3ecc01cd4dge344hg5104713e4b/Payload/'

[INFO] Connecting to DB

[INFO] Saving to Database

[2018-05-17 12:19:17]
[ERROR] Saving to DB (/Users/TECH/Downloads/Mobile-Security-Framework-MobSF-0.9.5.5/StaticAnalyzer/views/ios/db_interaction.py, LINE 118 "INFOPLIST=info_dict["plist_xml"],"): 'NoneType' object has no attribute '__getitem__'

[2018-05-17 12:19:17]
[ERROR] Rendering to Template (/Users/TECH/Downloads/Mobile-Security-Framework-MobSF-0.9.5.5/StaticAnalyzer/views/ios/db_interaction.py, LINE 26 "'plist': info_dict["plist_xml"],"): 'NoneType' object has no attribute '__getitem__'
[ERROR] 'NoneType' object does not support item assignment
[17/May/2018 12:19:17] "GET /StaticAnalyzer_iOS/?name=MyContact.ipa&type=ipa&checksum=8f38ad3ecc01cd4dge344hg5104713e4b HTTP/1.1" 500 4747

Thanks
Vijay Kumar S

**Comment by ajinabraham** [comment]
The error says `with zipfile.ZipFile(app_path, "r") as zipptr:"): File is not a zip file`
Can you share the IPA?

**Comment by VijaySokkala** [comment]
file is not zip file its .ipa file and please tell me if need to disable or enable something while build .ipa file for project
Sorry for that, ipa file is confidential

**Comment by VijaySokkala** [comment]
Yes i have done that also, still have same issue ajin 

Thanks
Vijay S

**Comment by ajinabraham** [comment]
Without the IPA we can't troubleshoot anything.
