### ISSUE TITLE
Getting error while Finishing Dynamic Analyser

### ISSUE THREAD

**Issue by deepakexodia** [ajinabraham/Mobile-Security-Framework-MobSF#206]
pls find the logs of the issue

[2016-08-01 17:50:57]
[ERROR] Device Data Dump (C:\MobSF\DynamicAnalyzer\views\android.py, LINE 332 "if "MOBSEC-TAR-CREATED" in subprocess.check_output([adb, "-s", getIdentifier(), "shell", "cat", "/sdcard/mobsec_status"]):"): Command '['C:\MobSF\DynamicAnalyzer/tools/adb/windows/adb.exe', '-s', '192.168.56.101:5555', 'shell', 'cat', '/sdcard/mobsec_status']' returned non-zero exit status -1

and let me know how to resolve it

**Comment by ajinabraham** [comment]
Should be  fine. Does this break anything?

**Comment by deepakexodia** [comment]
not yet, so far Dynamic Analyser seems to wok fine

**Comment by deepakexodia** [comment]
BTW thanks for prompt reply

**Comment by tachencko** [comment]
Hello, first of all thank the creation of this Framework because it is very useful.

I am ending the dynamic analysis, I click Finish and gives me this error, unable to finish the task. Any ideas?




> [ERROR] Device Data Dump (/home/android/Documents/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android.py, LINE 332 "if "MOBSEC-TAR-CREATED" in subprocess.check_output([adb, "-s", getIdentifier(), "shell", "cat", "/sdcard/mobsec_status"]):"): Command '['/home/android/Documents/Mobile-Security-Framework-MobSF/DynamicAnalyzer/tools/adb/linux/adb', '-s', '192.168.1.61:5555', 'shell', 'cat', '/sdcard/mobsec_status']' returned non-zero exit status 255

**Comment by ajinabraham** [comment]
The error is fine most of the time. Are you getting the Dynamic Analysis Result?

**Comment by tachencko** [comment]
No, I get the final result. Throws that error in the Terminal, and the Web part (test completed) do not let anything else.

I mean, does not end the dynamic analysis and therefore do not get the results.

PS: It happens with different APK'S

**Comment by ajinabraham** [comment]
So are you telling that the analyisis get stuck and the results page doesn't show up?
Are you using MobSF VM or a different one?

**Comment by tachencko** [comment]
Exact. Each view that attempt to "finalize" a dynamic analysis (always talk of dynamic analysis) of the apk, I returned the mistake I commented:

"[ERROR] Device Data Dump (/home/android/Documents/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android.py, LINE 332" if "MOBSEC-TAR-CREATED" in ....... ................ "and then everything is" frozen "and can not get the report / results of the dynamic analysis of MobSF.

Use Android Tamer VM, with MobSF downloaded via github (latest version), and use a terminal physical android, rooted. Basically because I have many problems with virtual machines (VMs) for detecting adb, ethernet network as they are in other subnets and continually I have problems to "look" between them. Therefore use a physical terminal.

**Comment by ajinabraham** [comment]
If VM is giving trouble, you can try using a real device. https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/wiki/1.-Documentation#configuring-rooted-android-devicecustom-vm-with-mobsf

The above error should not affect you ideally.

**Comment by ITmustang** [comment]
@ajinabraham im getting a similar issue, i run the dynamic analyzer and get several of these...  (im using latest mobsf version and on real device. thanks!

[ERROR] adb_command (/opt/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/shared.py, LINE 67 "result = subprocess.check_output(args)"): Command '['/opt/Mobile-Security-Framework-MobSF/DynamicAnalyzer/tools/adb/linux/adb', '-s', '192.168.1.16:5555', 'pull', '/data/local/screen.png', '/opt/Mobile-Security-Framework-MobSF/uploads/9cc1f13ea9f9f88a3c28f698300ccf84/screenshots-apk/expact-1.png']' returned non-zero exit status 1.

then it finishes and and i hit the finish button and it states that its dumping logs, etc, etc and it prints out the following... 

[INFO] Collecting Data and Cleaning Up

[INFO] Downloading Logcat logs

[2018-09-11 17:34:36]
[ERROR] adb_command (/opt/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/shared.py, LINE 67 "result = subprocess.check_output(args)"): Command '['/opt/Mobile-Security-Framework-MobSF/DynamicAnalyzer/tools/adb/linux/adb', '-s', '192.168.1.16:5555', 'pull', '/data/data/de.robv.android.xposed.installer/log/error.log', '/opt/Mobile-Security-Framework-MobSF/uploads/9cc1f13ea9f9f88a3c28f698300ccf84/x_logcat.txt']' returned non-zero exit status 1.

[INFO] Downloading Droidmon API Monitor Logcat logs

[INFO] Downloading Dumpsys logs

[INFO] Stopping Application

[INFO] Stopping ScreenCast Service
[11/Sep/2018 17:34:58] "POST /FinalTest/ HTTP/1.1" 200 16

[INFO] Downloading Application Data from Device
127.0.0.1:37366: clientconnect
[INFO] Killing CapFuzz UI
127.0.0.1:37366: HTTP protocol error in client request: Invalid HTTP request form (expected: authority or absolute, got: relative)
127.0.0.1:37366: clientdisconnect
127.0.0.1:37368: clientconnect

[INFO] Deleting Dump Status File

[INFO] Creating TAR of Application Files.

[INFO] Waiting for TAR dump to complete...

[ERROR] TAR Generation Failed. Process timed out.

[INFO] Dumping Application Files from Device/VM

[2018-09-11 17:39:59]
[ERROR] adb_command (/opt/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/shared.py, LINE 67 "result = subprocess.check_output(args)"): Command '['/opt/Mobile-Security-Framework-MobSF/DynamicAnalyzer/tools/adb/linux/adb', '-s', '192.168.1.16:5555', 'pull', '/data/local/com.chipotle.ordering.tar', '/opt/Mobile-Security-Framework-MobSF/uploads/9cc1f13ea9f9f88a3c28f698300ccf84/com.chipotle.ordering.tar']' returned non-zero exit status 1.

[INFO] Stopping ADB
[11/Sep/2018 17:39:59] "POST /DumpData/ HTTP/1.1" 200 15

[INFO] Dynamic Analysis Report Generation

[INFO] Dynamic API Analysis

[2018-09-11 17:39:59]
[ERROR] Dynamic API Analysis (/opt/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/analysis.py, LINE 42 "with open(location, "r") as flip:"): [Errno 2] No such file or directory: '/opt/Mobile-Security-Framework-MobSF/uploads/9cc1f13ea9f9f88a3c28f698300ccf84/x_logcat.txt'

[INFO] Dynamic File Analysis

[2018-09-11 17:39:59]
[ERROR] Dynamic Analysis Report Generation (/opt/Mobile-Security-Framework-MobSF/DynamicAnalyzer/views/android/dynamic.py, LINE 660 "analysis_result = run_analysis(app_dir, md5_hash, package)"): [Errno 2] No such file or directory: '/opt/Mobile-Security-Framework-MobSF/uploads/9cc1f13ea9f9f88a3c28f698300ccf84/x_logcat.txt'

**Comment by ajinabraham** [comment]
From the logs it looks like the Device is preventing file access. Is it rooted properly?

Try running the following command independently and see if adb can pull files from the device. If not, fix that first.

`adb -s 192.168.1.16:5555 pull /data/data/de.robv.android.xposed.installer/log/error.log /tmp/x_logcat.txt`

**Comment by ajinabraham** [comment]
You need to mount the storage before trying to access the file. Once you mount and access the file let me know the mounting command that you have used.

**Comment by ITmustang** [comment]
@ajinabraham sorry for delay. so ive come to the conclusion that something isnt right with the root on my android test phone, ive checked and recheck permissions, etc and everything looks good permissions wise.  I can do this adb -s command on my rooted android tablet and it works perfectly. for now i need to work on perhaps resetting and re-rooting my android phone.

**Comment by hishammir** [comment]
Following.
My configuration is Android 5.0.0 running on GenyMotion and Xposed is working properly so is adb.

**Comment by iceboym2m** [comment]
Static Analysis works correclty but i have same problem on Dynamic Analysis; 
and got some error but do not stuck, before reporting the result ,it stuck and return Error.
![Screenshot from 2019-07-17 16-07-23](https://user-images.githubusercontent.com/52599405/61372651-fd5bbd80-a8ac-11e9-9b5e-d22c7c2bc780.png)
in VM(vb+genymotion) i have similar problem too :
![Screenshot from 2019-07-17 15-57-20](https://user-images.githubusercontent.com/52599405/61372850-6d6a4380-a8ad-11e9-8127-a177188b3212.png)
could you please gimme some information about it ?

**Comment by ajinabraham** [comment]
You need to enable 32 bit execution support in Kali.
If your Kali Linux is a VM it won't work. MobSF has to run on host machine.

**Comment by iceboym2m** [comment]
I have a special thanks to you;
That problem solved after modifying and checking all configuration from
beginning.
I have another question; is there any way to analysis all applications with
any api level dynamically?
I checked some apk files and found that MobSF on vm (ova) can do dynamic
analysis on some of application.

Sincerely;
Zackariya

**Comment by ajinabraham** [comment]
Use a real rooted android device that support the API version you need.

**Comment by sewinturan** [comment]
Hello,
I installed the application on the MacOS. But when I install the .apk file I get an error like this. Can you help me?

Error
Raised when run() is called with check=True and the process returns a non-zero exit status. Attributes: cmd, returncode, stdout, stderr, output

Command '['java', '-jar', '/Users/macbookpro/Desktop/Mobsf/Mobile-Security-Framework-MobSF/StaticAnalyzer/tools/baksmali-2.3.4.jar', 'list', 'classes', '/Users/macbookpro/Desktop/Mobsf/Mobile-Security-Framework-MobSF/uploads/5056143f11c8a34b5d875d808360d3be/classes2.dex']' returned non-zero exit status 1.

**Comment by ajinabraham** [comment]
You need to install required version of Java and set JAVA_HOME environment variable or set JAVA path in settings.py

**Comment by osabri009** [comment]
I keep getting this any ideas?
[INFO] 14/Apr/2024 05:42:24 - Connecting to Android adb://192.168.56.101:5555
[INFO] 14/Apr/2024 05:42:24 - Waiting for 2 seconds...
[ERROR] 14/Apr/2024 05:42:26 - Error Running ADB Command
Traceback (most recent call last):
  File "/home/mobsf/Mobile-Security-Framework-MobSF/mobsf/DynamicAnalyzer/views/android/environment.py", line 167, in adb_command
    result = subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/adb', '-s', 'adb://192.168.56.101:5555', 'shell', 'getprop', 'ro.build.version.release']' returned non-zero exit status 1.
[INFO] 14/Apr/2024 05:42:34 - MobSFying Android instance
[INFO] 14/Apr/2024 05:42:37 - ADB Restarted
[INFO] 14/Apr/2024 05:42:37 - Waiting for 2 seconds...
[INFO] 14/Apr/2024 05:42:39 - Connecting to Android adb://192.168.56.101:5555
[INFO] 14/Apr/2024 05:42:39 - Waiting for 2 seconds...
[INFO] 14/Apr/2024 05:42:41 - Restarting ADB Daemon as root
adb: unable to connect for root: device 'adb://192.168.56.101:5555' not found
[ERROR] 14/Apr/2024 05:42:41 - MobSFying Android instance failed
