### ISSUE TITLE
The Video course server is too slow to watch

### ISSUE THREAD

**Issue by windyzxcui** [ajinabraham/Mobile-Security-Framework-MobSF#207]
hi Ajin, I spent $20 to buy the video course in OpSecX, but the server is very slow. It is too slow to watch the completed course. Can you please guide me how to see the course smoothly? Or please return my money. Thanks

**Comment by ajinabraham** [comment]
This is a bug tracker for Mobile Security Framework not for OpSecX.
Anyways I had informed Customer Support Team regarding your issue. They will get back to you via Email.
