### ISSUE TITLE
[ERROR] PDF Report Generation Error

### ISSUE THREAD

**Issue by aaronthomas1406** [ajinabraham/Mobile-Security-Framework-MobSF#208]
I am receiving the following error when I try to download the pdf version of the report. 

PDF Error: 
[ERROR] PDF Report Generation Error (/MobSF/Mobile-Security-Framework-MobSF-0.9.2/StaticAnalyzer/views.py, LINE 148 "pdf = pisa.pisaDocument(StringIO( "{0}".format(html.encode('utf-8'))), result, encoding='utf-8')"): global name 'pisa' is not defined

Please assist me in fixing this error. 

Thanks in advance for your help!

**Comment by ajinabraham** [comment]
`pip install -r requirements.txt && pip install html5lib==1.0b8`should fix it

**Comment by aaoconno** [comment]
I confirm, ajinabraham commented on Aug 4,  pip install html5lib==1.0b8,  fixed the problem for me.

**Comment by VijaySokkala** [comment]
hi abraham,
Could you pls help me to come out from below issue
i.e I got error when i click on Download report link

"
## Don't Play Around. An Error just popped in!

Inappropriate argument type.

__init__() got an unexpected keyword argument 'status_code'
"
above thing is an error

Thanks in advance

**Comment by ajinabraham** [comment]
Use the latest master

**Comment by VijaySokkala** [comment]
{"pdf_error": "Cannot Generate PDF", "err_details": "wkhtmltopdf exited with non-zero code 127. error:\n/usr/bin/wkhtmltopdf: error while loading shared libraries: libQt5WebKitWidgets.so.5: cannot open shared object file: No such file or directory\n"}

I got thiserror after clone the updated code and clcik on the Download report link

**Comment by VijaySokkala** [comment]
I have download the wkhtmltopdf.tar.xz and extracted
extracted file consist 4 directories
wt is the next step

**Comment by VijaySokkala** [comment]
ie bin, include, lib and share 

here there is no python files for install

Thanks in advance

Thanks
Vijay S

**Comment by ajinabraham** [comment]
Read the installation instruction of wkhtmltopdf

**Comment by VijaySokkala** [comment]
Thank you abraham 
 An issue is resolved

**Comment by VijaySokkala** [comment]
I have copied bin folder files into /usr/bin/ folder of the system. Then ran the application and successfully generate the pdf report for the respective apk

**Comment by VijaySokkala** [comment]
I have copied bin folder files into /usr/bin/ folder of the system. Then ran the application and successfully generate the pdf report for the respective apk

**Comment by pjadon-mn** [comment]
I am getting 'bool' object has no attribute 'dumps' exception when I click on Download Report in Mob SF Static Analyzer

The below is shown on console
[INFO] Fetching data from DB for PDF Report Generation (Android)

[INFO] Analysis is already Done. Fetching data from the DB...
INFO: Could not find files for the given pattern(s).
←[1m←[91m[ERROR] 'bool' object has no attribute 'dumps'←[0m
Internal Server Error: /PDF/

**Comment by ajinabraham** [comment]
Please provide logs

**Comment by niklasgadau** [comment]
**I have the same issue:**
Here are my logs:

./logs/MobSF.log says: `[2018-11-30 15:44:19]
[ERROR] 'bool' object has no attribute 'dumps'`

runserver log says:
`OS: Linux
Platform: Linux-4.15.0-29-generic-x86_64-with-Ubuntu-18.04-bionic
Dist: ('Ubuntu', '18.04', 'bionic')
[WARNING] Could not find VirtualBox path.
[INFO] MobSF Basic Environment Check
[INFO] Checking for Update.
[INFO] No updates available.
System check identified no issues (0 silenced).`

**Comment by ajinabraham** [comment]
Have you installed wkhtmltopdf?

**Comment by niklasgadau** [comment]
Yes, i did!
(venv) nga@nga:~/Documents/Mobile-Security-Framework-MobSF$ sudo apt-get install wkhtmltopdf
[sudo] password for nga:
Reading package lists... Done
Building dependency tree
Reading state information... Done
wkhtmltopdf is already the newest version (0.12.4-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by niklasgadau** [comment]
Any other ideas to resolve this issue?

**Comment by ajinabraham** [comment]
This error comes when `wkhtmltopdf` is not installed properly/available to MobSF.
Can you try this from terminal and see if it's working?
```
wkhtmltopdf http://google.com google.pdf
```

**Comment by ajinabraham** [comment]
Looks like wkhtmltopdf is working fine. Can you share the APK over email to investigate this further.

**Comment by pjadon-mn** [comment]
@ajinabraham 
>>> import subprocess
>>> import capfuzz
>>> subprocess.Popen(["capfuzz", "-m", "capture", "-p", "1337", "-n", "foo"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by bloodzer0** [comment]
> I am getting 'bool' object has no attribute 'dumps' exception when I click on Download Report in Mob SF Static Analyzer
> 
> The below is shown on console
> [INFO] Fetching data from DB for PDF Report Generation (Android)
> 
> [INFO] Analysis is already Done. Fetching data from the DB...
> INFO: Could not find files for the given pattern(s).
> ←[1m←[91m[ERROR] 'bool' object has no attribute 'dumps'←[0m
> Internal Server Error: /PDF/

I have encountered the same problem, I would like to ask how you solved it.

**Comment by ajinabraham** [comment]
If you have wkhtmltopdf installed and still seeing this. Please share the APK for further debugging.

**Comment by Joyoe** [comment]
> wkhtmltopdf

Thanks a lot, by reinstalling wkhtmltopdf, my issue has gone!
