### ISSUE TITLE
pdf generated report overlapping texts

### ISSUE THREAD

**Issue by c0ldb00t3r** [ajinabraham/Mobile-Security-Framework-MobSF#210]
after generating report everytime  permission & status are overlapped each other  and issue & severity also not in proper order

**Comment by ajinabraham** [comment]
Can you share a sample report generated with such problems

**Comment by dipadas** [comment]
[diva.pdf](https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/files/422368/diva.pdf)


Here is the sample pdf report

**Comment by c0ldb00t3r** [comment]
![mobsf](https://cloud.githubusercontent.com/assets/10518727/17764871/e5d7abdc-653f-11e6-84b7-48a2a5aed6e4.jpg)

**Comment by maxchill** [comment]
Seems to me like the Status column could be thinner, or some kind of wrapping can be applied to the Permission column

**Comment by ajinabraham** [comment]
Looks like an issue with html5lib, which is no more maintained. looking for an alternative for PDF generation

**Comment by ajinabraham** [comment]
This is temporarly fixed in master branch. Make sure you generate PDF for a new scan and not an old one.
