### ISSUE TITLE
Error while Finishing Dynamic Analyser

### ISSUE THREAD

**Issue by B-hzwsuki** [ajinabraham/Mobile-Security-Framework-MobSF#212]
Don't Play Around. An Error just popped in!

[INFO] Dynamic Analysis Report Generation

[INFO] Dynamic API Analysis

[2016-08-09 22:47:08]
[ERROR] Dynamic API Analysis (E:\Mobile-Security-Framework-MobSF-master-2\DynamicAnalyzer\views.py, LINE 681 "with open(LOCATION,"r") as f:"): [Errno 2] No such file or directory: u'E:\Mobile-Security-Framework-MobSF-master-2\uploads/f8d8abeb06893969bedcb846f348810a/x_logcat.txt'

[INFO] Dynamic File Analysis

[2016-08-09 22:47:08]
[ERROR] Dynamic Analysis Report Generation (E:\Mobile-Security-Framework-MobSF-master-2\DynamicAnalyzer\views.py, LINE 483 "URL,DOMAINS,EMAIL,HTTP,XML,SQLiteDB,OtherFiles=RunAnalysis(APP_DIR,MD5,PKG)"): [Errno 2] No such file or directory: u'E:\Mobile-Security-Framework-MobSF-master-2\uploads/f8d8abeb06893969bedcb846f348810a/x_logcat.txt'
How to resolve it

**Comment by ajinabraham** [comment]
For all APK or just one APK?

**Comment by B-hzwsuki** [comment]
All APK

**Comment by javixeneize** [comment]
Hi

Same error here

I can see webtraffic.txt, logcat.txt and dump.txt, but x_logcat.txt doesnt seem to be created

Should it be looking after logcat.txt intstead of x_logcat.txt?

**Comment by ajinabraham** [comment]
Both logcat and x_logcat should be there. Can you try the latest master and see if the problem still exists. Also are you using the default MobSF shipped VM for Dynamic Analysis?

**Comment by javixeneize** [comment]
Same issue. I am using a device, not the VM. x_logcat doesnt exist

**Comment by ajinabraham** [comment]
That could be the reason. This can happen if you haven't rooted the device properly, or enabled grant root automatically or xposed framework may not be installed properly along with xposed modules. Make sure that the configuration is done correctly.
