### ISSUE TITLE
Understanding the framework

### ISSUE THREAD

**Issue by ydevis803** [ajinabraham/Mobile-Security-Framework-MobSF#213]
Hi, This is not a bug or issue more like an understading of what the software does.

I have read the documentation and used the tool, however I would like to know more in details the types of security vulnerabilities this tool attempts to find? or what are the rules that you have set up to check against the applications?

Thank you

**Comment by ajinabraham** [comment]
The best thing is to go through the source code.
At a high level the tool do static analysis of Android Code and find out the possible security issues in Java and Android Manifest, Same with Objective C in the Case of iOS provided that the source code is available. For iOS binaries static analysis is done on the plist files and binary executable. 

Again it performs dynamic analysis of android Apps wherein the framework capture data in the background while the tester navigates through the different flows of the application and perform security analysis on the data. Also the Web APIs called are collected and fuzzed to identify web venerabilities.
