### ISSUE TITLE
MobSF_VM_0.2:Most APK run crash

### ISSUE THREAD

**Issue by B-hzwsuki** [ajinabraham/Mobile-Security-Framework-MobSF#214]
![image](https://cloud.githubusercontent.com/assets/20922901/17580863/6e6cde2a-5fd4-11e6-8125-de2e9892e9d4.png)
When I use androidx86_5.1(arm) run apk normal
How do I fix this problem？ thanks

**Comment by ajinabraham** [comment]
Problem with missing SO's or libs. You should use a real device or a different VM
