### ISSUE TITLE
False Posivitives related to C code

### ISSUE THREAD

**Issue by kurbbrtown** [ajinabraham/Mobile-Security-Framework-MobSF#215]
Is it common to received false positives on .IPA files coded in Swift?  I have a string of vulnerabilities being reported for Library functions associated with C code even thought no C code is in use.. Is this a known issue?

**Comment by ajinabraham** [comment]
Can you share a report or something so that I can comment more on this

**Comment by kurbbrtown** [comment]
Ajin,

Thx for your response.. Below is a snapshot of the results.  My development team is advising that Objective C is not used at all in the app.  The app is written entirely in SWIFT.  We tested removing the calls to the third party binaries and many of the findings below still remained.  Are there any known open issues that might be causing this..

[cid:image001.png@01D1FC55.8CBCFAF0]


Thank You

-------------------------------------------------------------------------------------------------------------------------------
Kurby Brown | Senior Security Analyst | iCIMS
Telephone: 732-520-7777 | Email: Kurby.Brown@icims.com<mailto:Kurby.Brown@icims.com>

[https://icimsinc.sharepoint.com/Style%20Library/Watercooler/images/email_signature/facebook_icon.png]<https://www.facebook.com/iCIMSTalentPlatform>[https://icimsinc.sharepoint.com/Style%20Library/Watercooler/images/email_signature/linkedin_icons.png]<https://www.linkedin.com/groups?gid=2568436&trk=hb_side_g>[https://icimsinc.sharepoint.com/Style%20Library/Watercooler/images/email_signature/twitter_icon.png]<https://twitter.com/iCIMS>[https://icimsinc.sharepoint.com/Style%20Library/Watercooler/images/email_signature/glassdoor_icon.png]<http://www.glassdoor.com/Overview/Working-at-iCIMS-EI_IE34908.11,16.htm>[https://icimsinc.sharepoint.com/Style%20Library/Watercooler/images/email_signature/instagram_icon.png]<https://instagram.com/icims_inc/>[https://icimsinc.sharepoint.com/Style%20Library/Watercooler/images/email_signature/hei-round.png]<http://www.icims.com/hire-expectations-institute#email>

Love iCIMS? Refer a Friend<http://care.icims.com/Refer-a-Friend>!

[https://icimsinc.sharepoint.com/Style%20Library/Watercooler/images/email_signature/icims_logo.png]

**Comment by ajinabraham** [comment]
You might want to upload the report in this github issue tracker so that I can access it

**Comment by ajinabraham** [comment]
Closing due to lack of response.
