### ISSUE TITLE
OVA, support for Cloud Environments

### ISSUE THREAD

**Issue by aaronweaver** [ajinabraham/Mobile-Security-Framework-MobSF#218]
I'd like to run MobSF in the cloud and docker works perfectly, however the OVA needs to be converted to support AWS. How are you building the OVA that you reference for download?

**Comment by bugwrangler** [comment]
+1

**Comment by ajinabraham** [comment]
Your Cloud hosting like digital ocean or Amazon are Virtual Environments. The last time I checked they don't allow complex VMs to be run inside a VM. As you need to run the MobSF VM inside the Host OS, considering the above fact it's not possible to Boot MobSF VM inside another VM that is virtualized on infrastructures like Xen. It worked in ESXi though.
