### ISSUE TITLE
Problems downloading reports

### ISSUE THREAD

**Issue by ydevis803** [ajinabraham/Mobile-Security-Framework-MobSF#219]
Hi, I am having the following error when I try to download the report:
[ERROR] xhtml2pdf is not installed. Cannot generate PDF reports (/root/Downloads/Mobile-Security-Framework-MobSF-0.9.2/StaticAnalyzer/views.py, LINE 20 "import xhtml2pdf.pisa as pisa"): cannot import name inputstream

However, the library is installed in my computer:
root@kali:~# pip install xhtml2pdf
Requirement already satisfied (use --upgrade to upgrade): xhtml2pdf in ./.local/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): html5lib in ./.local/lib/python2.7/site-packages (from xhtml2pdf)
Requirement already satisfied (use --upgrade to upgrade): pyPdf2 in ./.local/lib/python2.7/site-packages (from xhtml2pdf)
Requirement already satisfied (use --upgrade to upgrade): Pillow in ./.local/lib/python2.7/site-packages (from xhtml2pdf)
Requirement already satisfied (use --upgrade to upgrade): reportlab>=2.2 in /usr/local/lib/python2.7/dist-packages (from xhtml2pdf)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from html5lib->xhtml2pdf)
Requirement already satisfied (use --upgrade to upgrade): webencodings in /usr/local/lib/python2.7/dist-packages (from html5lib->xhtml2pdf)
Requirement already satisfied (use --upgrade to upgrade): setuptools>=18.5 in ./.local/lib/python2.7/site-packages (from html5lib->xhtml2pdf)
Requirement already satisfied (use --upgrade to upgrade): pip>=1.4.1 in /usr/lib/python2.7/dist-packages (from reportlab>=2.2->xhtml2pdf)

root@kali:~# pip install --upgrade  xhtml2pdf
Requirement already up-to-date: xhtml2pdf in ./.local/lib/python2.7/site-packages
Requirement already up-to-date: html5lib in ./.local/lib/python2.7/site-packages (from xhtml2pdf)

Am I missing something? any suggestion?

Thank you

**Comment by ajinabraham** [comment]
Do not upgrade. Newer version of html5lib has a bug

try:
```
pip install xhtml2pdf==0.0.6
pip install html5lib==1.0b8
```
