### ISSUE TITLE
[Suggestion] Add one summary box for postive findings 

### ISSUE THREAD

**Issue by bugwrangler** [ajinabraham/Mobile-Security-Framework-MobSF#22]
![example](https://cloud.githubusercontent.com/assets/6933052/7239138/235f4824-e7c5-11e4-85c2-797b5ec10be2.png)

**Comment by ajinabraham** [comment]
I will mark this as an enhancement and work on some high level reporting like this once everything is stabilised.

**Comment by bugwrangler** [comment]
Cool

**Comment by odan77** [comment]
Please , How To Fix it?
![screenshot from 2015-05-14 20 37 15](https://cloud.githubusercontent.com/assets/10478563/7646592/9ace2f52-fa7a-11e4-8bb6-2bfdbe58d6d2.png)

**Comment by odan77** [comment]
already fixed, I had not yet update the java to java 7: D, then I update it:
sudo update-alternatives --config java

**Comment by ajinabraham** [comment]
Positive Findings are now available in code analysis with the tag name "secure"
