### ISSUE TITLE
False Posivitives related to Code Analysis

### ISSUE THREAD

**Issue by ydevis803** [ajinabraham/Mobile-Security-Framework-MobSF#220]
Hi, I was just wondering if it is possible that the tool is giving me a false positive here.

Finding: "Files may contain hardcoded sensitive informations like usernames, passwords, keys etc." in the file MenuBuilder.java

However, when I checked the code and I cannot find anything hardcoded that is sensitive. The only line that I can think about it is "paramBundle.putInt("android:menu:expandedactionview", localMenuItem.getItemId());" but still I dont think it is. 

I have attached the MenuBuilder in case I am wrong. [MenuBuilder.java.txt](https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/files/428188/MenuBuilder.java.txt)

Also I was wondering if it is possible that for next version, we could see which line of the code the tool is doing reference. So we know exactly where the issue is.

Thank you.

**Comment by ajinabraham** [comment]
The false positive is due to this line
` private static final String ACTION_VIEW_STATES_KEY = "android:menu:actionviewstates";`

Will track the show line stuff as an enhancement

**Comment by ke88yun** [comment]
How do you suppress the false positive then ?
