### ISSUE TITLE
[ERROR] Reading Code Signing Certificate (C:\Mobile-Security-Framework-MobSF-0.9.2\StaticAnalyzer\views.py, LINE 996 "dat=escape(subprocess.check_output(args)).replace('\n', '</br>')"): 'utf8' codec can't decode byte 0xe3 in position 76

### ISSUE THREAD

**Issue by MLillow** [ajinabraham/Mobile-Security-Framework-MobSF#222]
The entire log:

[ERROR] Reading Code Signing Certificate (C:\Mobile-Security-Framework-MobSF-0.9.2\StaticAnalyzer\views.py, LINE 996 "dat=escape(subprocess.check_output(args)).replace('\n', '</br>')"): 'utf8' codec can't decode byte 0xe3 in position 76: invalid continuation byte. You passed in '[\n[\n  Version: V3\n  Subject: CN=Thiago Catoto Dias, OU=R&D, O=luizalabs, L=S\xe3o Paulo, ST=SP, C=55\n  Signature Algorithm: SHA1withRSA, OID = 1.2.840.113549.1.1.5\n\n  Key:  \n  Validity: [From:
Tue Jan 28 01:40:01 BRST 2014,\n               To: Mon Jan 23 01:40:01 BRST 2034]\n  Issuer: CN=Thiago Catoto Dias, OU=R&D, O=luizalabs, L=S\xe3o Paulo, ST=SP,
C=55\n  SerialNumber: [    52e72691]\n\n]\n  Algorithm: [SHA1withRSA]\n  Signature:\n0000: 5A 65 20 2F 00 F3 55 D1   35 21 50 4B AC EF 2F 1E  Ze /..U.5!PK../.\r\n0010: 95 93 A7 AD 2B A7 35 AC   F7 90 21 6F BB 81 88 2F  ....+.5...!o.../\r\n0020: 46 22 4D 66 C0 6E 7A 6A   56 4D 5A 85 C0 DC FD A1  F"Mf.nzjVMZ.....\r\n0030: CD D9 3C 57 EC 1A 46 43   39 E4 00 F9 64 73 FF 35  ..<W..FC9...ds.5\r\n0040: 39 06 73 B0 E3 0F 93 95   75 B1 58 1E F6 F8 66 F5  9.s.....u.X...f.\r\n0050: 38 BA 39 B5 D6 EA 65 C7   EB BA F1 59 98 34 B2 F9  8.9...e....Y.4..\r\n0060: 92 8F FD F8 E1 F4 A9 D0   9A 35 82 50 64 3A 5C 1B  .........5.Pd:\\.\r\n0070: 3B B4 E5
CB 21 A5 8C 1D   A7 31 91 E8 58 E1 C3 2B  ;...!....1..X..+\r\n\n]\r\n' (<type 'str'>)

Looks like an issue with caracters like ã and ç (used in BR language).

**Comment by ajinabraham** [comment]
Unicode issue

**Comment by ajinabraham** [comment]
Another Bug

```
[2016-09-12 12:32:42]

[ERROR] iOS Binary Analysis (/Users/dave/MobSF/StaticAnalyzer/views/ios.py, LINE 527 "strings=escape(strings.replace(BIN_DIR + "/",""))"): 'ascii' codec can't decode byte 0xb4 in position 31653: ordinal not in range(128)

[2016-09-12 12:32:42]

[ERROR] Static Analyzer iOS (/Users/dave/MobSF/StaticAnalyzer/views/ios.py, LINE 86 "INFO_PLIST,BIN_NAME,ID,VER,SDK,PLTFM,MIN,LIBS,BIN_ANAL,STRINGS=BinaryAnalysis(BIN_DIR,TOOLS_DIR,APP_DIR)"): 'NoneType' object is not iterable
```

**Comment by ajinabraham** [comment]
Tracking Separately.
