### ISSUE TITLE
Error when uploading source code 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by yehgdotnet** [ajinabraham/Mobile-Security-Framework-MobSF#223]
I received the following error from browser.

> Don't Play Around. An Error just popped in!
> 'NoneType' object is not iterable
> 
> Inappropriate argument type.

In command console, the error showed like 

> [INFO] iOS Static Analysis Started
> [INFO] iOS Source Code Analysis Started
> [INFO] ZIP Already Extracted
> [INFO] Generating Hashes
> [INFO] Get Files, BIN Plist -> XML, and Normalize
> [INFO] Starting iOS Source Code and PLIST Analysis
> 
> [2016-09-04 04:56:27]
> [ERROR] iOS Source Code Analysis (/Users/yehg/MobSF/StaticAnalyzer/views/ios.py, LINE 558 "with io.open(InfoP, mode='r',encoding="utf8",errors="ignore") as f:"): [Errno 2] No such file or directory: ''
> 
> [2016-09-04 04:56:27]
> [ERROR] Static Analyzer iOS (/Users/yehg/MobSF/StaticAnalyzer/views/ios.py, LINE 156 "HTML,CODEANAL,URLnFile,DOMAINS,EmailnFile,INFO_PLIST,BIN_NAME,ID,VER,SDK,PLTFM,MIN=iOS_Source_Analysis(APP_DIR,MD5)"): 'NoneType' object is not iterable
> [04/Sep/2016 04:56:27] "GET /StaticAnalyzer_iOS/?name=Archive.zip&type=ios&checksum=f0734925b763b055c0b90bcbb07c8777 HTTP/1.1" 200 4671
>

**Comment by yehgdotnet** [comment]
Proposed fix:

```

        if os.path.isfile(InfoP) == True:
            with io.open(InfoP, mode='r',encoding="utf8",errors="ignore") as f:
                XML=f.read()

        if XML!="":
            p = plistlib.readPlistFromString(XML)
            BIN_NAME = p["CFBundleDisplayName"]
            BIN = p["CFBundleExecutable"]
            ID = p["CFBundleIdentifier"]
            VER = p["CFBundleVersion"]

        SDK = ''  # p["DTSDKName"]
        PLTFM = ''  # p["DTPlatformVersion"]
        MIN = ''  # p["MinimumOSVersion"]
```

**Comment by ajinabraham** [comment]
Fixed on https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/commit/edc35e087fe1e6d00cda7dc497143b93c8e3205e

**Comment by yehgdotnet** [comment]
Awesome!
