### ISSUE TITLE
APK upload 'NoneType' object is not iterable error

### ISSUE THREAD

**Issue by ottucsakj** [ajinabraham/Mobile-Security-Framework-MobSF#226]
I uploaded an APK for static analysis and I received the following error:
_Don't Play Around. An Error just popped in!
'NoneType' object is not iterable
Inappropriate argument type._

Platform is Windows 8.1 x86.

Error log:

```
[INFO] Performing Static Analysis of Android APK
[13/Sep/2016 14:52:35] "POST /Upload/ HTTP/1.1" 200 158
[INFO] Starting Analysis on : join me_v3.2.3.3094_apkpure.com.apk
[INFO] Generating Hashes
[INFO] Unzipping
[INFO] Getting Hardcoded Certificates/Keystores
[INFO] APK Extracted
[INFO] Getting Manifest from Binary
[INFO] AXML -> XML

[2016-09-13 14:52:40]
[ERROR] Reading Manifest file (C:\mobsf\StaticAnalyzer\views\android.py, LINE 72
0 "dat=subprocess.check_output(args)"): [Error 2] The system cannot find the fil
e specified

[2016-09-13 14:52:40]
[ERROR] Parsing Manifest file (C:\mobsf\StaticAnalyzer\views\android.py, LINE 73
7 "dat=ReadManifest(APP_DIR,TOOLS_DIR,TYP,BIN).replace("\n","")"): 'NoneType' ob
ject has no attribute 'replace'
[INFO] Extracting Manifest Data

[2016-09-13 14:52:40]
[ERROR] Extracting Manifest Data (C:\mobsf\StaticAnalyzer\views\android.py, LINE
 996 "permissions = mfxml.getElementsByTagName("uses-permission")"): 'NoneType'
object has no attribute 'getElementsByTagName'

[2016-09-13 14:52:40]
[ERROR] Static Analyzer (C:\mobsf\StaticAnalyzer\views\android.py, LINE 279 "SER
VICES,ACTIVITIES,RECEIVERS,PROVIDERS,LIBRARIES,PERM,PACKAGENAME,MAINACTIVITY,MIN
_SDK,MAX_SDK,TARGET_SDK,ANDROVER,ANDROVERNAME=ManifestData(PARSEDXML,APP_DIR)"):
 'NoneType' object is not iterable
[13/Sep/2016 14:52:40] "GET /StaticAnalyzer/?name=join%20me_v3.2.3.3094_apkpure.
com.apk&type=apk&checksum=d259e61acf10cbf5a29c2da8eaab3219 HTTP/1.1" 200 4671
```

**Comment by ajinabraham** [comment]
Can you share the APK? It seems to have some trouble in reading android manifest

**Comment by nullPoint3r** [comment]
I have the same trouble, i tried many APKs , the same error like this

**Comment by ajinabraham** [comment]
Can you please try the latest master. Also If you see this again, please share an apk that caused the same.

**Comment by nullPoint3r** [comment]
It works using latest master

**Comment by danielmiessler** [comment]
Just tried with Master branch, same issue. Unable to share the .apk. : (

**Comment by psattarzadeh** [comment]
hi 
i get the 
"Don't Play Around. An Error just popped in!
'NoneType' object has no attribute '__getitem__'
Inappropriate argument type."
error for every APK file that im trying for StaticAnalyzer. and every time i get this error.
i went through all the topics related to this problem and I've done all the thing that every one suggested.
i deleted db.sqlite3 and updated with 
-python manage.py makemigrations
-python manage.py migrate
but nothing changed. 

i didnt find the final solution for this problem. could you please help me how to fix this issue?

**Comment by ajinabraham** [comment]
Delete everything in `StaticAnalyzer/migrations/` as well. Share console/terminal log if issue persists

**Comment by psattarzadeh** [comment]
i checked the log. the problem was my java version. mobsf need version 7 but mine was 8. 
thank you for your help and for creating this amazing tool.
