### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by achinverma** [ajinabraham/Mobile-Security-Framework-MobSF#228]
```
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    ----------------------------------------
Command "c:\users\70015379\appdata\local\programs\python\python35-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\70014756\\AppData\\Local\\Temp\\pip-build-i86fzsfh\\psutil\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\70014756\AppData\Local\Temp\pip-s7_tl5y6-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\70014756\AppData\Local\Temp\pip-build-i86fzsfh\psutil\

```
please anyone guide me?

**Comment by DominikSchlecht** [comment]
Dear @achinverma ,
have you already installed Microsoft Visual C++ Build Tools? If not, the instructions are on the screen:

> Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

Also, **MobSF needs Python 2.7**

It seems like you are using Python 3:
`Command "c:\users\70015379\appdata\local\programs\python\\**python35-32**\python.exe`

Greetings,
Dominik

PS.: Overall these are no project, but pip install error. Google will help you fixing most of these problems (even thought pip under windows can be a horror sometimes).

PPS.: Try to leave out specific information from your pc, like for example your username.

**Comment by achinverma** [comment]
@DominikSchlecht  yes i have Microsoft Visual C++ Build Tools 14.0 installed on my pc

**Comment by DominikSchlecht** [comment]
@achinverma Did you try the installation with Python 2.7?

**Comment by achinverma** [comment]
@DominikSchlecht  , but i have downgrade to Python  3.4 , but still not working

**Comment by ajinabraham** [comment]
@achinverma MobSF is based on Python 2.7

In windows, for getting the static analyzer to work,

Read the requirements: https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/wiki/1.-Documentation#requirements

And 

Instructions: https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/wiki/1.-Documentation#configuring-static-analyzer

Some python modules like libxml doesn't install, if you try from pip. Get the appropriate binary from: http://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by Ammad317** [comment]
i have install both python 2.7 or 3.7 but still i get the same error
[ERRRO] python3 is not installed
Please any ony guide me.

**Comment by sathiyac2** [comment]
@Ammad317  
Copy and past your setup.bat file in folder python37
