### ISSUE TITLE
How to get webSqlDB details from Dynamic Anlayzer

### ISSUE THREAD

**Issue by madhuCNKony** [ajinabraham/Mobile-Security-Framework-MobSF#229]
Hi Ajin Abraham

Is there a way I can get "webSqlDB" details from APK?

**Comment by ajinabraham** [comment]
Are you referring to the Web SQL API available to HTML5?
Dynamic Analyzer hooks and analyses native android methods only. Web SQL is a JavaScript API that works with Hybrid apps that are built on WebView using Phonegap, cordova etc. 
We don't analyse JavaScript at the moment.

**Comment by madhuCNKony** [comment]
ok I got it... Thank you
