### ISSUE TITLE
PDF display Error

### ISSUE THREAD

**Issue by vigkri** [ajinabraham/Mobile-Security-Framework-MobSF#230]
Thanks for this incredible tool. Everything works great, but when I try downloading the pdf report it redirects me to the error page.
In the cmd, the error shown is as follows:
**views.py, LINE 148 "pdf = pisa.pisaDocument(StringIO( "{0}".format(html.encode('utf-8'))), result, encoding='utf-8')"): global name 'pisa' is not defined**

**Comment by ajinabraham** [comment]
try
```
pip install xhtml2pdf==0.0.6
pip install html5lib==1.0b8
```
If you are able to install both of the modules then that will solve this error.

**Comment by vigkri** [comment]
Thank you. Worked great. But whenever I do a dynamic analysis with Mobsf,
It closes the application automatically in the Android VM giving out a
error message "*Unfortunately, the application has stopped working*".
Kindly help.

**Comment by ajinabraham** [comment]
Not all apps work in VM. You might need a real device or a different VM: https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/wiki/1.-Documentation#configuring-rooted-android-devicecustom-vm-with-mobsf
