### ISSUE TITLE
MobSF automation?

### ISSUE THREAD

**Issue by javixeneize** [ajinabraham/Mobile-Security-Framework-MobSF#233]
Hi

Can MobSF static analysis be automated? Looks like you need to run the python to start the server, and upload the file manually

Is there any way to pass to the python script a parameter with the file you want to analyse?

Thanks

**Comment by ajinabraham** [comment]
Look into: https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/wiki/4.-Mass-Static-Analysis
