### ISSUE TITLE
pdf report not being generated

### ISSUE THREAD

**Issue by javixeneize** [ajinabraham/Mobile-Security-Framework-MobSF#234]
Hi

When i try to generate a report in PDF, nothing seems to happen. I can see in the console this

[INFO] Fetching data from DB for PDF Report Generation (IOS IPA)

But nothing else happens...

Is that a known issue?

**Comment by ajinabraham** [comment]
Not sure what's happening. Can you paste your `log/ MobSF.log` here. 
If it's already populated, delete the file and try the PDF generation again and share the error. 
Also if the results are large, PDF generation can take some time.

**Comment by javixeneize** [comment]
Hi

It only happens with ipa analysis. apk works fine

Nothing is written in the log

**Comment by ajinabraham** [comment]
Can you share an that causes the trouble IPA.

**Comment by javixeneize** [comment]
Hi

Update on this... Report generated, but it took 10 minutes! It is an .ipa that is only 18mb

**Comment by ajinabraham** [comment]
So these are the possible reasons
* System might not have enough RAM
* Even though the IPA is small, the anaysis result might be huge.

**Comment by javixeneize** [comment]
Ok... if nobody else reported that, must be a local problem. Hapy to close
it

**Comment by luisxiaomai** [comment]
@ajinabraham @javixeneize , I also met this pdf generating issue for ipa.

**Comment by ajinabraham** [comment]
Any error logs?

**Comment by luisxiaomai** [comment]
No error log displays in server side, just like ` [INFO] Fetching data from DB for PDF Report Generation (IOS IPA)` and always pending in UI.

**Comment by ajinabraham** [comment]
Can you share an IPA that caused this problem.

**Comment by luisxiaomai** [comment]
@ajinabraham , I can see results in web page but can't download it to pdf. It should not be related to pdf. I will take a look tomorrow, anywhere thanks for your quick response.

**Comment by jackwuzz** [comment]
Hi
I have the same problem - “It only happens with ipa analysis. apk works fine;also log/ MobSF.log show nothing wrong”
finally ，I use chrome‘ print function transform html to pdf ,and it work fine ,also it's colorful

**Comment by ajinabraham** [comment]
It's working fine at my end. Can you share the IPA @jackwuzz  that caused the trouble.

**Comment by javixeneize** [comment]
I experienced the same problem some time ago. The report is generated but
takes long lomg time (it could take 10 mins)

To address the issue properly, wait for that time and check if the report
is generated

Let us know when you have the results

Thanks

**Comment by jackwuzz** [comment]
The ipa file I have email to you ,
I hope can help you to test and solve the problem. @ajinabraham

**Comment by ajinabraham** [comment]
@jackwuzz Please check your email
