### ISSUE TITLE
Non-ascii filename in Python2.7

### ISSUE THREAD

**Issue by TiberiumPY** [ajinabraham/Mobile-Security-Framework-MobSF#236]
If user trying to upload .apk with non-ascii filename, exception being thrown:
[ERROR] Uploading File: (/home/ubuntu/Mobile-Security-Framework-MobSF/MobSF/views.py, LINE 53 "print "[INFO] MIME Type: " + file_type + " FILE: " + str(request.FILES['file'].name)"): 'ascii' codec can't encode characters in position 0-7: ordinal not in range(128)

**Comment by ajinabraham** [comment]
Tracking Separately.

**Comment by ajinabraham** [comment]
Fixed in latest commit to master
