### ISSUE TITLE
Proxy for Custom Android VM 

### ISSUE THREAD

**Issue by vigkri** [ajinabraham/Mobile-Security-Framework-MobSF#241]
Hi. Instead of using the mobsf.ova file, I've downloaded a custom Virtualbox image from the internet. My problem is that the Wifi option is always turned off and I am unable to configure the proxy for the VM image.

**Comment by ajinabraham** [comment]
This is not a MobSF issue. Please read https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/blob/master/CONTRIBUTING.md

You might need some IP to communicate with the VM
