### ISSUE TITLE
'ascii' codec can't decode byte 0xe3 in position 0: ordinal not in range(128) 

### ISSUE THREAD

**Issue by pablovidelayanez** [ajinabraham/Mobile-Security-Framework-MobSF#243]
Hi, i have the project in a windows machine, with Python 2.7.12
In others apk i don't have problem , but with wich one i have this problem:

[ERROR] Unzipping Error (E:\Mobile-Security-Framework-MobSF\StaticAnalyzer\views\shared_func.py, LINE 59 "z.extractall(EXT_PATH)"): 'ascii' codec can't decode byte 0xe3 in position 0: ordinal not in range(128)

And the reports all fails. I tested too in Kali linux and the problem are the same.

Thanks you in advance.

![image](https://cloud.githubusercontent.com/assets/9121003/19335583/cfca42de-90da-11e6-9910-a1747114f63e.png)

**Comment by ajinabraham** [comment]
This is a known unicode issue.

**Comment by ajinabraham** [comment]
Tracking Separately.

**Comment by ajinabraham** [comment]
Can you share this APK? I need the APK to investigate more on this.

**Comment by TiberiumPY** [comment]
@ajinabraham why you are still using python 2? Python 3 is very good

**Comment by ajinabraham** [comment]
@TiberiumPY I know that Python 3 is better. But MobSF was initially written in Python 2. We will gradually move to Python 3.

**Comment by pablovidelayanez** [comment]
@ajinabraham Sorry i can't share the apk (this don't belong to me), but i am sure the apk it's obfuscated with proguard, and that it's the problem. In other machine can decompile some source (with androlab and your app) but in kali and in windows i can't do that.

**Comment by ajinabraham** [comment]
I cannot test it unless I can reproduce the issue. If you can point me to a public location of the APK in playstore or something, I can get the APK.

**Comment by ajinabraham** [comment]
This is fixed in latest commit to master. Can you check and confirm
