### ISSUE TITLE
Feature Request: Can we export the details in Excel Format.

### ISSUE THREAD

**Issue by avinashkmr632** [ajinabraham/Mobile-Security-Framework-MobSF#248]
As of now we are able to generate a PDF report for the scanned application. It would we more scalable if we are able to download an Excel report for the same.

Thanks in advance.

**Comment by ajinabraham** [comment]
MobSF gives nested data. It makes more sense to give a JSON output in future. But what is the advantage you see from Excel?

**Comment by DominikSchlecht** [comment]
I also see some benefits, mostly for easy tracking in companies (you just copy the findings over to your internal tracking excel for example).

That would fit great into my master thesis, so if you don't mind I would start with implementing json first and excel in a second step over the upcoming weeks.

Greeting,
Dominik

**Comment by ajinabraham** [comment]
Go Ahead. I really like the JSON way since lot of people were asking if they can get the result in JSON via some REST API. They need to integrate MobSF Static Analysis result with other applications. But I don't really see any value with excel as it's pretty much similar to PDF. May be I am missing something here.

**Comment by DominikSchlecht** [comment]
PDF can't be edited afterwards ;)

OK, thanks.

Greetings,
Dominik

**Comment by avinashkmr632** [comment]
Even excel sheet can be used as a database. Also excel uses less memory. If
we have an excel report for the scan then we can play further like
compararing two app, there vulnerabilities, etc. It can be great having an
excel report for each app.

**Comment by ajinabraham** [comment]
Okey sounds fine. Will track this. I have a related enhancement opened here: https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/issues/249

**Comment by avinashkmr632** [comment]
How are we supposed to download the report as an excel format?

**Comment by ajinabraham** [comment]
This is an enhancement, being tracked at the moment and is not available with MobSF currently.

**Comment by asjrosabal** [comment]
I would like export the results of MobSF in XML, It is possible? How can I export to Xml File the results? Thanks

**Comment by skerns00** [comment]
I think I developed a way to extract the data to JSON file. I did this when the user extracts the PDF file. The JSON file is created in the same directory as install directory of MobSF, though the directory could be changed. I changed the file shared_func.py, so when it generates the PDF it also writes the JSON file.

**Comment by aress31** [comment]
Why is this issue closed?

**Comment by ajinabraham** [comment]
@aress31 Tracked Separately https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/264

**Comment by lynnseyMitel** [comment]
@ajinabraham I'm so sorry if this is covered somewhere else but are we able to export results as JSON now?

**Comment by ajinabraham** [comment]
Yes there is JSON report REST API.

**Comment by lynnseyMitel** [comment]
@ajinabraham Thank you so much!
