### ISSUE TITLE
API Fuzzer response = http_client.fetch(url)"): HTTP 404

### ISSUE THREAD

**Issue by printer101** [ajinabraham/Mobile-Security-Framework-MobSF#250]
Hi thanks for great tool when i get apifuzzer receive this error

[INFO] Performing Information Gathering

[2016-10-22 06:03:06]
[ERROR] HTTP Connection Error (C:\MobSF\APITester\views.py, LINE 946 "response = http_client.fetch(url)"): HTTP 404: Not Found
[22/Oct/2016 06:03:06]"POST /StartScan/ HTTP/1.1" 200 5370

thanks in adavanced

**Comment by ajinabraham** [comment]
This is normal. It's a page not found error

**Comment by printer101** [comment]
hi many apk get "app has stopped"   what you think is cert issue or other ??

thanks
