### ISSUE TITLE
MobSF Unfortunately xxxxx is stopped 

### ISSUE THREAD

**Issue by printer101** [ajinabraham/Mobile-Security-Framework-MobSF#251]
many apk get this error "Unfortunately xxxxx is stopped "  how solve this issue?

![error](https://cloud.githubusercontent.com/assets/22992826/19617840/fa1744e2-9832-11e6-93db-7d459a21ad8f.png)

**Comment by ajinabraham** [comment]
This happens due to many reasons. The best thing to try is to use a real device with mobsf.

**Comment by kindsjay** [comment]
me too,How do you do that?
