### ISSUE TITLE
Connecting to VM - Dynamic Analysis

### ISSUE THREAD

**Issue by ydevis803** [ajinabraham/Mobile-Security-Framework-MobSF#252]
Hi,

I have tried several different ways to connect to the VM but I cant. This is the configuration:
I had to change the Adapter type, because with Paravirtualized Network (virtio-net) doesnt work at all.
![image](https://cloud.githubusercontent.com/assets/20956774/19628217/8e3b2a4e-9950-11e6-92c6-bd9ac3b34e5a.png)

Doing ipconfig from the host:
![image](https://cloud.githubusercontent.com/assets/20956774/19628219/b28965be-9950-11e6-82a1-25d9e9a44638.png)

I am using a wireless connection btw.

However when I start the VM, looks like this:

<img width="277" alt="ip_start_vm" src="https://cloud.githubusercontent.com/assets/20956774/19628176/c02550d0-994f-11e6-90c4-601988007137.PNG">

I get connection in the VM (that is how I know that the IP is 10.0.3.15). However, I cannot connect from MobSF
![image](https://cloud.githubusercontent.com/assets/20956774/19628293/8186be56-9952-11e6-9eb6-89c05b6f0cf0.png)

I have configured the settings.py file following the steps:
![image](https://cloud.githubusercontent.com/assets/20956774/19628304/981676de-9952-11e6-96af-3fc94fef3f17.png)

Any ideas?

Thanks

**Comment by ajinabraham** [comment]
If you don't see IP while VM is booting up, it will give you problems. You need to fix this first. Something is wrong with your network config. Also make sure that you are not running other Android VM or devices connected to the host via ADB. I see trouble when a Genymotion VM or Android Studio running along with MobSF VM. This is not a MobSF bug, you have some network/virtual box issues. Hence closing.

**Comment by din123456789** [comment]
Hai 
when i Run Dynamic analyser an error showing unable to connect 192.168.56.101 in console..

**Comment by din123456789** [comment]
how to solve this?
