### ISSUE TITLE
No module named lxml

### ISSUE THREAD

**Issue by sunipa21** [ajinabraham/Mobile-Security-Framework-MobSF#253]
Hi,

I am not able to launch MobSF, it is throwing below mentioned exception:
"No module named lxml"
Python Version:	2.7.9
Python Path:	
['C:\\MobSF',
 'C:\\Python27\\lib\\site-packages\\nosqlmap-0.7-py2.7.egg',
 'C:\\Python27\\lib\\site-packages\\requests-2.5.0-py2.7.egg',
 'C:\\Python27\\lib\\site-packages\\pymongo-2.7.2-py2.7-win32.egg',
 'C:\\Python27\\lib\\site-packages\\pbkdf2-1.3-py2.7.egg',
 'C:\\Python27\\lib\\site-packages\\ipcalc-1.1.3-py2.7.egg',
 'C:\\Python27\\lib\\site-packages\\httplib2-0.9-py2.7.egg',
 'C:\\Python27\\lib\\site-packages\\couchdb-1.0-py2.7.egg',
 'C:\\Windows\\system32\\python27.zip',
 'C:\\Python27\\DLLs',
 'C:\\Python27\\lib',
 'C:\\Python27\\lib\\plat-win',
 'C:\\Python27\\lib\\lib-tk',
 'C:\\Python27',
 'C:\\Python27\\lib\\site-packages']

I tried installing lxml using below mentioned commad but it ended-up with error:
 -> build\lib.win32-2.7\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    running build_ext
    building 'lxml.etree' extension
    creating build\temp.win32-2.7
    creating build\temp.win32-2.7\Release
    creating build\temp.win32-2.7\Release\src
    creating build\temp.win32-2.7\Release\src\lxml
    C:\Users\\AppData\Local\Programs\Common\Microsoft\Visual C++ for
 Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Isrc\lxml\includ
es -Ic:\python27\include -Ic:\python27\PC /Tcsrc\lxml\lxml.etree.c /Fobuild\temp
.win32-2.7\Release\src\lxml\lxml.etree.obj -w
    cl : Command line warning D9025 : overriding '/W3' with '/w'
    lxml.etree.c
    src\lxml\includes\etree_defs.h(14) : fatal error C1083: Cannot open include
file: 'libxml/xmlversion.h': No such file or directory
    Compile failed: command 'C:\\Users\\AppData\\Local\\Programs\\
Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit
 status 2
    C:\Users\\AppData\Local\Programs\Common\Microsoft\Visual C++ for
 Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I/usr/include/li
bxml2 /Tcc:\users\sunil~1.pan\appdata\local\temp\xmlXPathInitknmy1m.c /Fousers\s
unil~1.pan\appdata\local\temp\xmlXPathInitknmy1m.obj
    xmlXPathInitknmy1m.c
    c:\users\sunil~1.pan\appdata\local\temp\xmlXPathInitknmy1m.c(1) : fatal erro
r C1083: Cannot open include file: 'libxml/xpath.h': No such file or directory
    ****************************************************************************
*****
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 insta
lled?
    ****************************************************************************
*****
    error: command 'C:\\Users\\AppData\\Local\\Programs\\Common\\M
icrosoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\
\users\\sunil~1.pan\\appdata\\local\\temp\\pip-build-_op9zx\\lxml\\setup.py';exe
c(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n')
, __file__, 'exec'))" install --record c:\users\sunil~1.pan\appdata\local\temp\p
ip-zhdkgs-record\install-record.txt --single-version-externally-managed --compil
e" failed with error code 1 in c:\users\sunil~1.pan\appdata\local\temp\pip-build
-_op9zx\lxml\

Please help me in fixing this issue.

Best Regards,
Sunil

**Comment by TiberiumPY** [comment]
use latest python

**Comment by sunipa21** [comment]
Thanks for reply,

In the documentation, it is mentioned to use python 2.7, and if I use latest python which is 3.5.2, in that case, the framework may not be compatible.
At the same time I am getting error as:
"[ERROR] Oracle Java (JDK >=1.7) is not found! (C:\MobSF\MobSF\utils.py, LINE 134
 "for dirname in os.listdir(WIN_JAVA_BASE):"): [Error 123] The filename, directo
ry name, or volume label syntax is incorrect: 'C:/Program Files/Java/C:/Program
Files (x86)/Java/*.*'"

Not sure why I am getting this error, my Env path value is "C:\Program Files\Java\jdk1.7.0;C:\Program Files\Java\jdk1.7.0\bin"

Please suggest

Best Regards,
Sunil

**Comment by ajinabraham** [comment]
This is not a MobSF bug hence closing.

**Comment by TiberiumPY** [comment]
@sunipa21 python 2.7 and 3.5 are not compatible while using them in big apps

**Comment by DominikSchlecht** [comment]
Hey, simply install lxml:
https://pypi.python.org/pypi/lxml

**Comment by ajinabraham** [comment]
@sunipa21 This is an issue tracker for MobSF related bugs/ feature requests. Please use stackoverflow for issues that are not related to MobSF.

**Comment by yazananwar** [comment]
hi 

you can use this command 

pip install lxml==3.4.2
