### ISSUE TITLE
Error xhtml2pdf is not installed. Cannot generate PDF reports

### ISSUE THREAD

**Issue by ringonotts** [ajinabraham/Mobile-Security-Framework-MobSF#255]
Sorry about this - i highly suspect its user error..

I am unable to generate pdf reports as told when i run the server.

I read a previous issue and re-ran the command the install the dependencies. However, that failed too.

Logs:

> C:\Tools\MobSF>c:\Python27\python.exe manage.py runserver
> 
> 
> Mobile Security Framework v0.9.2 Beta
> 
>   __  __       _    ____  _____          ___   ___   ____
>  |  \/  | ___ | |__/ ___||  ___| __   __/ _ \ / _ \ |___ \
>  | |\/| |/ _ \| '_ \___ \| |_    \ \ / / | | | (_) |  __) |
>  | |  | | (_) | |_) |__) |  _|    \ V /| |_| |\__, | / __/
>  |_|  |_|\___/|_.__/____/|_|       \_/  \___(_) /_(_)_____|
> 
> 
> 
> 
> 
> [INFO] Finding JDK Location in Windows....
> 
> [INFO] Oracle JDK Identified. Looking for JDK 1.7 or above
> 
> [INFO] Oracle Java (JDK >= 1.7) is installed!
> 
> 
> Mobile Security Framework v0.9.2 Beta
> 
>   __  __       _    ____  _____          ___   ___   ____
>  |  \/  | ___ | |__/ ___||  ___| __   __/ _ \ / _ \ |___ \
>  | |\/| |/ _ \| '_ \___ \| |_    \ \ / / | | | (_) |  __) |
>  | |  | | (_) | |_) |__) |  _|    \ V /| |_| |\__, | / __/
>  |_|  |_|\___/|_.__/____/|_|       \_/  \___(_) /_(_)_____|
> 
> 
> 
> 
> 
> [INFO] Finding JDK Location in Windows....
> 
> [INFO] Oracle JDK Identified. Looking for JDK 1.7 or above
> 
> [INFO] Oracle Java (JDK >= 1.7) is installed!
> Performing system checks...
> 
> 
> [2016-10-28 15:41:47]
> [ERROR] xhtml2pdf is not installed. Cannot generate PDF reports (C:\Tools\MobSF\
> StaticAnalyzer\views\shared_func.py, LINE 27 "import xhtml2pdf.pisa as pisa"): N
> o module named xhtml2pdf.pisa
> 
> [2016-10-28 15:41:47]
> [ERROR] xhtml2pdf is not installed. Cannot generate PDF reports (C:\Tools\MobSF\
> StaticAnalyzer\views\ios.py, LINE 24 "import xhtml2pdf.pisa as pisa"): No module
>  named xhtml2pdf.pisa
> System check identified no issues (0 silenced).
> October 28, 2016 - 15:41:47
> Django version 1.10b1, using settings 'MobSF.settings'
> Starting development server at http://127.0.0.1:8000/
> Quit the server with CTRL-BREAK.
> 

And for the dependencies error:

> C:\Tools\MobSF>pip install -r requirements.txt
> Requirement already satisfied (use --upgrade to upgrade): Django==1.10.b1 in c:\
> users\xbv784\appdata\local\programs\python\python35-32\lib\site-packages (from -
> r requirements.txt (line 1))
> Requirement already satisfied (use --upgrade to upgrade): pyOpenSSL==0.15 in c:\
> users\xbv784\appdata\local\programs\python\python35-32\lib\site-packages (from -
> r requirements.txt (line 2))
> Requirement already satisfied (use --upgrade to upgrade): tornado==4.1 in c:\use
> rs\xbv784\appdata\local\programs\python\python35-32\lib\site-packages (from -r r
> equirements.txt (line 3))
> Requirement already satisfied (use --upgrade to upgrade): xhtml2pdf==0.0.6 in c:
> \users\xbv784\appdata\local\programs\python\python35-32\lib\site-packages (from
> -r requirements.txt (line 4))
> Requirement already satisfied (use --upgrade to upgrade): html5lib==1.0b8 in c:\
> users\xbv784\appdata\local\programs\python\python35-32\lib\site-packages (from -
> r requirements.txt (line 5))
> Requirement already satisfied (use --upgrade to upgrade): psutil==4.2.0 in c:\us
> ers\xbv784\appdata\local\programs\python\python35-32\lib\site-packages (from -r
> requirements.txt (line 6))
> Collecting lxml (from -r requirements.txt (line 7))
>   Using cached lxml-3.6.4.tar.gz
> Requirement already satisfied (use --upgrade to upgrade): cryptography>=0.7 in c
> :\users\xbv784\appdata\local\programs\python\python35-32\lib\site-packages (from
>  pyOpenSSL==0.15->-r requirements.txt (line 2))
> Requirement already satisfied (use --upgrade to upgrade): six>=1.5.2 in c:\users
> \xbv784\appdata\local\programs\python\python35-32\lib\site-packages (from pyOpen
> SSL==0.15->-r requirements.txt (line 2))
> Requirement already satisfied (use --upgrade to upgrade): certifi in c:\users\xb
> v784\appdata\local\programs\python\python35-32\lib\site-packages (from tornado==
> 4.1->-r requirements.txt (line 3))
> Requirement already satisfied (use --upgrade to upgrade): pyPdf2 in c:\users\xbv
> 784\appdata\local\programs\python\python35-32\lib\site-packages (from xhtml2pdf=
> =0.0.6->-r requirements.txt (line 4))
> Requirement already satisfied (use --upgrade to upgrade): Pillow in c:\users\xbv
> 784\appdata\local\programs\python\python35-32\lib\site-packages (from xhtml2pdf=
> =0.0.6->-r requirements.txt (line 4))
> Requirement already satisfied (use --upgrade to upgrade): reportlab>=2.2 in c:\u
> sers\xbv784\appdata\local\programs\python\python35-32\lib\site-packages (from xh
> tml2pdf==0.0.6->-r requirements.txt (line 4))
> Requirement already satisfied (use --upgrade to upgrade): idna>=2.0 in c:\users\
> xbv784\appdata\local\programs\python\python35-32\lib\site-packages (from cryptog
> raphy>=0.7->pyOpenSSL==0.15->-r requirements.txt (line 2))
> Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.8 in c:\us
> ers\xbv784\appdata\local\programs\python\python35-32\lib\site-packages (from cry
> ptography>=0.7->pyOpenSSL==0.15->-r requirements.txt (line 2))
> Requirement already satisfied (use --upgrade to upgrade): cffi>=1.4.1 in c:\user
> s\xbv784\appdata\local\programs\python\python35-32\lib\site-packages (from crypt
> ography>=0.7->pyOpenSSL==0.15->-r requirements.txt (line 2))
> Requirement already satisfied (use --upgrade to upgrade): setuptools>=11.3 in c:
> \users\xbv784\appdata\local\programs\python\python35-32\lib\site-packages (from
> cryptography>=0.7->pyOpenSSL==0.15->-r requirements.txt (line 2))
> Requirement already satisfied (use --upgrade to upgrade): pip>=1.4.1 in c:\users
> \xbv784\appdata\local\programs\python\python35-32\lib\site-packages (from report
> lab>=2.2->xhtml2pdf==0.0.6->-r requirements.txt (line 4))
> Requirement already satisfied (use --upgrade to upgrade): pycparser in c:\users\
> xbv784\appdata\local\programs\python\python35-32\lib\site-packages (from cffi>=1
> .4.1->cryptography>=0.7->pyOpenSSL==0.15->-r requirements.txt (line 2))
> Installing collected packages: lxml
>   Running setup.py install for lxml ... error
>     Complete output from command c:\users\xbv784\appdata\local\programs\python\p
> ython35-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\xb
> v784\\AppData\\Local\\Temp\\pip-build-mgmlzr97\\lxml\\setup.py';exec(compile(get
> attr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, '
> exec'))" install --record C:\Users\xbv784\AppData\Local\Temp\pip-6d18nevd-record
> \install-record.txt --single-version-externally-managed --compile:
>     Building lxml version 3.6.4.
>     Building without Cython.
>     ERROR: b"'xslt-config' is not recognized as an internal or external command,
> \r\noperable program or batch file.\r\n"
>     ** make sure the development packages of libxml2 and libxslt are installed *
> *
> 
>     Using build configuration of libxslt
>     running install
>     running build
>     running build_py
>     creating build
>     creating build\lib.win32-3.5
>     creating build\lib.win32-3.5\lxml
>     copying src\lxml\builder.py -> build\lib.win32-3.5\lxml
>     copying src\lxml\cssselect.py -> build\lib.win32-3.5\lxml
>     copying src\lxml\doctestcompare.py -> build\lib.win32-3.5\lxml
>     copying src\lxml\ElementInclude.py -> build\lib.win32-3.5\lxml
>     copying src\lxml\pyclasslookup.py -> build\lib.win32-3.5\lxml
>     copying src\lxml\sax.py -> build\lib.win32-3.5\lxml
>     copying src\lxml\usedoctest.py -> build\lib.win32-3.5\lxml
>     copying src\lxml\_elementpath.py -> build\lib.win32-3.5\lxml
>     copying src\lxml\__init__.py -> build\lib.win32-3.5\lxml
>     creating build\lib.win32-3.5\lxml\includes
>     copying src\lxml\includes\__init__.py -> build\lib.win32-3.5\lxml\includes
>     creating build\lib.win32-3.5\lxml\html
>     copying src\lxml\html\builder.py -> build\lib.win32-3.5\lxml\html
>     copying src\lxml\html\clean.py -> build\lib.win32-3.5\lxml\html
>     copying src\lxml\html\defs.py -> build\lib.win32-3.5\lxml\html
>     copying src\lxml\html\diff.py -> build\lib.win32-3.5\lxml\html
>     copying src\lxml\html\ElementSoup.py -> build\lib.win32-3.5\lxml\html
>     copying src\lxml\html\formfill.py -> build\lib.win32-3.5\lxml\html
>     copying src\lxml\html\html5parser.py -> build\lib.win32-3.5\lxml\html
>     copying src\lxml\html\soupparser.py -> build\lib.win32-3.5\lxml\html
>     copying src\lxml\html\usedoctest.py -> build\lib.win32-3.5\lxml\html
>     copying src\lxml\html\_diffcommand.py -> build\lib.win32-3.5\lxml\html
>     copying src\lxml\html\_html5builder.py -> build\lib.win32-3.5\lxml\html
>     copying src\lxml\html\_setmixin.py -> build\lib.win32-3.5\lxml\html
>     copying src\lxml\html\__init__.py -> build\lib.win32-3.5\lxml\html
>     creating build\lib.win32-3.5\lxml\isoschematron
>     copying src\lxml\isoschematron\__init__.py -> build\lib.win32-3.5\lxml\isosc
> hematron
>     copying src\lxml\lxml.etree.h -> build\lib.win32-3.5\lxml
>     copying src\lxml\lxml.etree_api.h -> build\lib.win32-3.5\lxml
>     copying src\lxml\includes\c14n.pxd -> build\lib.win32-3.5\lxml\includes
>     copying src\lxml\includes\config.pxd -> build\lib.win32-3.5\lxml\includes
>     copying src\lxml\includes\dtdvalid.pxd -> build\lib.win32-3.5\lxml\includes
>     copying src\lxml\includes\etreepublic.pxd -> build\lib.win32-3.5\lxml\includ
> es
>     copying src\lxml\includes\htmlparser.pxd -> build\lib.win32-3.5\lxml\include
> s
>     copying src\lxml\includes\relaxng.pxd -> build\lib.win32-3.5\lxml\includes
>     copying src\lxml\includes\schematron.pxd -> build\lib.win32-3.5\lxml\include
> s
>     copying src\lxml\includes\tree.pxd -> build\lib.win32-3.5\lxml\includes
>     copying src\lxml\includes\uri.pxd -> build\lib.win32-3.5\lxml\includes
>     copying src\lxml\includes\xinclude.pxd -> build\lib.win32-3.5\lxml\includes
>     copying src\lxml\includes\xmlerror.pxd -> build\lib.win32-3.5\lxml\includes
>     copying src\lxml\includes\xmlparser.pxd -> build\lib.win32-3.5\lxml\includes
> 
>     copying src\lxml\includes\xmlschema.pxd -> build\lib.win32-3.5\lxml\includes
> 
>     copying src\lxml\includes\xpath.pxd -> build\lib.win32-3.5\lxml\includes
>     copying src\lxml\includes\xslt.pxd -> build\lib.win32-3.5\lxml\includes
>     copying src\lxml\includes\etree_defs.h -> build\lib.win32-3.5\lxml\includes
>     copying src\lxml\includes\lxml-version.h -> build\lib.win32-3.5\lxml\include
> s
>     creating build\lib.win32-3.5\lxml\isoschematron\resources
>     creating build\lib.win32-3.5\lxml\isoschematron\resources\rng
>     copying src\lxml\isoschematron\resources\rng\iso-schematron.rng -> build\lib
> .win32-3.5\lxml\isoschematron\resources\rng
>     creating build\lib.win32-3.5\lxml\isoschematron\resources\xsl
>     copying src\lxml\isoschematron\resources\xsl\RNG2Schtrn.xsl -> build\lib.win
> 32-3.5\lxml\isoschematron\resources\xsl
>     copying src\lxml\isoschematron\resources\xsl\XSD2Schtrn.xsl -> build\lib.win
> 32-3.5\lxml\isoschematron\resources\xsl
>     creating build\lib.win32-3.5\lxml\isoschematron\resources\xsl\iso-schematron
> -xslt1
>     copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_abstra
> ct_expand.xsl -> build\lib.win32-3.5\lxml\isoschematron\resources\xsl\iso-schema
> tron-xslt1
>     copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_dsdl_i
> nclude.xsl -> build\lib.win32-3.5\lxml\isoschematron\resources\xsl\iso-schematro
> n-xslt1
>     copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schema
> tron_message.xsl -> build\lib.win32-3.5\lxml\isoschematron\resources\xsl\iso-sch
> ematron-xslt1
>     copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schema
> tron_skeleton_for_xslt1.xsl -> build\lib.win32-3.5\lxml\isoschematron\resources\
> xsl\iso-schematron-xslt1
>     copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_svrl_f
> or_xslt1.xsl -> build\lib.win32-3.5\lxml\isoschematron\resources\xsl\iso-schemat
> ron-xslt1
>     copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\readme.txt
>  -> build\lib.win32-3.5\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
>     running build_ext
>     building 'lxml.etree' extension
>     creating build\temp.win32-3.5
>     creating build\temp.win32-3.5\Release
>     creating build\temp.win32-3.5\Release\src
>     creating build\temp.win32-3.5\Release\src\lxml
>     C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo
>  /Ox /W3 /GL /DNDEBUG /MD -Isrc\lxml\includes -Ic:\users\xbv784\appdata\local\pr
> ograms\python\python35-32\include -Ic:\users\xbv784\appdata\local\programs\pytho
> n\python35-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
> INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\ucrt" "-
> IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Fi
> les (x86)\Windows Kits\10\include\10.0.10586.0\shared" "-IC:\Program Files (x86)
> \Windows Kits\10\include\10.0.10586.0\um" "-IC:\Program Files (x86)\Windows Kits
> \10\include\10.0.10586.0\winrt" /Tcsrc\lxml\lxml.etree.c /Fobuild\temp.win32-3.5
> \Release\src\lxml\lxml.etree.obj -w
>     cl : Command line warning D9025 : overriding '/W3' with '/w'
>     lxml.etree.c
>     src\lxml\includes\etree_defs.h(14): fatal error C1083: Cannot open include f
> ile: 'libxml/xmlversion.h': No such file or directory
>     Compile failed: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14
> .0\\VC\\BIN\\cl.exe' failed with exit status 2
>     creating Users
>     creating Users\xbv784
>     creating Users\xbv784\AppData
>     creating Users\xbv784\AppData\Local
>     creating Users\xbv784\AppData\Local\Temp
>     C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo
>  /Ox /W3 /GL /DNDEBUG /MD -I/usr/include/libxml2 "-IC:\Program Files (x86)\Micro
> soft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\in
> clude\10.0.10586.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\i
> nclude\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\shared
> " "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10586.0\um" "-IC:\Progr
> am Files (x86)\Windows Kits\10\include\10.0.10586.0\winrt" /TcC:\Users\xbv784\Ap
> pData\Local\Temp\xmlXPathInitdto7rl4d.c /FoUsers\xbv784\AppData\Local\Temp\xmlXP
> athInitdto7rl4d.obj
>     xmlXPathInitdto7rl4d.c
>     C:\Users\xbv784\AppData\Local\Temp\xmlXPathInitdto7rl4d.c(1): fatal error C1
> 083: Cannot open include file: 'libxml/xpath.h': No such file or directory
>     ****************************************************************************
> *****
>     Could not find function xmlCheckVersion in library libxml2. Is libxml2 insta
> lled?
>     ****************************************************************************
> *****
>     error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\B
> IN\\cl.exe' failed with exit status 2
> 
>     ----------------------------------------
> Command "c:\users\xbv784\appdata\local\programs\python\python35-32\python.exe -u
>  -c "import setuptools, tokenize;__file__='C:\\Users\\xbv784\\AppData\\Local\\Te
> mp\\pip-build-mgmlzr97\\lxml\\setup.py';exec(compile(getattr(tokenize, 'open', o
> pen)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --recor
> d C:\Users\xbv784\AppData\Local\Temp\pip-6d18nevd-record\install-record.txt --si
> ngle-version-externally-managed --compile" failed with error code 1 in C:\Users\
> xbv784\AppData\Local\Temp\pip-build-mgmlzr97\lxml\

**Comment by ajinabraham** [comment]
Not a MobSF issue.
