### ISSUE TITLE
Potential issue with "(" characters

### ISSUE THREAD

**Issue by javixeneize** [ajinabraham/Mobile-Security-Framework-MobSF#260]
Hi

I have a problem when running MobSF in iOS apps when the app contains special characters (EG "(")

I have an app call javi(test).ipa. When running otool, it goes to Payload/javi(test).app/javi, when the real binary file is javi(test). As this file doesnt exist, it gives an error and fails

Thanks

**Comment by ajinabraham** [comment]
Can you share a sample ipa that exhibits this problem?

**Comment by ajinabraham** [comment]
Closing due to lack of response

**Comment by TiberiumPY** [comment]
@ajinabraham just rename any ipa to javi(test).ipa

**Comment by ajinabraham** [comment]
@TiberiumPY That filename is not causing any issue at my end.

**Comment by TiberiumPY** [comment]
@ajinabraham 
"I have an app call javi(test).ipa. When running otool, it goes to Payload/javi(test).app/javi, when the real binary file is javi(test). As this file doesnt exist, it gives an error and fails"

**Comment by TiberiumPY** [comment]
@ajinabraham did you ran otool

**Comment by ajinabraham** [comment]
Yup works fine
```
[INFO] Analysis is already Done. Fetching data from the DB...
[26/Dec/2016 16:51:27] "GET /StaticAnalyzer_iOS/?name=javi(test).ipa&type=ipa&checksum=c511c1008531955a2503d3e52d6f10a1 HTTP/1.1" 200 141207
[INFO] iOS Static Analysis Started
[INFO] iOS Binary (IPA) Analysis Started
[INFO] Generating Hashes
[INFO] Extracting IPA
[INFO] Unzipping
[INFO] Get Files, BIN Plist -> XML, and Normalize
[INFO] Starting Binary Analysis
[INFO] Reading Info.plist
[INFO] iOS Binary : MFAFIApp
[INFO] Running otool against the Binary
[INFO] Running class-dump-z against the Binary
[INFO] Running strings against the Binary

[INFO] Connecting to DB

[INFO] Updating Database...
[26/Dec/2016 16:51:29] "GET /StaticAnalyzer_iOS/?checksum=c511c1008531955a2503d3e52d6f10a1&name=javi(test).ipa&type=ipa&rescan=1 HTTP/1.1" 200 142903

```
