### ISSUE TITLE
Can I Configuring Dynamic Analyzer on MAC Book?

### ISSUE THREAD

**Issue by madhuCNKony** [ajinabraham/Mobile-Security-Framework-MobSF#266]
Can I Configuring Dynamic Analyzer on MAC Book?

After Importing MobSF_VM_X.X.ova to virtual box, under setting I selected Host Only Adapter

But while starting VM it is giving error to change network type.

Is this is expected?

**Comment by ajinabraham** [comment]
Yes you can configure it in MAC. It should be your Virtual Box Virtual Network problem.
