### ISSUE TITLE
IP management shows empty 

### ISSUE THREAD

**Issue by DinaHkr** [ajinabraham/Mobile-Security-Framework-MobSF#267]
Hi Ajin

i have got the below message once i start configuring with dynamic analysis  i dint get any ip management it shows empty value what is the solution for this ? ..

![capture](https://cloud.githubusercontent.com/assets/22589368/20473317/c8286ebe-afe5-11e6-86fb-400c53bfe142.JPG)

**Comment by ajinabraham** [comment]
Some issues with your VirtualBox Virtual Networking.

**Comment by DinaHkr** [comment]
Hi Ajin 

I have removed and reconfigured the virtual box but again it shows the same thing

**Comment by ajinabraham** [comment]
Try this once: https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/wiki/6.-What-to-do-when-MobSF-VM-and-VirtualBox-Host-Only-Adapter-are-not-in-the-same-network-range

**Comment by DinaHkr** [comment]
Hi Ajin

 I have tried everything it show the same thing so that i am stuck with dynamic analysis. is there any solution ?.

**Comment by ajinabraham** [comment]
This is not a MobSF problem. There is something wrong with your VirtualBox Network Configuration. You need to solve it first so that the VM gets an IP.

**Comment by DinaHkr** [comment]
can i get the link of .ovf link first version,it works on first version but it stucks with third version can i get the   URL of first version i'll download and check with that previous one .

**Comment by ajinabraham** [comment]
0.2: https://drive.google.com/open?id=0B_Ci-1YbMqshUnhHOU1LTDllRUE
0.1: https://drive.google.com/open?id=0B_Ci-1YbMqshalg4T3dFcG1lM0k

**Comment by DinaHkr** [comment]
Thank you i have got it .let me check and update you .

**Comment by rwang5** [comment]
I got this issue on Mac ox . This issue is due to user permission. Please try to change your user from standard user to system user.  You can find it and system perference. Enable  'Permit user can manage this computer'

**Comment by benbadio** [comment]
The real reason this issue happens is because a host network has to be set up with DHCP enabled in order for this to work. I had this issue and couldn't resolve it until I realized that I needed to enable DHCP. This requirement is not mentioned in the documentation for configuring the VM.
