### ISSUE TITLE
Trying to connect to port 5555:5555

### ISSUE THREAD

**Issue by securisec** [ajinabraham/Mobile-Security-Framework-MobSF#268]
This issue seems to pop up here and there it seems like. about 50% of the time, the connection to the physical device fails because it is trying to connect to 5555:5555... Any idea how to fix this?

**Comment by ajinabraham** [comment]
This can happen if you have multiple adb spawned and other connections are working. For example you are running Android Studio.

**Comment by SameerMB** [comment]
Thanks. But, in such case, how to solve it?
I quit android studio, also killed adb processes & still facing this issue.
I'm using latest release version (v0.9.3.1 Beta).

**Comment by SameerMB** [comment]
Well, I was trying with USB connection!
When I used WiFi ADB, all worked fine :)

**Comment by NeuroWinter** [comment]
Is there a real fix for this I am using wifi, no usb connected, killed all ADB, restarted server, restarted host, still same issue.
