### ISSUE TITLE
Can not runserver on win8.1 python 2.7.12

### ISSUE THREAD

**Issue by oMinGWo** [ajinabraham/Mobile-Security-Framework-MobSF#271]
I'm trying to runserver on my windows8.1 and python 2.7.12. version 0.92beta
But there are some problems 
Here are the logs:
![image](https://cloud.githubusercontent.com/assets/7437349/20524013/06d30044-b0f3-11e6-9d1b-03510c906c21.png)
It seems that the problem is about python, but I can run a former version 0.9.2 beta in the same enviroment.
How can I fix this problem?

**Comment by ajinabraham** [comment]
Make sure you are using Django 1.10 or above.
Also delete your db.sqlite3
run 
`pip install -r requirements.txt`
`python manage.py makemigrations && python manage.py migrate`

**Comment by ajinabraham** [comment]
v0.9.3 Beta will fix this: https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/releases/tag/v0.9.3
