### ISSUE TITLE
Using duplicate variables

### ISSUE THREAD

**Issue by secure-KOR** [ajinabraham/Mobile-Security-Framework-MobSF#272]
Hello, English is clumsy, but ... I was testing MobSF

[2016-11-23 11:52:41]
[ERROR] Extracting Manifest Data (/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/manifest_analysis.py, LINE 132 "lib.append(libary)"): Element instance has no attribute 'append'
[2016-11-23 11:52:41]
[ERROR] Performing Manifest Analysis (/root/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/android/manifest_analysis.py, LINE 379 "if item != man_data_dic['mainactivity']:"): 'NoneType' object has no attribute '__getitem__'

 The above error has occurred....
 I opened "manifest_analysis.py" and modified the code.

 The existing "manifest_analysis.py" line 130-132
[ 
130         for lib in libs: 
131             libary = lib.getAttribute("android:name")
132             lib.append(libary)
 ]

 I corrected it as follows.

[ 
130         for lib2 in libs: 
131             libary = lib2.getAttribute("android:name")
132             lib.append(libary)
 ]

 I do not know if it is a correct countermeasure.
 MobSF is conducive to studying.  Thank you all the time.

**Comment by ajinabraham** [comment]
@DominikSchlecht I guess it's a bug. Fixing it and bumping a minor version

**Comment by ajinabraham** [comment]
@secure-KOR: Thanks for pointing out. It's fixed in https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/commit/c571e9e516a7eeefb9ffad7e81b68f8f9bbbadcc 
And a version is bumped in MobSF.
