### ISSUE TITLE
Getting error while starting server

### ISSUE THREAD

**Issue by Arunraj89** [ajinabraham/Mobile-Security-Framework-MobSF#273]
Hi, while i am trying to start the server for the first time after new Mobsf update. But i am getting the following error message, Please help me

C:\Mobile-Security-Framework-MobSF-master>python manage.py runserver
            [INFO] Running first time setup for windows.
[*] Reading config file..
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 53, in __getattr__
    self._setup(name)
  File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Mobile-Security-Framework-MobSF-master\MobSF\settings.py", line 363, in <module>
    windows_setup.install_locally(MobSF_HOME)
  File "C:\Mobile-Security-Framework-MobSF-master\install\windows\setup.py", line 366, in install_locally
    rewrite_local_config(mobsf_home)
  File "C:\Mobile-Security-Framework-MobSF-master\install\windows\setup.py", line 349, in rewrite_local_config
    CONFIG['MobSF']['subdir_tools'] = mobsf_home + "\\StaticAnalyzer\\tools\\windows\\"
AttributeError: ConfigParser instance has no attribute '__getitem__'

I am using latest Python 2.7.12

**Comment by SameerMB** [comment]
I did faced similar problem earlier when I moved to latest release.
Running "pip install -r requirements.txt --user" solved my problem. Give it a try.

**Comment by ajinabraham** [comment]
Ya install the requirements.txt. That will solve it.

**Comment by Arunraj89** [comment]
I have installed requirements.txt, even then i am getting the same error. 

 C:\Python27\Scripts>pip.exe install -r requirements.txt --user
Requirement already satisfied: Django==1.10.b1 in c:\python27\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: pyOpenSSL==0.15 in c:\python27\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: tornado==4.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: xhtml2pdf==0.0.6 in c:\python27\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: html5lib==1.0b8 in c:\python27\lib\site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: psutil==4.2.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: rsa in c:\python27\lib\site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: configparser in c:\python27\lib\site-packages (from -r requirements.txt (line 8))
Requirement already satisfied: lxml in c:\python27\lib\site-packages (from -r requirements.txt (line 9))
Requirement already satisfied: six>=1.5.2 in c:\python27\lib\site-packages (from pyOpenSSL==0.15->-r requirements.txt (line 2))
Requirement already satisfied: cryptography>=0.7 in c:\python27\lib\site-packages (from pyOpenSSL==0.15->-r requirements.txt (line 2))
Requirement already satisfied: certifi in c:\python27\lib\site-packages (from tornado==4.1->-r requirements.txt (line 3))
Requirement already satisfied: backports.ssl_match_hostname in c:\python27\lib\site-packages (from tornado==4.1->-r requirements.txt (line 3))
Requirement already satisfied: pyPdf2 in c:\python27\lib\site-packages (from xhtml2pdf==0.0.6->-r requirements.txt (line 4))
Requirement already satisfied: Pillow in c:\python27\lib\site-packages (from xhtml2pdf==0.0.6->-r requirements.txt (line 4))
Requirement already satisfied: reportlab>=2.2 in c:\python27\lib\site-packages (from xhtml2pdf==0.0.6->-r requirements.txt (line 4))
Requirement already satisfied: pyasn1>=0.1.3 in c:\python27\lib\site-packages (from rsa->-r requirements.txt (line 7))
Requirement already satisfied: cffi>=1.1.0 in c:\python27\lib\site-packages (from cryptography>=0.7->pyOpenSSL==0.15->-r requirements.txt (line 2))
Requirement already satisfied: idna>=2.0 in c:\python27\lib\site-packages (from cryptography>=0.7->pyOpenSSL==0.15->-r requirements.txt (line 2))
Requirement already satisfied: ipaddress in c:\python27\lib\site-packages (from cryptography>=0.7->pyOpenSSL==0.15->-r requirements.txt (line 2))
Requirement already satisfied: setuptools in c:\python27\lib\site-packages (from cryptography>=0.7->pyOpenSSL==0.15->-r requirements.txt (line 2))
Requirement already satisfied: enum34 in c:\python27\lib\site-packages (from cryptography>=0.7->pyOpenSSL==0.15->-r requirements.txt (line 2))
Requirement already satisfied: pip>=1.4.1 in c:\python27\lib\site-packages (from reportlab>=2.2->xhtml2pdf==0.0.6->-r requirements.txt (line 4))
Requirement already satisfied: pycparser in c:\python27\lib\site-packages (from cffi>=1.1.0->cryptography>=0.7->pyOpenSSL==0.15->-r requirements.txt (line 2))

C:\Mobile-Security-Framework-MobSF-master>python manage.py runserver
[INFO] Running first time setup for windows.
[*] Reading config file..
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 53, in __getattr__
    self._setup(name)
  File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Mobile-Security-Framework-MobSF-master\MobSF\settings.py", line 363, in <module>
    windows_setup.install_locally(MobSF_HOME)
  File "C:\Mobile-Security-Framework-MobSF-master\install\windows\setup.py", line 366, in install_locally
    rewrite_local_config(mobsf_home)
  File "C:\Mobile-Security-Framework-MobSF-master\install\windows\setup.py", line 349, in rewrite_local_config
    CONFIG['MobSF']['subdir_tools'] = mobsf_home + "\\StaticAnalyzer\\tools\\windows\\"
AttributeError: ConfigParser instance has no attribute '__getitem__'

**Comment by ajinabraham** [comment]
@DominikSchlecht  Can you take a look into this?

**Comment by Arunraj89** [comment]
@DominikSchlecht @ajinabraham : Any update on this?

**Comment by DominikSchlecht** [comment]
Will have a link into it this evening.

You are using MobSF on Windows I assume? Or on Linux with Windows-VM?

Could you please test if ConfigParser is up-to-date and working correctly?

**Comment by DominikSchlecht** [comment]
Could you please check if CONFIG is set in `rewrite_local_config`? Just include a `print(CONFIG)` at the start of the function and check the output.

**Comment by Arunraj89** [comment]
Thanks @DominikSchlecht once i changed the location, it works fine. but i am getting different error message now like below:

C:\MobSF\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master>python manage.py runserver

[INFO] Finding JDK Location in Windows....

[INFO] Oracle JDK Identified. Looking for JDK 1.7 or above

[INFO] Oracle Java (JDK >= 1.7) is installed!

[INFO] Finding JDK Location in Windows....

[INFO] Oracle JDK Identified. Looking for JDK 1.7 or above

[INFO] Oracle Java (JDK >= 1.7) is installed!
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x0000000004DE8C88>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\core\management\commands\runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Python27\lib\site-packages\django\core\checks\registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Python27\lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "C:\Python27\lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "C:\Python27\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Python27\lib\site-packages\django\urls\resolvers.py", line 305, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Python27\lib\site-packages\django\urls\resolvers.py", line 298, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\MobSF\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\MobSF\urls.py", line 4, in <module>
    import DynamicAnalyzer.views.android
  File "C:\MobSF\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\DynamicAnalyzer\views\android.py", line 9, in <module>
    from DynamicAnalyzer.pyWebProxy.pywebproxy import *
  File "C:\MobSF\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\DynamicAnalyzer\pyWebProxy\pywebproxy.py", line 51, in <module>
    from DynamicAnalyzer.pyWebProxy.socket_wrapper import wrap_socket
  File "C:\MobSF\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\DynamicAnalyzer\pyWebProxy\socket_wrapper.py", line 35, in <module>
    from gen_cert import gen_signed_cert
  File "C:\MobSF\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\DynamicAnalyzer\pyWebProxy\gen_cert.py", line 32, in <module>
    from OpenSSL import crypto
  File "C:\Python27\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "C:\Python27\lib\site-packages\OpenSSL\rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "C:\Python27\lib\site-packages\OpenSSL\_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "C:\Python27\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by ajinabraham** [comment]
Not a MobSF Issue. Make sure the pyOpenSSL lib you have installed is compatible with your OS.
http://stackoverflow.com/questions/4676433/solving-dll-load-failed-1-is-not-a-valid-win32-application-for-pygame

**Comment by darshanaher** [comment]
I'm getting the following error when  installing requirement list. 



  copying src/cryptography/hazmat/backends/openssl/__init__.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
  running egg_info
  writing src/cryptography.egg-info/PKG-INFO
  writing dependency_links to src/cryptography.egg-info/dependency_links.txt
  writing requirements to src/cryptography.egg-info/requires.txt
  writing top-level names to src/cryptography.egg-info/top_level.txt
  reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching 'docs/_build'
  warning: no previously-included files matching '*' found under directory 'vectors'
  writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
  running build_ext
  generating cffi module 'build/temp.linux-x86_64-3.7/_padding.c'
  creating build/temp.linux-x86_64-3.7
  generating cffi module 'build/temp.linux-x86_64-3.7/_constant_time.c'
  generating cffi module 'build/temp.linux-x86_64-3.7/_openssl.c'
  building '_openssl' extension
  creating build/temp.linux-x86_64-3.7/build
  creating build/temp.linux-x86_64-3.7/build/temp.linux-x86_64-3.7
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -c build/temp.linux-x86_64-3.7/_openssl.c -o build/temp.linux-x86_64-3.7/build/temp.linux-x86_64-3.7/_openssl.o -Wconversion -Wno-error=sign-conversion
  build/temp.linux-x86_64-3.7/_openssl.c:493:10: fatal error: openssl/opensslv.h: No such file or directory
   #include <openssl/opensslv.h>
            ^~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for cryptography
  Running setup.py clean for cryptography
Successfully built capfuzz
Failed to build cryptography
mitmproxy 3.0.2 has requirement click<7,>=6.2, but you'll have click 7.0 which is incompatible.
Installing collected packages: cryptography, pyOpenSSL, ldap3, mitmproxy, capfuzz
  Found existing installation: cryptography 2.6.1
    Not uninstalling cryptography at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'cryptography'. No files were found to uninstall.
  Running setup.py install for cryptography ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-e9zh4_y2/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-sf4ccc07/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/cryptography
    copying src/cryptography/exceptions.py -> build/lib.linux-x86_64-3.7/cryptography
    copying src/cryptography/__about__.py -> build/lib.linux-x86_64-3.7/cryptography
    copying src/cryptography/utils.py -> build/lib.linux-x86_64-3.7/cryptography
    copying src/cryptography/fernet.py -> build/lib.linux-x86_64-3.7/cryptography
    copying src/cryptography/__init__.py -> build/lib.linux-x86_64-3.7/cryptography
    creating build/lib.linux-x86_64-3.7/cryptography/hazmat
    copying src/cryptography/hazmat/__init__.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat
    creating build/lib.linux-x86_64-3.7/cryptography/x509
    copying src/cryptography/x509/extensions.py -> build/lib.linux-x86_64-3.7/cryptography/x509
    copying src/cryptography/x509/base.py -> build/lib.linux-x86_64-3.7/cryptography/x509
    copying src/cryptography/x509/general_name.py -> build/lib.linux-x86_64-3.7/cryptography/x509
    copying src/cryptography/x509/name.py -> build/lib.linux-x86_64-3.7/cryptography/x509
    copying src/cryptography/x509/oid.py -> build/lib.linux-x86_64-3.7/cryptography/x509
    copying src/cryptography/x509/certificate_transparency.py -> build/lib.linux-x86_64-3.7/cryptography/x509
    copying src/cryptography/x509/__init__.py -> build/lib.linux-x86_64-3.7/cryptography/x509
    creating build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/hmac.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/padding.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/cmac.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/keywrap.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/mac.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/hashes.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/constant_time.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/serialization.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/__init__.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives
    creating build/lib.linux-x86_64-3.7/cryptography/hazmat/bindings
    copying src/cryptography/hazmat/bindings/__init__.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/bindings
    creating build/lib.linux-x86_64-3.7/cryptography/hazmat/backends
    copying src/cryptography/hazmat/backends/interfaces.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/backends
    copying src/cryptography/hazmat/backends/__init__.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/backends
    creating build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/hkdf.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/concatkdf.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/pbkdf2.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/scrypt.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/kbkdf.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/x963kdf.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/__init__.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/kdf
    creating build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/utils.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/hotp.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/totp.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/__init__.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/twofactor
    creating build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/base.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/algorithms.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/aead.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/modes.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/__init__.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/ciphers
    creating build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/dh.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/padding.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/utils.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/dsa.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/rsa.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/ec.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/x25519.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/__init__.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/primitives/asymmetric
    creating build/lib.linux-x86_64-3.7/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/_conditional.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/binding.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/__init__.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/bindings/openssl
    creating build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/dh.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/hmac.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/decode_asn1.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/backend.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/cmac.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/utils.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/encode_asn1.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/dsa.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/aead.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/rsa.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/ciphers.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/ec.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/hashes.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/x25519.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/x509.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/__init__.py -> build/lib.linux-x86_64-3.7/cryptography/hazmat/backends/openssl
    running egg_info
    writing src/cryptography.egg-info/PKG-INFO
    writing dependency_links to src/cryptography.egg-info/dependency_links.txt
    writing requirements to src/cryptography.egg-info/requires.txt
    writing top-level names to src/cryptography.egg-info/top_level.txt
    reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
    writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
    running build_ext
    generating cffi module 'build/temp.linux-x86_64-3.7/_padding.c'
    creating build/temp.linux-x86_64-3.7
    generating cffi module 'build/temp.linux-x86_64-3.7/_constant_time.c'
    generating cffi module 'build/temp.linux-x86_64-3.7/_openssl.c'
    building '_openssl' extension
    creating build/temp.linux-x86_64-3.7/build
    _**creating build/temp.linux-x86_64-3.7/build/temp.linux-x86_64-3.7
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -c build/temp.linux-x86_64-3.7/_openssl.c -o build/temp.linux-x86_64-3.7/build/temp.linux-x86_64-3.7/_openssl.o -Wconversion -Wno-error=sign-conversion
    build/temp.linux-x86_64-3.7/_openssl.c:493:10: fatal error: openssl/opensslv.h: No such file or directory
     #include <openssl/opensslv.h>
              ^~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
  Can't roll back cryptography; was not uninstalled
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-e9zh4_y2/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-sf4ccc07/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-e9zh4_y2/cryptography/**_
