### ISSUE TITLE
How to setup Web APIFuzzer?

### ISSUE THREAD

**Issue by luisxiaomai** [ajinabraham/Mobile-Security-Framework-MobSF#275]
I can't found any about Web API Fuzzer? Any setup or guide documentation?

**Comment by ajinabraham** [comment]
This is not a support forum. Please read: https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/blob/master/CONTRIBUTING.md#using-the-issue-tracker

You don't have to setup anything. Web API Fuzzer can be used after Dynamic Analysis.
