### ISSUE TITLE
mobsfy uses 32 bit adb

### ISSUE THREAD

**Issue by tautology0** [ajinabraham/Mobile-Security-Framework-MobSF#276]
The mobsfy.py script uses the 32 bit variant of adb that comes with MobSF. This fails on 64 bit Linux systems.

What would be nice is to have a --adb option so you can provide a path to an existing adb binary.

e.g. 
./mobsfy.py -i 0123456789ABCDEF -t 2 --adb /usr/bin/adb

**Comment by ajinabraham** [comment]
This can be done, or you can enable 32 bit support in linux at the moment.

**Comment by ajinabraham** [comment]
We are not planning to hardcode a 64 bit binary. In future we may move to a python adb wrapper.
