### ISSUE TITLE
Potential Error in Regex

### ISSUE THREAD

**Issue by ajinabraham** [ajinabraham/Mobile-Security-Framework-MobSF#279]
@DominikSchlecht  Is this regex correct? 
https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/blob/master/StaticAnalyzer/views/windows.py#L235

**Comment by DominikSchlecht** [comment]
Seems like some kind of encoding error, will have so look into it :)

**Comment by DominikSchlecht** [comment]
Yep, this is an error, seems like there were `'` around the regex. Don't ask me why they are in the encoded form here :/ Sadly this is also breaking the regex overall, so we should fix it asap.

Generally, should I just fix this and push to master or should I create a branch and let you test it?

**Comment by ajinabraham** [comment]
Push it to master
