### ISSUE TITLE
Report Generation Error

### ISSUE THREAD

**Issue by Arunraj89** [ajinabraham/Mobile-Security-Framework-MobSF#280]
Hi, Server getting started now and when the static scan got completed and when i try to download the report i am getting the below error:

[2016-11-29 23:21:09]
[ERROR] PDF Report Generation Error (C:\MobSF\Mobile-Security-Framework-MobSF-master\Mobile-Security-Framework-MobSF-master\StaticAnalyzer\views\shared_func.py, LINE 250 "pdf = pisa.pisaDocument(StringIO("{0}".format("): global name 'pisa' is not defined
[29/Nov/2016 23:21:09] "GET /PDF/?md5=0079faade84474fd046dd92bde9f8706&type=APK HTTP/1.1" 302 0
[29/Nov/2016 23:21:09] "GET /error/ HTTP/1.1" 200 4603

From the closed issue i understood that "pip install html5lib==1.0b8" can slove this issue, so i used that too. Even then i am getting the same error again.  

C:\Python27\Scripts>pip install html5lib==1.0b8
Collecting html5lib==1.0b8
  Using cached html5lib-1.0b8.tar.gz
Requirement already satisfied: six in c:\python27\lib\site-packages (from html5lib==1.0b8)
Installing collected packages: html5lib
  Running setup.py install for html5lib ... done
Successfully installed html5lib-1.0b8

**Comment by ajinabraham** [comment]
Try
`pip uninstall html5lib`
`pip install html5lib==1.0b8`

**Comment by ajinabraham** [comment]
Try this as well: https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/issues/208#issuecomment-237469060

**Comment by Arunraj89** [comment]
`pip install xhtml2pdf ` solves my issue. Thanks.
