### ISSUE TITLE
Datas not storing on DB 

### ISSUE THREAD

**Issue by DinaHkr** [ajinabraham/Mobile-Security-Framework-MobSF#281]
Hi Ajin

I have migrated sqlite to postgres after that if i start scan i can able check all the scan apk name on postgres database But the result i can not able to view on postgres (Static and Dynamic) what should i do ?..

**Comment by ajinabraham** [comment]
There was a bug. Fixed in the latest release v0.9.3.5 Beta. (https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/releases/tag/v0.9.3.5) 
Also follow the instructions: https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/wiki/Use-Postgres-Database-Instead-of-Sqlite3

**Comment by DinaHkr** [comment]
Hi Ajin

Works Perfect.
