### ISSUE TITLE
Windows App Binary Analysis Error

### ISSUE THREAD

**Issue by ajinabraham** [ajinabraham/Mobile-Security-Framework-MobSF#282]
I am seeing 
```
[2016-11-30 13:07:54]
[ERROR] Static Analyzer Windows (/Users/ajin/Code/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/windows.py, LINE 101 "bin_an_dic = _binary_analysis(app_dic)"): <Fault 1: "<class 'KeyError'>:'file_x64'">

````
again.

Here is the APPX that I used http://www.appx4fun.com/xap/8030/

**Comment by DominikSchlecht** [comment]
Hey Ajin,

I'm currently on a business trip, I will look into this on Monday.

Greetings,
Dominik

**Comment by kryptoknight13** [comment]
I am also facing the same issue.

**Comment by DominikSchlecht** [comment]
Strange, this should not appear because of the if-statement in line https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/blob/master/StaticAnalyzer/views/windows.py#L302.

Are you using windows 32 or 64 bit? I'm currently trying to recreate the issue.

**Comment by DominikSchlecht** [comment]
Could you please paste your `C:\\MobSF\\Config\\config.txt`?

For me it looks good on windows 10 x64:
```
[binskim]
nuget = Microsoft.CodeAnalysis.BinSkim
file_x86 = C:\MobSF\Tools\Microsoft.CodeAnalysis.BinSkim.1.3.6\tools\x86\BinSkim.exe
file_x64 = C:\MobSF\Tools\Microsoft.CodeAnalysis.BinSkim.1.3.6\tools\x64\BinSkim.exe
```

**Comment by ajinabraham** [comment]
I am on Windows 7 64bit Service Pack 1

**config.txt**
```
[MobSF]
dir = C:\MobSF
subdir_downloads = C:\MobSF\Downloads\
subdir_tools = C:\MobSF\Tools\
subdir_samples = C:\MobSF\Samples\
priv_key_file = C:\MobSF\Tools\windows_vm_priv_key.asc
pub_key_file = C:\MobSF\Tools\windows_vm_pub_key.asc

[nuget]
url = https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
file = nuget.exe

[binskim]
nuget = Microsoft.CodeAnalysis.BinSkim

[binscope]
url_x64 = https://download.microsoft.com/download/5/6/0/56027BE0-3A1F-4326-B966-BC99A15856AA/BinScope_x64.msi
url_x86 = https://download.microsoft.com/download/5/6/0/56027BE0-3A1F-4326-B966-BC99A15856AA/BinScope_x86.msi

[rpc]
url = https://raw.githubusercontent.com/ajinabraham/Mobile-Security-Framework-MobSF/master/install/windows/rpc_client.py
file = rpc_client.py

[autostart]
file = mobsf_rpc.bat
```

**Comment by ajinabraham** [comment]
Also everything worked on the same VM before.

**Comment by DominikSchlecht** [comment]
Seems like the paths for binskim were not set during setup.

You don't have the output of setup.py? ^^

Is binskim in the C:\\MobSF\\Tools folder?

**Comment by ajinabraham** [comment]
Yes Binskim is present in Tools

**Comment by DominikSchlecht** [comment]
Then it must be either a error finding the binaries or writing the config.

Could you please provide the structure of the Tools-Folder and especially the binskim-folders?

Thank you in advance.

**Comment by ajinabraham** [comment]
```
C:\MOBSF
├───Config
├───Downloads
├───Samples
└───Tools
    ├───BinScope
    │   ├───Plugins
    │   └───Reporting
    └───Microsoft.CodeAnalysis.BinSkim.1.3.6
        └───tools
            ├───x64
            └───x86
```

**Comment by DominikSchlecht** [comment]
I really don't see where the error could be.

1. Binskim gets installed, the output gets searched by a regex so the code will work with future versions (RE: b"Microsoft\.CodeAnalysis\.BinSkim\..*' ")
2. Depending on the Python-Version the "' " at the end of the matched string get removed
3. string gets concated with the tools-directory and search for exes with really simple tools. Even upper/lowecase in the path (e.g. your MOBSF dir is written uppercase on the filestructure but is lowercase in your config) should work just fine (tested with 32bit-Windows 7 like 10 minutes ago..).

Could you please retry and post the output of setup.py? :/

**Comment by ajinabraham** [comment]
rpc.py shows

```
Listening on port 8000...
172.16.244.1 - - [06/Dec/2016 19:58:34] "POST /RPC2 HTTP/1.1" 200 -
[*] Challenge successfully verified.
172.16.244.1 - - [06/Dec/2016 19:58:35] "POST /RPC2 HTTP/1.1" 200 -
172.16.244.1 - - [06/Dec/2016 19:58:35] "POST /RPC2 HTTP/1.1" 200 -
[*] Challenge successfully verified.
172.16.244.1 - - [06/Dec/2016 19:58:36] "POST /RPC2 HTTP/1.1" 200 -
```

<img width="571" alt="screen shot 2016-12-06 at 7 59 49 pm" src="https://cloud.githubusercontent.com/assets/4301109/20929093/a0ec5b5c-bbee-11e6-9c03-5c2f18329c71.png">
<img width="1143" alt="screen shot 2016-12-06 at 7 59 43 pm" src="https://cloud.githubusercontent.com/assets/4301109/20929095/a24fb368-bbee-11e6-9f73-85a8893ee92b.png">

**Comment by ajinabraham** [comment]
I see something wrong now

```
C:\Users\Ajin Abraham\Desktop>python setup.py
[*] Downloading config file..
[*] Saving to File config.txt
[*] Reading config file..
[*] Creating other folders...
[*] Checking dependencies...
[+] rsa is installed.
[+] Everything good.
[*] Downloading nuget..
[*] Saving to File nuget.exe
[*] Downloading and installing Binskim...
[!] Unable to parse folder from binskim nuget installation.
```

**Comment by ajinabraham** [comment]
@DominikSchlecht  I did the following

code change
```
output = subprocess.check_output(
        [
            nuget,
            "install", binskim_nuget, '-Pre',
            '-o', mobsf_subdir_tools
        ]
    )

    # Some code to determine the version on the fly so we don't have to fix the
    # config file on every new release of binskim..

    # Search for the version number
    print (output)
    folder = re.search(
        b"Microsoft\.CodeAnalysis\.BinSkim\..*' ", output # pylint: disable-msg=W1401
    )
print (folder)
```
```
[*] Downloading and installing Binskim...
b'Feeds used:\r\n  https://api.nuget.org/v3/index.json\r\n\r\n  GET https://api.
nuget.org/v3/registration1-gz/microsoft.codeanalysis.binskim/index.json\r\n  OK
https://api.nuget.org/v3/registration1-gz/microsoft.codeanalysis.binskim/index.j
son 6491ms\r\nPackage "Microsoft.CodeAnalysis.BinSkim.1.3.6" is already installe
d.\r\n'
None
[!] Unable to parse folder from binskim nuget installation.
```

Looks like the issue is with the regex.

Is this regex correct? 
```
b"Microsoft\.CodeAnalysis\.BinSkim\..*' "
```
Why the single quote?

**Comment by DominikSchlecht** [comment]
Now we are getting close. The single Quote works if binskim gets installed, but it seems that this is not correct if binskim is *already* installed.

I will check this tonight and propose a fix.

**Comment by DominikSchlecht** [comment]
<img width="920" alt="screen shot 2016-12-06 at 18 37 25" src="https://cloud.githubusercontent.com/assets/1722036/20936520/2e4f767a-bbe3-11e6-998e-50e0dd56ae98.png">

Jap that's it, `"`when reinstalling and `'`on the first install..

Pushing a fix in a few minutes.

**Comment by DominikSchlecht** [comment]
Could you please test and verify?

Re-installation now works on my vms.

**Comment by ajinabraham** [comment]
That fixes it! 👍
