### ISSUE TITLE
PDF Unicode Bug

### ISSUE THREAD

**Issue by secure-KOR** [ajinabraham/Mobile-Security-Framework-MobSF#283]
Report error when request Korean language APK.

Static Analysis - ■■■■.apk

FILE INFORMATION
Name ■■■■.apk

**Comment by ajinabraham** [comment]
Can you share the APK that caused this issue?

**Comment by secure-KOR** [comment]
@ajinabraham All APK in Korean .. For example : https://goo.gl/3Ha045
password : qqqq

**Comment by ajinabraham** [comment]
I am facing no issues with PDF generation.
See: https://drive.google.com/file/d/0B_Ci-1YbMqshdnRzM2hfTlFGLW8/view?usp=sharing
Please update to latest release

**Comment by secure-KOR** [comment]
@ajinabraham  ...... App name seems to be broken.
same file : https://drive.google.com/file/d/0ByqvBmv_ieShUF9KRnl0UGJHdUU/view?usp=sharing
filename : 안녕하세요.apk
git clone the latest version  v0.9.3.7 ...

**Comment by ajinabraham** [comment]
What exactly is the problem here? I can see the analysis running till end without any problem, also no issues with the PDF report generation as well.
