### ISSUE TITLE
Dynamic analysis reports not saving on postgres database 

### ISSUE THREAD

**Issue by DinaHkr** [ajinabraham/Mobile-Security-Framework-MobSF#285]
Hi Ajin 

I have got 
![capture](https://cloud.githubusercontent.com/assets/22589368/20785114/3b6467f6-b753-11e6-87e4-90b99e60bcf9.JPG)
this below error while doing dynamic analysis and data's not updating on database what is the solution ?.

**Comment by ajinabraham** [comment]
We don't store dynamic analysis results at the moment as they vary from analysis ti analysis of the same app.
The above error is shown if you are not running MobSF with enough permission to access the Temp directory.

**Comment by DinaHkr** [comment]
Hi Ajin 

Is there any way to store dynamic analysis report to the database ? ..

**Comment by ajinabraham** [comment]
Not implemented at the moment.

**Comment by DinaHkr** [comment]
Hi Ajin 

Then the result on browserdisplays from which location ? .

**Comment by ajinabraham** [comment]
It's from the files created during dynamic analysis in the scan directory. They will get overwritten the next time, you perform dynamic analysis on the APK.

**Comment by DinaHkr** [comment]
Hi Ajin

Thanks .
