### ISSUE TITLE
Dynamic Analysis Environment unable to connect VM

### ISSUE THREAD

**Issue by Arunraj89** [ajinabraham/Mobile-Security-Framework-MobSF#286]
Team, While trying to do Dynamic analysis i am getting error `[INFO] Connecting to VM/Device
unable to connect to 192.168.74.101:5555:5555` in the console. I have MobSF_VM_0.2.ova file. i have configured all setting as per [https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/wiki/1.-Documentation#configuring-mobsf-vm-with-the-dynamic-analyzer](url) 

My Console Error:
`[INFO] VM Starting
[01/Dec/2016 22:31:09] "POST /DynamicAnalyzer/ HTTP/1.1" 200 31947
[01/Dec/2016 22:31:09] "GET /download/screen/screen.png HTTP/1.1" 302 0
[01/Dec/2016 22:31:09] "GET /error/ HTTP/1.1" 200 4603

[INFO] Setting up Dynamic Analysis Environment

[INFO] Starting Web Proxy

[INFO] Started Web Proxy at 192.168.56.1:1337

[INFO] Connecting to VM/Device

[INFO] Getting ADB Location
* daemon not running. starting it now on port 5037 *
* daemon started successfully *

[INFO] ADB Started

[INFO] Waiting for 5 seconds...

[INFO] Connecting to VM/Device
unable to connect to 192.168.74.101:5555:5555`

My VM IP: `192.168.74.101`

While starting the VM, it's getting start from snapshot but while Trying to setup the environment only i am getting this error.

![image](https://cloud.githubusercontent.com/assets/16404627/20804052/693c5af2-b817-11e6-8c49-9e2f04d04bb2.png)

**Comment by ajinabraham** [comment]
See the both IP range are different.
Read: https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/wiki/6.-What-to-do-when-MobSF-VM-and-VirtualBox-Host-Only-Adapter-are-not-in-the-same-network-range
