### ISSUE TITLE
Regarding New Virtual machine 

### ISSUE THREAD

**Issue by DinaHkr** [ajinabraham/Mobile-Security-Framework-MobSF#287]
Hi Ajin 

I have installed new virtual machine and ip management i can not able to view IP address  once the android vm is turned ON what is the solution for that is there any configuration we need to setup with new virtual machine ? .. '

And i have tried these below link

https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/wiki/2.-Configure-MobSF-Dynamic-Analysis-Environment-in-your-Android-Device-or-VM

Once i use network adapter1 as Host only IP and second adapter as NAT but once i use this configuration i can not able to access the internet how to access the internet ajin pls help .

**Comment by ajinabraham** [comment]
If you are not getting IP, it may be some issues with your network/ virtual network. And what do you refer by "New Virtual Machine" ? If it's not the MobSF VM then you have to make sure that it has networking support to connect to internet.
