### ISSUE TITLE
[ASK]-Does Window App scanning supported on MAC Machine ? 

### ISSUE THREAD

**Issue by kryptoknight13** [ajinabraham/Mobile-Security-Framework-MobSF#288]

**Comment by kryptoknight13** [comment]
please do elaborate more on dependencies, if any.

**Comment by DominikSchlecht** [comment]
Dear @kryptoknight13,

with only Mac in place, only a small potion (scanning for bad function) works.

MobSF for Windows-Apps is only fully functional with Mac/Linux + windows vm attached (actually the setup I implemented it) or when running on native windows. Please look into the wiki for instruction about how to setup the VM.

If you have further questions, please feel free to ask. (I will close this issue in 2 days.)

Greetings,
Dominik

**Comment by ajinabraham** [comment]
@kryptoknight13 This is the wiki entry: https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/blob/master/install/windows/readme.md
