### ISSUE TITLE
Dynamic Analyzer - Android 6.0 support

### ISSUE THREAD

**Issue by AresS31** [ajinabraham/Mobile-Security-Framework-MobSF#289]
Hello,

I would like to know if the Dynamic Analyzer supports the version 6.0 of Android.

It is written on the wiki that only version 4 of Android is supported, is that up to date?

If yes, do you plan to make the latest versions of Android compatible anytime soon?

Thanks,
Alex

**Comment by ajinabraham** [comment]
It's not supported at the moment. To make it compatible, you might need to update components like Xposed and should get a VM that can be accessed by IP.

**Comment by AresS31** [comment]
Well, Xposed Framework, Rootcloak and SSLUnpinning are all supported by Android 6.0, so theoritically it could be possible to run the Dynamic Analyzer, am I right?
