### ISSUE TITLE
Dynamic Analysis ERROR!

### ISSUE THREAD

**Issue by bitian** [ajinabraham/Mobile-Security-Framework-MobSF#291]
when I start Dynamic Analysis,the program run as following and stop,I don't konw why it can't run .can you help me ?
![default](https://cloud.githubusercontent.com/assets/14858638/20912285/479107dc-bba9-11e6-8349-b1368bb2af57.PNG)

**Comment by ajinabraham** [comment]
Share the logs.

**Comment by bitian** [comment]
the logs only these

**Comment by ajinabraham** [comment]
You don't have anything in logs/MobSF.log ? Please clear it before running again.

**Comment by bitian** [comment]
I have clear logs,nothing in logs/MobSF.log. I use IE11,MobSF and Virtualbox installed D disk.
![default](https://cloud.githubusercontent.com/assets/14858638/20915321/1fbd3c00-bbc0-11e6-9449-b5a288def044.PNG)

**Comment by bitian** [comment]
MOBSF_VM version is 0.2

**Comment by ajinabraham** [comment]
It's difficult to troubleshoot with out error.

1. Can you try this on Chrome or Firefox.
2. Does your browser goes to error page when you click on Start Dynamic Analysis, if so what is the error. 
3. Retry the Start Dynamic Analysis button if the VM is not booting up.
4. Make sure the VM UUID and Snapshot ID are correct

**Comment by ajinabraham** [comment]
It's recommend to use the lastest version of MobSF and the VM

**Comment by ajinabraham** [comment]
Use 0.3 VM

**Comment by bitian** [comment]
thank you , now I download 0.3 VM and try

**Comment by bitian** [comment]
hello,I have run 0.3 VM,but the following error occurred:

![default](https://cloud.githubusercontent.com/assets/14858638/20917957/834ced7e-bbcf-11e6-9c0d-41dc5a63658a.PNG)
I need your help,thank you.

**Comment by ajinabraham** [comment]
These errors are normal and should not affect the dynamic analysis process. Does the VM boot up when you press start dynamic analysis?

**Comment by bitian** [comment]
Yeah,when I press start dynamic analysis,the VM boot up.When the VM is started,I use command "adb shell" in cmd,it show "error: device not found".Is this right?

**Comment by ajinabraham** [comment]
You should not do that. MobSF uses an adb instance. If you are running another instance of adb/ android studio in parallel. It will cause issue in communication. What is the real problem you face after the VM boots up?

**Comment by bitian** [comment]
After the VM boots up,the browser shows as below : 
![09816062-bbd2-11e6-853e-70d2db8b891b](https://cloud.githubusercontent.com/assets/14858638/21000059/98dbde18-bd53-11e6-9eb1-2d2c7ea1570a.PNG)
all logs below:
![default](https://cloud.githubusercontent.com/assets/14858638/21000094/cd46d8ec-bd53-11e6-94e7-74c2453c5a77.PNG)

**Comment by ajinabraham** [comment]
IT looks Messed up. You are missing something. The CSS and JavaScript is not running properly from the screenshot. Create Environment should be a button.
