### ISSUE TITLE
MobSF doesn't initialise on Windows

### ISSUE THREAD

**Issue by pwntoken** [ajinabraham/Mobile-Security-Framework-MobSF#292]
Had a couple of fix points for MobSF on Mac (Will share them on a different issue ticket);

This is on Windows with Latest MobSF code along with all `requirements` full-filled. Checked the code, on `line 9` & it were Nuget (It's fine). Not sure what went wrong. Neither did `/logs/` had any additional file created.

![screen shot 2016-12-06 at 11 35 59 am](https://cloud.githubusercontent.com/assets/11158935/20914906/a61b1bae-bba8-11e6-9ae6-c57bbb2668e9.png)

**Comment by ajinabraham** [comment]
@DominikSchlecht can you look into this? Looks like Config file read/write error.

**Comment by koehntopp** [comment]
Similar issue here:

`>python manage.py runserver
[INFO] Running first time setup for windows.
[*] Reading config file..
[*] Downloading nuget..
[*] Saving to File nuget.exe
[*] Downloading and installing Binskim...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "c:\python27\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "c:\python27\lib\site-packages\django\core\management\__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "c:\python27\lib\site-packages\django\conf\__init__.py", line 53, in __getattr__
    self._setup(name)
  File "c:\python27\lib\site-packages\django\conf\__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "c:\python27\lib\site-packages\django\conf\__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "c:\python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\MobSF\MobSF\settings.py", line 367, in <module>
    windows_setup.install_locally(MobSF_HOME)
  File "C:\MobSF\install\windows\setup.py", line 370, in install_locally
    tools_binskim()
  File "C:\MobSF\install\windows\setup.py", line 148, in tools_binskim
    '-o', mobsf_subdir_tools
  File "c:\python27\lib\subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "c:\python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "c:\python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 1392] The file or directory is corrupted and unreadable`

**Comment by DominikSchlecht** [comment]
@pwntoken, duplicate of #278.
ConfigParser is unable to init the instance, please check privs and that all required files are there. There should be one config in `\\MobSF\\install\\windows\\config.txt`nwhich will be copied over to either `\\MobSF\\MobSF\\config.txt` or the user-defined path from settings.py, if it is set. Please verify, that this step is possible.

@koehntopp, same root-cause, as the log already states "The file or directory is corrupted and unreadable" please make sure that the paths stated in `\\MobSF\\config.txt` are writeable.

**Comment by ajinabraham** [comment]
@DominikSchlecht This problem will occur a lot in future with most of the people. How about moving MobSF to %temp% or other local directory? (We need to make sure that these files are not deleted or cleaned as the RSA private key/other significant files will be lost)

**Comment by koehntopp** [comment]
This is the first release where this happens (and I don't even need Windows... ;) ) the paths in config.txt and settings.py don't look consistent, specifically c:\MobSF\MobSF will usually not be there, also capitalization is different.
I have no way of making this work through permissions, this is Windows, after all...

**Comment by DominikSchlecht** [comment]
@ajinabraham I will try to implement it this week, but I don't really think that it will fix the rights-problem, if there is any. The Tools get installed in the StaticAnalyzer/x/Tools folder right now if you install MobSF on a Windows machine, which I find fairly user friendly.

@koehntopp sry if I have to ask back, what do you mean by:
> "c:\MobSF\MobSF" will usally not be there
and 
> also capitalization is different.

Could you please post the corresponding text-snippets? I also don't think that this a rights problem, also on a second read your error message seems strange. Maybe the download just failed and the file was corrupt? o0

I just re-tested the setup on Windows 10/7 each 32/64 bit without problems :/

**Comment by ajinabraham** [comment]
I just suggested to temp directory as usually Windows allows to extract files to Temp without much permission restrictions. The only problem I see is if the temp dir is cleaned, it will cause more trouble. How about Home directory?
`MobSF_HOME = os.path.join(os.path.expanduser('~'), ".MobSF")` 

Because normally browsers download into Downloads in Home dir. I think home dir is a good candidate when we use Windows VM and a simpler exception printing for config parser so that people can understand from the error message itself.

**Comment by DominikSchlecht** [comment]
Done with 83613af855c9bd33ca6ab735339e59e519b12bf5, please test and verify.

I would advice to take a new virtual machine, or to really *deinstall* binskim, since the MSI seems to take the path of the previous installation instead of the the one I tell it to install to..

**Comment by victorpresas93** [comment]
Unhandled exception in thread started by <function wrapper at 0x02DF6CB0>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\utils\autoreload.py", line 226, in
wrapper
    fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\core\management\commands\runserver.
py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 385,
 in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 372,
 in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Python27\lib\site-packages\django\core\checks\registry.py", line 81,
in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Python27\lib\site-packages\django\core\checks\urls.py", line 14, in c
heck_url_config
    return check_resolver(resolver)
  File "C:\Python27\lib\site-packages\django\core\checks\urls.py", line 24, in c
heck_resolver
    for pattern in resolver.url_patterns:
  File "C:\Python27\lib\site-packages\django\utils\functional.py", line 35, in _
_get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Python27\lib\site-packages\django\urls\resolvers.py", line 305, in ur
l_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\utils\functional.py", line 35, in _
_get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Python27\lib\site-packages\django\urls\resolvers.py", line 298, in ur
lconf_module
    return import_module(self.urlconf_name)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\MobSF-0.9.3.7\MobSF\urls.py", line 3, in <module>
    import APITester.views
  File "C:\MobSF-0.9.3.7\APITester\views.py", line 27, in <module>
    from lxml import etree
ImportError: No module named lxml

**Comment by ajinabraham** [comment]
@victorpresas93  This is an unrelated entry. You have to install lxml module!

**Comment by ajinabraham** [comment]
@DominikSchlecht I am testing this on fresh Windows 10 64bit. I think there is some issues with the arguments passed to BinScope. Please refer the below Screenshots
<img width="1029" alt="screen shot 2016-12-23 at 12 24 14 pm" src="https://cloud.githubusercontent.com/assets/4301109/21448636/f97b0ce0-c90a-11e6-8de6-2418f31f1418.png">
<img width="953" alt="screen shot 2016-12-23 at 12 24 23 pm" src="https://cloud.githubusercontent.com/assets/4301109/21448638/fb1db46c-c90a-11e6-8339-3b877b900b4e.png">

**Comment by DominikSchlecht** [comment]
Hmm will look into it.

Is it really a fresh windows 10 it just a fresh install of mobsf? Could you please try to deinstall binscope and retry? 

Greetings, 
Dominik

**Comment by ajinabraham** [comment]
Yes as recommended it's the base snapshot of a Windows 10 image. Everything starting from python was freshly installed.

**Comment by DominikSchlecht** [comment]
I think this is because of the space in the username. 

Sadly because of Christmas I will not be able to fix this today.

I will push a commit to fix this tomorrow evening. 

Greetings,
Dominik

**Comment by ajinabraham** [comment]
Happy Christmas dude. Enjoy!

**Comment by DominikSchlecht** [comment]
Thanks :)

Should now be fixed. Especially when installing the msi with `INSTALLOCATION="SOME PATH WITH SPACES"` using subprocess caused me some headache. Sadly I had to switch to os.system :/

Tested in remote environments with usernames with and without spaces. 

Greetings,
Dominik

**Comment by ajinabraham** [comment]
All good. Thanks for the quick fix!
