### ISSUE TITLE
[ERROR]xhtml2pdf is not installed，but I have installed

### ISSUE THREAD

**Issue by jackwuzz** [ajinabraham/Mobile-Security-Framework-MobSF#294]
[ERROR] xhtml2pdf is not installed. Cannot generate PDF reports (/Users/jack-bldz/Mobile-Security-Framework-MobSF-master/StaticAnalyzer/views/ios.py, LINE 25 "import xhtml2pdf.pisa as pisa"): cannot import name viewkeys

![image](https://cloud.githubusercontent.com/assets/22313763/21171467/3efbeb32-c207-11e6-80ad-de889c91eb0f.png)

**Comment by ajinabraham** [comment]
This is a duplicate please look on the closed bugs before posting issuse. https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/issues/230

**Comment by jackwuzz** [comment]
OK，thanks
