### ISSUE TITLE
Identify browsable activities during manifest analysis

### ISSUE THREAD

**Issue by oldbam** [ajinabraham/Mobile-Security-Framework-MobSF#295]
From looking at the source code, it looks like MobSF does not highlights browsable activities during manifest analysis in any way. Here is a [source code from drozer](https://github.com/mwrlabs/drozer/blob/06710506ab0b51129942bf9f4c3f685c277ba6c2/src/drozer/modules/scanner/activity/browsable.py) that performs the same action. It looks like an important check for assessing android applications, and having it as part of manifest analysis would be a good addition.

**Comment by ajinabraham** [comment]
This feature is now available in master
<img width="1031" alt="screen shot 2016-12-15 at 5 56 50 pm" src="https://cloud.githubusercontent.com/assets/4301109/21225229/ec8c8ec0-c2f5-11e6-92a7-ee17aa42674b.png">
