### ISSUE TITLE
Regarding method not supported 

### ISSUE THREAD

**Issue by DinaHkr** [ajinabraham/Mobile-Security-Framework-MobSF#297]
Hi Ajin

I have created upload form and i tried to upload apk file on my system with my created form and it says method not supported how to solve that, can you pls guide me?
![capture](https://cloud.githubusercontent.com/assets/22589368/21424734/a8460456-c86a-11e6-9efc-c2cbc0da2353.JPG)

**Comment by ajinabraham** [comment]
You got that error as MobSF received an OPTIONS request. 
Due to the fact that Anti CSRF Token is present, You can't just create a form and upload the APK. MobSF will reject it.

**Comment by DinaHkr** [comment]
Hi Ajin

Thanks for the reply .
