### ISSUE TITLE
Any API support for MobSF?

### ISSUE THREAD

**Issue by pnigos** [ajinabraham/Mobile-Security-Framework-MobSF#299]
Hi,I'd like to know if there a plan to develop API support like upload apk,start scan,get report for MobSF?

Thanks!

**Comment by ajinabraham** [comment]
Nothing much at the moment. But a hacky implementation for uploading and starting scan is available here: https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/blob/master/mass_static_analysis.py You can also call appropriate URLS to get report or generate PDF.
