### ISSUE TITLE
How to acesss MobSF with my interface?..

### ISSUE THREAD

**Issue by DinaHkr** [ajinabraham/Mobile-Security-Framework-MobSF#300]
Hi Ajin

How to access my interface with MobSF?..

**Comment by DinaHkr** [comment]
Hi Ajin

I have seen http://127.0.0.1:8000/upload/ ,But i could not find any folder name there pls kindly guide me .

**Comment by ajinabraham** [comment]
This is an issue tracker. Please use this to post MobSF bugs only. https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/blob/master/CONTRIBUTING.md#using-the-issue-tracker

/upload/ is not a directory like it is a django API endpoint. If you are trying to programically upload a file you have to script something similar to: https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/blob/master/mass_static_analysis.py#L86

**Comment by DinaHkr** [comment]
Hi Ajin

Thanks
