### ISSUE TITLE
IOS Zipped file not working.

### ISSUE THREAD

**Issue by nandankd** [ajinabraham/Mobile-Security-Framework-MobSF#304]
After zipped file is uploaded , it is redirected to /zip_format/ page

e.g. you can try this project : https://github.com/ooyala/ios-sample-apps/tree/stable/AdvancedPlaybackSampleApp

**Comment by ajinabraham** [comment]
Works fine for me. I had pushed a bug fix but that is not related to this. You need to follow the instructions.
```
iOS Project: For iOS projects, the .xcodeproj file must exist in the root directory of the ZIPPED Source files.
```

**Comment by nandankd** [comment]
I have pulled the latest changes , but still having the same problem. Could you please try with this zipped ios Project. http://wikisend.com/download/379012/AdvancedPlaybackSampleApp.zip 
(.xcodeproj file is on the root directory )

**Comment by ajinabraham** [comment]
There is some issue with the way you zipped that files. I had extracted the same and then zipped again and it works fine. Scan the attachment with MobSF
[Archive.zip](https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/files/678275/Archive.zip)
