### ISSUE TITLE
Kali-Install-MobSF-Issues

### ISSUE THREAD

**Issue by ztencmcp** [ajinabraham/Mobile-Security-Framework-MobSF#306]
hello,

I get this issue when i execute "./manage.py runserver". What's going on here. Thanks.
![image](https://cloud.githubusercontent.com/assets/22705390/21540839/334d2822-cded-11e6-9ec6-87b08d8f1266.png)

**Comment by ajinabraham** [comment]
You have issues with pyopenssl lib, try updating it to the latest and update your python to the latest in 2.7 branch
