### ISSUE TITLE
Setup Issue

### ISSUE THREAD

**Issue by adarshsvnair** [ajinabraham/Mobile-Security-Framework-MobSF#307]
Hi Ajin,

While installing MobSF, I am getting the following error. 

**AttributeError: 'module' object has no attribute 'SSL_ST_INIT'**

Could you please help me on fixing it?

Thanks
Adarsh Nair

**Comment by ajinabraham** [comment]
Please check closed bugs before opening new issues
https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/issues/293
Update your pyOpenSSL to latest version
