### ISSUE TITLE
Dynamic Analysis Error

### ISSUE THREAD

**Issue by adarshsvnair** [ajinabraham/Mobile-Security-Framework-MobSF#309]
Please help. I am including the logs below.

[2017-01-07 00:34:59]
[ERROR]  Connecting to VM/Device (/home/adarshvnair/MobSF/DynamicAnalyzer/views/android.py, LINE 725 "subprocess.call([adb, "kill-server"])"): [Errno 2] No such file or directory

[INFO] Starting App for Dynamic Analysis

[INFO] Getting ADB Location

[INFO] Installing APK

[2017-01-07 00:34:59]
[ERROR]  Starting App for Dynamic Analysis (/home/adarshvnair/MobSF/DynamicAnalyzer/views/android.py, LINE 751 "subprocess.call([adb, "-s", getIdentifier(), "install", "-r", APKPATH])"): [Errno 2] No such file or directory

[INFO] Getting Screen Resolution

[INFO] Getting ADB Location

[2017-01-07 00:34:59]
[ERROR] Getting Screen Resolution (/home/adarshvnair/MobSF/DynamicAnalyzer/views/android.py, LINE 1137 "[adb, "-s", getIdentifier(), "shell", "dumpsys", "window"])"): [Errno 2] No such file or directory
[07/Jan/2017 00:34:59] "POST /GetEnv/ HTTP/1.1" 200 58

[INFO] Getting ADB Location

[INFO] Installing MobSF RootCA

[INFO] Starting Clipboard Dump Service in VM/Device

[INFO] Getting ADB Location

[2017-01-07 00:34:59]
[ERROR] MobSF RootCA Handler (/home/adarshvnair/MobSF/DynamicAnalyzer/views/android.py, LINE 313 "ROOTCA, "/data/local/tmp/" + settings.ROOT_CA])"): [Errno 2] No such file or directory
[07/Jan/2017 00:34:59] "POST /MobSFCA/ HTTP/1.1" 302 0

[2017-01-07 00:34:59]
[ERROR] Dumping Clipboard (/home/adarshvnair/MobSF/DynamicAnalyzer/views/android.py, LINE 226 "subprocess.call(args)"): [Errno 2] No such file or directory
[07/Jan/2017 00:34:59] "POST /ClipDump/ HTTP/1.1" 200 19
[07/Jan/2017 00:35:00] "GET /error/ HTTP/1.1" 200 4603

**Comment by adarshsvnair** [comment]
Could you please help me?

**Comment by ajinabraham** [comment]
Either you don't have permission or you don't have 32 bit execution support

**Comment by adarshsvnair** [comment]
Could you please tell me which permission is required?

**Comment by kobebryamv2** [comment]
Could you please tell me which permission is required?
The same happens to me

**Comment by ajinabraham** [comment]
Executable permission. Make sure you can execute the adb bundled with MobSF

**Comment by kobebryamv2** [comment]
only works with 32 bit system
