### ISSUE TITLE
Dynamic Analysis ERROR no such file or directory

### ISSUE THREAD

**Issue by kobebryamv2** [ajinabraham/Mobile-Security-Framework-MobSF#310]
![screenshot_3](https://cloud.githubusercontent.com/assets/25012069/21775708/703ca052-d697-11e6-82dd-fa612737e39b.png)

The error happens when I press the button [Create environment]

I have verified that the IPS are in the same network.
I checked the permissions.
I have also checked the names of the VM and screeenshot
I do not know what may be happening.

Does anyone feel the same?
Could someone help me?

**Comment by SyrianProgrammer** [comment]
the problem with adb binary file 
edit file /Mobile-Security-Framework-MobSF-master/MobSF/settings.py
on line 257 replace with ADB_BINARY = "/usr/bin/adb"               #path adb binary for Linux

**Comment by ajinabraham** [comment]
Make sure your system support 32 bit execution

**Comment by kobebryamv2** [comment]
thanks. only works with 32 bit system
