### ISSUE TITLE
Dynamic Analysis ERROR unfortunately, <app name> has stopped.

### ISSUE THREAD

**Issue by SyrianProgrammer** [ajinabraham/Mobile-Security-Framework-MobSF#311]
hello, i tried to build your project and i have  issue with dynamic scan for apk when the project install the app it getting crash  immediately because the version of android doesn't work anymore on this old version.
how can i solve it ?
one think more which os you used to build android can give me a link or name of the website to build android lollipop or marshmallow ?

**Comment by ajinabraham** [comment]
You might need to configure a real device and do the Analysis
