### ISSUE TITLE
Report Download Error

### ISSUE THREAD

**Issue by shashankhacker730** [ajinabraham/Mobile-Security-Framework-MobSF#44]
Hi Team,

The final report get downloaded in PNG format and that file is corrupt.
Kindly check the issue.

Thanks,
SHG
![error](https://cloud.githubusercontent.com/assets/6128222/8889366/76bcc6c4-32f5-11e5-97ba-84afdd310f73.png)

**Comment by ajinabraham** [comment]
Known issue, we are moving to PDF reports in the future, when the page is so large, there is some bugs with html2canvas image generation.

**Comment by bugwrangler** [comment]
Just FYI - It's working for me over the CH latest in Mac machine.

**Comment by ajinabraham** [comment]
@bugwrangler For some large images this issue occurs. 
This issue will be fixed on 0.8.8 Beta as PDF reporting will replace Image Reports.

**Comment by ajinabraham** [comment]
Fixed in v0.8.8 - New PDF reporting is available now.
