### ISSUE TITLE
There should be nice error handler when binary unable reverse. 

### ISSUE THREAD

**Issue by bugwrangler** [ajinabraham/Mobile-Security-Framework-MobSF#46]
Take out the binary from playstore  : com.barclays.android.barclaysmobilebanking  

<img width="1136" alt="screen shot 2015-08-04 at 3 45 50 pm" src="https://cloud.githubusercontent.com/assets/6933052/9058587/f11a0842-3abf-11e5-8871-45a56f84f818.png">

Observe the Framework went to debugging state which can be disabled using manage.py however there should be proper error handler in either of scenario.

**Comment by ajinabraham** [comment]
Framework is in Beta so it will continue to run on Debug Mode. Will investigate further on that APK and this issue.

**Comment by ajinabraham** [comment]
Identified the issue. This is an issue with python zip file module. Will fix this by using an alternate unzip module or utility.

**Comment by ajinabraham** [comment]
Even other platforms are failing to unzip that file properly.

**Comment by ajinabraham** [comment]
Fixed in V0.8.8 and fix is available for Unix.
