### ISSUE TITLE
In the case of strong binary, Failure message should be more clear and self exploratory.  [Enc] 

### ISSUE THREAD

**Issue by bugwrangler** [ajinabraham/Mobile-Security-Framework-MobSF#47]
<img width="855" alt="screen shot 2015-08-04 at 4 00 33 pm" src="https://cloud.githubusercontent.com/assets/6933052/9058869/460b154c-3ac2-11e5-8ade-cd36f48d796f.png">

**Comment by ajinabraham** [comment]
some DexGuard Protected binaries have there manifest file with non-utf-8 charset and the XML parser fails. Due to that manifest file analysis is not done. Only code analysis is done. That's the reason for Failed message and blank Distribution.

Will see If I can do some work arounds in future.
