### ISSUE TITLE
Don't Play Around. An Error just popped in!

### ISSUE THREAD

**Issue by adithyanaresh** [ajinabraham/Mobile-Security-Framework-MobSF#53]
![mobsf](https://cloud.githubusercontent.com/assets/2325491/9784657/2d9dd6dc-57ca-11e5-93d8-ae60e2f487d3.PNG)
When i runserver says zero errors.Any clue what would be the problem.Java installed properly and set up good.Django also.

**Comment by ajinabraham** [comment]
Can you paste your console log here.

**Comment by ajinabraham** [comment]
Fixed. Some problems with git. Dex2Jar lib directory was not uploaded.
Re download from : https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/releases/tag/0.8.8.1
