### ISSUE TITLE
Download report as PDF shows "Don't Play Around. An Error just popped in!"

### ISSUE THREAD

**Issue by bugwrangler** [ajinabraham/Mobile-Security-Framework-MobSF#56]
I am using on Mac and shows this error with google chrome browser. 

<img width="1063" alt="screen shot 2015-09-10 at 4 37 31 pm" src="https://cloud.githubusercontent.com/assets/6933052/9786798/8576c728-57da-11e5-9697-6b928ceb450f.png">

**Comment by ajinabraham** [comment]
Console log please.

**Comment by ajinabraham** [comment]
I suppose you have not install the dependencies
`pip install -r requirements.txt` check the documentation

**Comment by Cn33yX7** [comment]
i am not install the dependencies,  thanks!

2015-09-10 20:03 GMT+08:00 Ajin Abraham <notifications@github.com>:

**Comment by bugwrangler** [comment]
Abhinavs-MacBook-Pro:MobSF BugWrangler$ python manage.py runserver 127.0.0.1:9095

[INFO] Finding JDK Location in Linux/MAC....

[INFO] Oracle Java is installed!

[INFO] JDK 1.7 or above is available

[INFO] Finding JDK Location in Linux/MAC....

[INFO] Oracle Java is installed!

[INFO] JDK 1.7 or above is available
Performing system checks...

System check identified no issues (0 silenced).
September 20, 2015 - 21:46:47
Django version 1.8, using settings 'MobSF.settings'
Starting development server at http://127.0.0.1:9095/
Quit the server with CONTROL-C.

[ERROR] xhtml2pdf is not installed. Cannot generate PDF reports

[INFO] Fetching data from DB for PDF Report Generation (Android)

[ERROR] PDF Report Generation Error - global name 'pisa' is not defined Line: 137
[20/Sep/2015 21:47:27]"GET /PDF/?md5=11712c6819c577feb2cfd7a731cd1c2c&type=APK HTTP/1.1" 302 0
[20/Sep/2015 21:47:27]"GET /error/ HTTP/1.1" 200 2927
[INFO] Mobile Security Framework v0.8.8beta
[20/Sep/2015 21:47:30]"GET / HTTP/1.1" 200 7201
[INFO] MIME Type: application/octet-stream FILE: android-debug (1).apk
[20/Sep/2015 21:47:36]"POST /Upload/ HTTP/1.1" 200 144
[INFO] Starting Analysis on : android-debug (1).apk

[INFO] Analysis is already Done. Fetching data from the DB...
[20/Sep/2015 21:47:36]"GET /StaticAnalyzer/?name=android-debug%20(1).apk&type=apk&checksum=11712c6819c577feb2cfd7a731cd1c2c HTTP/1.1" 200 41713

[INFO] Fetching data from DB for PDF Report Generation (Android)

[ERROR] PDF Report Generation Error - global name 'pisa' is not defined Line: 137

**Comment by bugwrangler** [comment]
Abhinavs-MacBook-Pro:MobSF BugWrangler$ pip install -r requirements.txt

Requirement already satisfied (use --upgrade to upgrade): Django==1.8 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from -r requirements.txt (line 1))

Downloading/unpacking pyOpenSSL==0.15 (from -r requirements.txt (line 2))
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement pyOpenSSL==0.15 (from -r requirements.txt (line 2))

Cleaning up...
No distributions at all found for pyOpenSSL==0.15 (from -r requirements.txt (line 2))
Storing debug log for failure in /Users/BugWrangler/.pip/pip.log

**Comment by ajinabraham** [comment]
Working fine for me
```
C:\Users\Ajin>c:\Python27\Scripts\pip.exe install pyOpenSSL==0.15
Requirement already satisfied (use --upgrade to upgrade): pyOpenSSL==0.15 in c:\python27\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): six>=1.5.2 in c:\python27\lib\site-packages (from pyOpenSSL==0.15)
Requirement already satisfied (use --upgrade to upgrade): cryptography>=0.7 in c:\python27\lib\site-packages (from pyOpenSSL==0.15)
Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\python27\lib\site-packages (from cryptography>=0.7->pyOpenSSL==0.15)
Requirement already satisfied (use --upgrade to upgrade): enum34 in c:\python27\lib\site-packages (from cryptography>=0.7->pyOpenSSL==0.15)
Requirement already satisfied (use --upgrade to upgrade): ipaddress in c:\python27\lib\site-packages (from cryptography>=0.7->pyOpenSSL==0.15)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.8 in c:\python27\lib\site-packages (from cryptography>=0.7->pyOpenSSL==0.15)
Requirement already satisfied (use --upgrade to upgrade): idna>=2.0 in c:\python27\lib\site-packages (from cryptography>=0.7->pyOpenSSL==0.15)
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.1.0 in c:\python27\lib\site-packages (from cryptography>=0.7->pyOpenSSL==0.15)
Requirement already satisfied (use --upgrade to upgrade): pycparser in c:\python27\lib\site-packages (from cffi>=1.1.0->cryptography>=0.7->pyOpenSSL==0.15)
```

Probably some issues with your pip. Reinstall your pip or try alternative methods to install pyOpenSSL 0.15  and other problematic dependencies.

**Comment by bugwrangler** [comment]
I acknowledge this issue due to xhtml2pdf & psutil. Sorry for the hassle!

**Comment by thiruspark** [comment]
Hi, i too face the same problem, 

while scanning the android apk the following error arises,
"Don't Play Around. An Error just popped in!

MS-Windows OS system call failed."

i have installed latest versions of python, jdk, pip scripts components
below are the log, please help me in rectifying this issue

C:\Users\isms\Desktop\Thirumurugan\tools\Android testing\Mobile-Security-Fr
amework-MobSF-0.8.8.2>manage.py runserver

[INFO] Finding JDK Location in Windows....

[INFO] Oracle JDK Identified. Looking for JDK 1.7 or above

[ERROR] Cannot Run Process - [Error 2] The system cannot find the file specified


[ERROR] Oracle JDK 1.7 or above is not found!

[INFO] Finding JDK Location in Windows....

[INFO] Oracle JDK Identified. Looking for JDK 1.7 or above

[ERROR] Cannot Run Process - [Error 2] The system cannot find the file specified


[ERROR] Oracle JDK 1.7 or above is not found!
Performing system checks...

System check identified no issues (0 silenced).
January 13, 2016 - 17:44:39
Django version 1.8, using settings 'MobSF.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[INFO] MIME Type: application/vnd.android.package-archive FILE: myCams.apk
[13/Jan/2016 17:44:48]"POST /Upload/ HTTP/1.1" 200 133
[INFO] Starting Analysis on : myCams.apk
[INFO] Generating Hashes
[INFO] Unzipping
[INFO] Getting Hardcoded Certificates
[INFO] APK Extracted
[INFO] Getting Manifest from Binary
[INFO] AXML -> XML
[INFO] Parsing AndroidManifest.xml
[INFO] Extracting Manifest Data
[INFO] Manifest Analysis Started
[INFO] Formatting Permissions
[INFO] Reading Signer Certificate
[INFO] DEX -> JAR
[INFO] Running JAVA Path fix in Windows
C:\Users\cams_isms\Desktop\Thirumurugan\tools\Android testing\Mobile-Security-Fr
amework-MobSF-0.8.8.2\uploads\d194e38945abd0212cf66184a1fd4aa7\classes.jar exist
s, use --force to overwrite
[INFO] DEX -> SMALI
