### ISSUE TITLE
When the VM isn't available, error should be user friendly (at Start Dynamic Analysis) 

### ISSUE THREAD

**Issue by bugwrangler** [ajinabraham/Mobile-Security-Framework-MobSF#57]
<img width="1409" alt="screen shot 2015-09-10 at 4 41 43 pm" src="https://cloud.githubusercontent.com/assets/6933052/9786998/3c5ef63a-57dc-11e5-91a3-b8f369371811.png">

**Comment by ajinabraham** [comment]
Looks like you are in a hurry. Have you gone through https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/wiki/Documentation ?
