### ISSUE TITLE
Dynamic Analysis Error:OSError at /DynamicAnalyzer/

### ISSUE THREAD

**Issue by jackmasa** [ajinabraham/Mobile-Security-Framework-MobSF#60]
OSError at /DynamicAnalyzer/
[Errno 2] No such file or directory
Request Method:	POST
Request URL:	http://127.0.0.1:8000/DynamicAnalyzer/
Django Version:	1.8
Exception Type:	OSError
Exception Value:	
[Errno 2] No such file or directory
Exception Location:	/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py in _execute_child, line 1335
Python Executable:	/usr/bin/python
Python Version:	2.7.10
Python Path:	
['/Users/xsser/Mobile-Security-Framework-MobSF',
 '/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC',
 '/Library/Python/2.7/site-packages']

**Comment by ajinabraham** [comment]
I just did a fresh install of MobSF on Ubuntu and Linux and couldn't reproduce this issue. It works fine for me.
This looks like you may not have permission to execute it.
Try this and let me know the outcome.
Go to the root directory of Mobile Security Framework
Give 
`sudo chmod -r 777 DynamicAnalyzer/tools/`

**Comment by ariveirab** [comment]
Hello 

Maybe the problem is the Virtualbox installation directory. I changed on settings.py the VBOX directory from /usr/bin to usr/local/bin. I hope it helps.

else:
    #For OSX and Linux
    #JAVA_PATH='/usr/bin/'
    JAVA_PATH=java.FindJava()
    VBOX='/usr/local/bin/VBoxManage'

Bye

**Comment by ajinabraham** [comment]
See if this helps

**Comment by ajinabraham** [comment]
@jackmasa what was the issue?

**Comment by jackmasa** [comment]
@ajinabraham  not have permission.

**Comment by jackmasa** [comment]
@ajinabraham 
```chmod: 777: No such file or directory```
???
