### ISSUE TITLE
Not able to download the ova file from https://goo.gl/PmLt78

### ISSUE THREAD

**Issue by chenji1978** [ajinabraham/Mobile-Security-Framework-MobSF#61]
May be for the internet connectivity, the MobSF_VM_0.1 file was not be downloaded from the site:https://goo.gl/PmLt78, so, can the owner or any other help provide one other way to download it?

Thanks and BR,
Ji (at China)

**Comment by JackLong89** [comment]
Hi Ji, 

VM file is available at : https://drive.google.com/file/d/0B_Ci-1YbMqshalg4T3dFcG1lM0k/view?pli=1

**Comment by chenji1978** [comment]
Hi Jack,

Many thanks for the site you provide.
Very sorry, it seem that this URL seem not to be accessed here.
So, on my honest, would  you like put this file to this site (cloud disk), https://pan.baidu.com, and you can share it after you upload the file into it. If that OK, I will very appreciate it, thanks!

BR,
Ji

**Comment by chenji1978** [comment]
Because in China, there has been prohibited to access any site related to Google,so, if anyone can help share this ova file on the site available for Chinese, I will appreciate it very much, thanks more if anybody can help do it!!

**Comment by ajinabraham** [comment]
I will move the VM to amadon S3 or similar storage and update the links soon.
Sad that you can't access Google in China. But out of curiosity, Google and it products actually worked for me in shanghai airport. it was 3 years back.

**Comment by chenji1978** [comment]
:) I'm glad when saw that you say it ok when at Shanghai,but, the "3 years back" in the end let me get upset right now.
BUT, it let us(include the others in China) feel so lucky that you plan to move VM image to amazon S3, thank you very much! You are best man!

**Comment by chenji1978** [comment]
It seem there is no hope to be able to get such image .ova file even if I keep checking the progress everyday. 
Hope anyone who saw this message could give me one hand on it, thanks!!

**Comment by ajinabraham** [comment]
Hey @chenji1978 It seems you are so desperate to get the OVA file. Here is an unofficial link to the OVA. https://www.dropbox.com/s/qkx5wnr8ltj5x3p/MobSF_VM_0.1.ova?dl=0
