### ISSUE TITLE
Unable to get proxy connection to work in dynamic analysis

### ISSUE THREAD

**Issue by mrtompa** [ajinabraham/Mobile-Security-Framework-MobSF#62]
I'm not able to get the proxy connection to work. I get the error message: net::ERR_PROXY_CONNECTION_FAILED.

I can ping from host to guest, and guest to host. If I disable proxy settings, everything works fine. I've tried to disable win firewall but that didn't help.

Information about my configuration:

Description . . . . . . . . . . . : VirtualBox Host-Only Ethernet Adapter
Physical Address. . . . . . . . . : 08-00-27-00-88-31
DHCP Enabled. . . . . . . . . . . : No
Autoconfiguration Enabled . . . . : Yes
Link-local IPv6 Address . . . . . : fe80::b043:2fd8:8a4b:682d%6(Preferred)
IPv4 Address. . . . . . . . . . . : 192.168.56.1(Preferred)
Subnet Mask . . . . . . . . . . . : 255.255.255.0

proxy in VM: 192.168.56.1, port 1337

settings.py:
#VM/Device IP
VM_IP='192.168.56.101'
#PROXY SETTINGS
PROXY_IP='192.168.56.1' #Host/Server/Proxy IP
PORT='1337' #Proxy Port

Log from starting VM:
[INFO] VM Starting
[14/Sep/2015 13:52:29]"POST /DynamicAnalyzer/ HTTP/1.1" 200 17778

[INFO] HTTPS Proxy (PID: 1368) Running on 192.168.56.1:1337
[WebProxy Error] [Errno 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
* daemon not running. starting it now on port 5037 *
* daemon started successfully *

[INFO] ADB Started

[INFO] Waiting for 7 seconds...

[INFO] Connecting to VM
connected to 192.168.56.101:5555

**Comment by ajinabraham** [comment]
[WebProxy Error] [Errno 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

port 1337 is already used by some other application.
Kill that application or else change the MobSF proxy port in settings and VM.

**Comment by mrtompa** [comment]
I tried the changes you suggested but I'm still not successfull.

[INFO] VM Starting
[15/Sep/2015 09:12:26]"POST /DynamicAnalyzer/ HTTP/1.1" 200 17778

[INFO] HTTPS Proxy (PID: 11384) Running on 192.168.56.1:1340
* daemon not running. starting it now on port 5037 *
* daemon started successfully *

I also tried wget with proxy settings from shell on device, but can't connect to proxy. Host is reachable from VM:

1|root@mobsec:/etc # ping 192.168.56.1
PING 192.168.56.1 (192.168.56.1) 56(84) bytes of data.
64 bytes from 192.168.56.1: icmp_seq=1 ttl=128 time=0.376 ms
64 bytes from 192.168.56.1: icmp_seq=2 ttl=128 time=0.479 ms
^X64 bytes from 192.168.56.1: icmp_seq=3 ttl=128 time=0.858 ms
64 bytes from 192.168.56.1: icmp_seq=4 ttl=128 time=1.22 ms
64 bytes from 192.168.56.1: icmp_seq=5 ttl=128 time=0.636 ms
64 bytes from 192.168.56.1: icmp_seq=6 ttl=128 time=0.871 ms
^C
--- 192.168.56.1 ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5003ms

And proxy should be listening on port 1340:

$ netstat -nao | grep 1340
  TCP    192.168.56.1:1340      0.0.0.0:0              LISTENING       11384

Any suggestions?

**Comment by saravanapriya1991** [comment]
Hi,
I would like to clarify my doubt with settings.py
i didnt change any values like UUID, SUUID, VM_IP etc in settings.py. But still my MobSF VM is working and generating results for dynamic analysis.? How is it possible ? Kindly suggest

**Comment by ajinabraham** [comment]
It won't function properly until you specify all the values correctly
