### ISSUE TITLE
Static Analyze IPA,Why show "File format not Supported!"

### ISSUE THREAD

**Issue by fishjing2015** [ajinabraham/Mobile-Security-Framework-MobSF#63]
log:
[INFO] Mobile Security Framework v0.8.8beta
[15/Sep/2015 16:22:17] "GET / HTTP/1.1" 200 7201
[INFO] MIME Type: application/x-zip-compressed FILE: MobileControl.ipa
[15/Sep/2015 16:22:30] "POST /Upload/ HTTP/1.1" 200 75
[INFO] Mobile Security Framework v0.8.8beta

**Comment by ajinabraham** [comment]
MIMEType issue for IPA.

Re download this file : https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/blob/master/MobSF/views.py

or 

Re download and configure the new release: https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/releases/tag/0.8.8.2

**Comment by fishjing2015** [comment]
Thanks very much!

**Comment by Vivek-jadon** [comment]
Showing Apk file unsupported . Please help

**Comment by Vivek-jadon** [comment]
Log:

[19/Jan/2016 10:31:36]"GET /static/fonts/glyphicons-halflings-regular.woff HTTP/
1.1" 200 23320
[19/Jan/2016 10:31:36]"GET /static/favicon HTTP/1.1" 404 1634
[INFO] MIME Type: application/x-gsarcade-usersvc FILE: 20150213-prod.apk
[19/Jan/2016 10:32:28]"POST /Upload/ HTTP/1.1" 200 75
[INFO] Mobile Security Framework v0.8.8beta

**Comment by ajinabraham** [comment]
@Vivek-jadon This (application/x-gsarcade-usersvc ) is not a MIME type for an APK. 
A vulnerability with similar MIME-TYPE http://www.securityfocus.com/archive/1/331083
