### ISSUE TITLE
[Dynamic Analysis] dump & logcat output 0 bytes.

### ISSUE THREAD

**Issue by whitehatpanda** [ajinabraham/Mobile-Security-Framework-MobSF#65]
There are no data found in dump, logcat text output after dynamic analysis finished. Check my attachment!
![error1](https://cloud.githubusercontent.com/assets/5643884/9900570/e1b963c8-5c8b-11e5-8014-f8d6c20f9016.png)
![api_monitor_no_data](https://cloud.githubusercontent.com/assets/5643884/9900578/ee20e500-5c8b-11e5-817c-7dc405c59c71.png)

**Comment by ajinabraham** [comment]
Please share the console logs of MobSF.
Have you gone through the Documentation Wiki?

**Comment by whitehatpanda** [comment]
After your comment, i recheck all the console logs and i think that the reason is why the API Monitor and some logs file with 0 bytes content is:

[INFO] Activity Screenshot Taken
WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.
WARNING: linker: app_process has text relocations. This is wasting memory and is a security risk. Please fix.

[INFO] Stopping App
[18/Sep/2015 23:03:18]"POST /ExportedActivityTester/ HTTP/1.1" 200 22
'D:\Work\Mobile' is not recognized as an internal or external command,
operable program or batch file.

[INFO] Downloading Logcat logs
'D:\Work\Mobile' is not recognized as an internal or external command,
operable program or batch file.

[INFO] Downloading Droidmon API Monitor Logcat logs
'D:\Work\Mobile' is not recognized as an internal or external command,
operable program or batch file.

[INFO] Downloading Dumpsys logs
WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.
WARNING: linker: app_process has text relocations. This is wasting memory and is a security risk. Please fix.

[INFO] Stopping Application
[18/Sep/2015 23:04:13]"POST /FinalTest/ HTTP/1.1" 200 16

Root cause: "'D:\Work\Mobile' is not recognized as an internal or external command,
operable program or batch file."

Solution is there is no existing of any space characters in the MobSF path.
