### ISSUE TITLE
Update VM for dynamic analysis or documentation to build own

### ISSUE THREAD

**Issue by raymontag** [ajinabraham/Mobile-Security-Framework-MobSF#66]
Hi,

could you please update the VM for the dynamic analysis to a recent version of Android or provide some documentation  what is needed to do this ourselves?

Thanks,

Karsten

**Comment by ajinabraham** [comment]
Xposed is not stable for Android 5.0, Will eventually move once things are stabilised.
Will be adding the doc to configure a VM soon.
