### ISSUE TITLE
Dynamic Analysis can not run 

### ISSUE THREAD

**Issue by bitian** [ajinabraham/Mobile-Security-Framework-MobSF#69]
When I start Dynamic Analyzer,the log is:
---------------------------------------
[INFO] VM Closed
Restoring snapshot 49825fe1-e15b-49e2-8db9-b5cd1a09813b
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%

[INFO] VM Restore Snapshot
Waiting for VM "450fc65c-c9cf-43ff-ab5e-10ed0eb9a7b8" to power on...
VM "450fc65c-c9cf-43ff-ab5e-10ed0eb9a7b8" has been successfully started.

[INFO] VM Starting
[28/Sep/2015 09:52:55]"POST /DynamicAnalyzer/ HTTP/1.1" 200 17736
---------------------------------------------------------------------------------

After this,it cann't run,where is wrong？

**Comment by ajinabraham** [comment]
OS Please..
After that what happens?
Add the complete console log.

**Comment by bitian** [comment]
After this nothing hanppen,what is wrong?

**Comment by ajinabraham** [comment]
Hey @bitian Provide the details of the OS on which you are trying to run MobSF. Also send across the complete console logs of MobSF. Then only I troubleshoot the issue happening for you.

**Comment by bitian** [comment]
My OS is Windows8,the complete console logs only contain below contents:
-----------------------------------------------------------------------------------------------------
c:\MobSF>python manage.py runserver

[INFO] Finding JDK Location in Windows....

[INFO] Oracle JDK Identified. Looking for JDK 1.7 or above

[INFO] Oracle Java (JDK >= 1.7) is installed!

[INFO] Finding JDK Location in Windows....

[INFO] Oracle JDK Identified. Looking for JDK 1.7 or above

[INFO] Oracle Java (JDK >= 1.7) is installed!
Performing system checks...

System check identified no issues (0 silenced).
October 09, 2015 - 09:29:09
Django version 1.8, using settings 'MobSF.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[INFO] Mobile Security Framework v0.8.8beta
[09/Oct/2015 09:29:15]"GET / HTTP/1.1" 200 7201
[INFO] MIME Type: application/octet-stream FILE: FristProject.apk
[09/Oct/2015 09:29:19]"POST /Upload/ HTTP/1.1" 200 139
[INFO] Starting Analysis on : FristProject.apk

[INFO] Analysis is already Done. Fetching data from the DB...
[09/Oct/2015 09:29:20]"GET /StaticAnalyzer/?name=FristProject.apk&type=apk&check
sum=f6d803a8f8e7d2f4284fe1e5cfdc9016 HTTP/1.1" 200 28513
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%

[INFO] VM Closed
Restoring snapshot 88213fc1-144f-467b-bf5a-648b1792fa56
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%

[INFO] VM Restore Snapshot
Waiting for VM "eaad2f5f-9993-45f6-878c-3110cdb6db0c" to power on...
VM "eaad2f5f-9993-45f6-878c-3110cdb6db0c" has been successfully started.

[INFO] VM Starting
[09/Oct/2015 09:29:49]"POST /DynamicAnalyzer/ HTTP/1.1" 200 17776
 I have sent email to you about the log screenshot.Thank you very much.
--------------------------------------------------------------------------------------------------

**Comment by ajinabraham** [comment]
v0.9 released please try again and reopen if applicable.
