### ISSUE TITLE
HTTPS proxy issue 

### ISSUE THREAD

**Issue by dimpol** [ajinabraham/Mobile-Security-Framework-MobSF#70]
I have the following setup : 
Virtualbox (on Windows 8.1 machine) : Running the MobSF VM 0.1 ova file (VM's IP: 192.168.56.101)
VMware (on Windows 8.1 machine) : Running Kali Linux with the MobSF 
Windows 8.1 Proxy/Host/IP : 192.168.1.176

I have filled the setting.py correctly.

I think there is a problem with the creation of the HTTPS proxy. When I try to browse from the emulator using the 192.168.1.176:1337 proxy, the following error appears ERR_PROXY_CONNECTION_FAILED

Logs:
[INFO] VM Starting
[28/Sep/2015 12:05:47]"POST /DynamicAnalyzer/ HTTP/1.1" 200 17694

[INFO] HTTPS Proxy (PID: 2946) Running on 192.168.1.176:1337
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
[WebProxy Error] [Errno 99] Cannot assign requested address

[INFO] ADB Started

[INFO] Waiting for 7 seconds...

[INFO] Connecting to VM
connected to 192.168.56.101:5555

[INFO] Mounting

[INFO] Installing APK
........

192.168.1.176 and 192.168.56.101 are both ping-able from my kali linux machine, where I run the mobSF server.

Can you please help me on how I can resolve the proxy issue?

**Comment by ajinabraham** [comment]
Wrong setup.

The VM and MobSF should be directly connected to host OS (Win 8.1)

Install MobSF in Win 8.1 and Virtual Box in Win 8.1, load the VM to the VirtualBox and follow the documentation.
