### ISSUE TITLE
Failure while uploading the code which is written in the android studio.

### ISSUE THREAD

**Issue by bugwrangler** [ajinabraham/Mobile-Security-Framework-MobSF#71]
Android Studio Project: AndroidManifest.xml must be located at 'app/src/main/AndroidManifest.xml' and the directory 'app/src/main/java/' must exist for Android Studio projects. 

E.G - https://github.com/bugwrangler/Digitalbank - Compile using the Android studio and followed it out the same pattern of structure.

**Comment by bugwrangler** [comment]
<img width="1174" alt="screen shot 2015-09-29 at 2 13 50 am" src="https://cloud.githubusercontent.com/assets/6933052/10156505/d0ee0efe-664f-11e5-87cb-1df84651cdfd.png">

**Comment by ajinabraham** [comment]
You are doing it wrong somewhere. It's working fine for me.

[download (1).pdf](https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/files/4496/download.1.pdf)

**Comment by ajinabraham** [comment]
Make Sue you zip the contents of the root directory and not any folders.
<img width="796" alt="1" src="https://cloud.githubusercontent.com/assets/4301109/10169258/e959950a-66ed-11e5-9c2a-9f1da97b1779.png">
