### ISSUE TITLE
Dynamic Analysis - HTTP(S) Request headers in logs?

### ISSUE THREAD

**Issue by jveGH1** [ajinabraham/Mobile-Security-Framework-MobSF#72]
Hi, 

I am using v0.8.8beta. Everything works fine so far but I noticed one minor issue: After performing an dynamic analysis, in the report in the "HTTP(S) Traffic" section the wrong header fields seem to be included for the requests. 

E.g. I get the following output:

REQUEST: GET https://data.flurry.com/aap.do
**Date: Tue, 13 Oct 2015 18:10:17 GMT
Transfer-Encoding: chunked
Connection: close
Server: nginx**
  
RESPONSE: 400 Bad Request
Date: Tue, 13 Oct 2015 18:10:17 GMT
Transfer-Encoding: chunked
Connection: close
Server: nginx

The header fields for the request are the same as the ones in the response. I cannot include full logs at the moment as I was working on a non-public app, but if you need more info I can create those on a fresh setup with a demo app.

Thanks for this tool BTW,  great work :)

**Comment by jveGH1** [comment]
Nevermind, I think I just figured it out, the following change in *MobSF/DynamicAnalyzer/tools/pyWebProxy* seems to do the trick:

```
$ diff proxy.py proxy.py.old 
59c59
<     for header, value in list(request.headers.items()):
---
>     for header, value in list(response.headers.items()):
```

**Comment by ajinabraham** [comment]
Nice catch! Actually it should be `response.request.headers` instead of `request.headers`
