### ISSUE TITLE
Can i use Genymotion x86 based instead of Emulator (your provided VM)

### ISSUE THREAD

**Issue by whitehatpanda** [ajinabraham/Mobile-Security-Framework-MobSF#75]
Hi there,

Can you share any document to build or change the Emulator to Genymotion x86 based?

**Comment by ajinabraham** [comment]
Most of the things on device is available here https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/tree/master/DynamicAnalyzer/tools/onDevice
In addition to these, lot's of patches are made to the emulator to fake real device environment. these are not documented and there are other things in priority.
