### ISSUE TITLE
Save analysis results

### ISSUE THREAD

**Issue by h4ng3r** [ajinabraham/Mobile-Security-Framework-MobSF#78]
Could be nice to store the results and a way to access them after. I've this implemented in the old version and for my team is perfect.

**Comment by ajinabraham** [comment]
Download the latest MobSF: https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/releases/tag/0.8.8.2

This version has support for PDF reports and Static Analysis Reports are stored in DB. You can access them using MD5 checksum of the apk or zipped file.
