### ISSUE TITLE
Don't Play Around. An Error just popped in! And No Exception On Logs...

### ISSUE THREAD

**Issue by ahmatjan** [ajinabraham/Mobile-Security-Framework-MobSF#79]
There Is Logs
[10/Nov/2015 16:34:56]"GET / HTTP/1.1" 200 7201
[INFO] MIME Type: application/octet-stream FILE: KYFX.apk
[10/Nov/2015 16:34:58]"POST /Upload/ HTTP/1.1" 200 131
[INFO] Starting Analysis on : KYFX.apk
[INFO] Generating Hashes
[INFO] Unzipping
[INFO] Getting Hardcoded Certificates
[INFO] APK Extracted
[INFO] Getting Manifest from Binary
[INFO] AXML -> XML
[INFO] Parsing AndroidManifest.xml
[INFO] Extracting Manifest Data
[INFO] Manifest Analysis Started
[INFO] Formatting Permissions
[INFO] Reading Signer Certificate
[10/Nov/2015 16:34:59]"GET /StaticAnalyzer/?name=KYFX.apk&type=apk&checksum=32a1
db719e24bcecadf1f8b29a51a039 HTTP/1.1" 200 2931

**Comment by ajinabraham** [comment]
Which OS are you using? 
Is Oracle Java installed and made the default?

**Comment by ahmatjan** [comment]
[INFO] Finding JDK Location in Windows....

[INFO] Oracle JDK Identified. Looking for JDK 1.7 or above

[INFO] Oracle Java (JDK >= 1.7) is installed!

[INFO] Finding JDK Location in Windows....

[INFO] Oracle JDK Identified. Looking for JDK 1.7 or above

[INFO] Oracle Java (JDK >= 1.7) is installed!
Performing system checks...

System check identified no issues (0 silenced).
November 16, 2015 - 11:56:43
Django version 1.8, using settings 'MobSF.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

**Comment by ajinabraham** [comment]
Closing this as I am tracking the bug here: https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/issues/80
