### ISSUE TITLE
I think this is a bug

### ISSUE THREAD

**Issue by ahmatjan** [ajinabraham/Mobile-Security-Framework-MobSF#80]
StaticAnalyzer/views.py files in a row 904 have an exception is not caught , resulting in abnormal exit when handling rsa certificate file
subprocess.check_output(args) => If returncode is not 0 , then include an error (subprocess.CalledProcessError)

My English is not good, this is translation by Google

**Comment by ahmatjan** [comment]
You can contact me by E-mail{rootbyme@gmail.com}

**Comment by ajinabraham** [comment]
Strange error. I need more information

**Comment by ahmatjan** [comment]
I save the error msg by python in this where 
throw at row 904 in file StaticAnalyzer/views.py
       dat=escape(subprocess.check_output(args)).replace('\n', '</br>')

[ERROR]
'utf8' codec can't decode byte 0xca in position 39: invalid continuation byte. You passed in '[\n[\n  Version: V3\n  Subject: CN=DH, OU=\xca\xfd\xd7\xd6\xcc\xec\xcc\xc3\xa3\xa8\xb1\xb1\xbe\xa9\xa3\xa9\xcd\xf8\xc2\xe7\xbc\xbc\xca\xf5\xd3\xd0\xcf\xde\xb9\xab\xcb\xbe, O=\xca\xfd\xd7\xd6\xcc\xec\xcc\xc3\xa3\xa8\xb1\xb1\xbe\xa9\xa3\xa9\xcd\xf8\xc2\xe7\xbc\xbc\xca\xf5\xd3\xd0\xcf\xde\xb9\xab\xcb\xbe, L=\xba\xa3\xb5\xed, ST=\xb1\xb1\xbe\xa9, C=86\n  Signature Algorithm: SHA1withRSA, OID = 1.2.840.113549.1.1.5\n\n  Key:  \n  Validity: [From: Mon Apr 22 14:45:31 CST 2013,\n               To: Sun Aug 23 14:45:31 CST 3012]\n  Issuer: CN=DH, OU=\xca\xfd\xd7\xd6\xcc\xec\xcc\xc3\xa3\xa8\xb1\xb1\xbe\xa9\xa3\xa9\xcd\xf8\xc2\xe7\xbc\xbc\xca\xf5\xd3\xd0\xcf\xde\xb9\xab\xcb\xbe, O=\xca\xfd\xd7\xd6\xcc\xec\xcc\xc3\xa3\xa8\xb1\xb1\xbe\xa9\xa3\xa9\xcd\xf8\xc2\xe7\xbc\xbc\xca\xf5\xd3\xd0\xcf\xde\xb9\xab\xcb\xbe, L=\xba\xa3\xb5\xed, ST=\xb1\xb1\xbe\xa9, C=86\n  SerialNumber: [    5174dc8b]\n\n]\n  Algorithm: [SHA1withRSA]\n  Signature:\n0000: 10 60 2A AA EA A8 79 D6   35 3A B7 95 B3 6C F3 06  .`*...y.5:...l..\r\n0010: 14 A7 3A 9E D4 A3 6B 9A   B5 4B 3E B0 8A 2C CA 44  ..:...k..K>..,.D\r\n0020: BE 69 59 1A 5E 40 2D 91   02 04 44 BA A9 52 21 C5  .iY.^@-...D..R!.\r\n0030: AE D3 B6 91 CB E7 BC 1B   43 9A 19 F2 14 90 81 8F  ........C.......\r\n0040: E4 67 C4 C1 0A 59 F8 CE   F9 1F CE CE F3 00 86 EA  .g...Y..........\r\n0050: 7A C4 52 08 48 96 03 75   CF AF 70 EB BD DF C0 4D  z.R.H..u..p....M\r\n0060: E8 BF B2 30 AD DC C9 9E   A6 78 DC E3 55 9F 03 39  ...0.....x..U..9\r\n0070: 4C 93 8C 7F DA 7C 92 05   39 3A 99 F4 BD BA 6F E2  L.......9:....o.\r\n\n]\r\n' (<type 'str'>)

**Comment by ajinabraham** [comment]
Can you provide the apk that triggered this bug.

**Comment by ajinabraham** [comment]
No Followups received. So closing this issue.
