### ISSUE TITLE
File Read/Write Permission can also use integer values

### ISSUE THREAD

**Issue by ajinabraham** [ajinabraham/Mobile-Security-Framework-MobSF#82]
https://github.com/AndroBugs/AndroBugs_Framework/blob/master/androbugs.py#L2208-L2213
Bug pointed out by @AndroBugs
![screen shot 2015-11-12 at 21 38 23](https://cloud.githubusercontent.com/assets/4301109/11123154/6ba4307a-8984-11e5-9c59-816c57742f36.png)

**Comment by motazreda** [comment]
Just something we need to try not using regex for performance enhancement, thanks

**Comment by ajinabraham** [comment]
closing this here and adding this to static analyzer enhancements

**Comment by ajinabraham** [comment]
fixed
