### ISSUE TITLE
timed out waiting for /dev/.coldboot

### ISSUE THREAD

**Issue by code-scan** [ajinabraham/Mobile-Security-Framework-MobSF#83]
when i startup vbox Machine ,it output
```
 timed out waiting for /dev/.coldboot
```

**Comment by ajinabraham** [comment]
This happens when you start the VM after importing the OVA file?
I doubt your hardware supports the VM. Try changing the settings like acceleration or visualization and see if it's working.

**Comment by code-scan** [comment]
it's working,just for waiting a long time
