### ISSUE TITLE
[Dynamic Analysis] Android apps crash

### ISSUE THREAD

**Issue by bataille16** [ajinabraham/Mobile-Security-Framework-MobSF#84]
I am attempting to use the dynamic analysis tool for some standard android apks found on apkmirror. 
I am using java-oracle 7 and the setup (at least) seems to be correct. However, once the APK file is installed on the VM and it is time to run the app, it crashes and I get the famous "Unfortunately [app_name] has stopped. Every app I have tried to install uses API < 19, so I don't quite see what the problem is. Anyone encountered this problem before? Any insight?

For reference, I am attaching the log for my attempt to install and do a dynamic analysis of a Spotify apk found on apkmirror. 

Thanks for the help.

[spotify-mobsf-log.txt](https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/files/46459/spotify-mobsf-log.txt)

**Comment by ajinabraham** [comment]
Is this behavior seen in all apk or just spotify?
It might even possible that the APK is having some Anti-VM/ root detection capabilities. 
MobSF will take care of that for most of the apps but if it doesn't then you have to patch the apk or write an xposed module to bypass the checks.

Try looking into logcat logs. It may give you better information on what caused the crash.

**Comment by ajinabraham** [comment]
Also from Dynamic Analyzer window, issue the command
`shell am start -n com.spotify.music/com.spotify.music.MainActivity`

**Comment by ajinabraham** [comment]
No Followups received. So closing this issue.
