### ISSUE TITLE
JNI libs are not identified correctly.

### ISSUE THREAD

**Issue by inode-** [ajinabraham/Mobile-Security-Framework-MobSF#87]
Native libraries called from JAVA are not identified correctly. The result is "Native: false" and no check is done on the libraries.

If needed I can support with log etc.

**Comment by inode-** [comment]
Juste checked the code, the problem seem to be that MSF doesn't execute no test on native library on android.

**Comment by ajinabraham** [comment]
Thanks for pointing out. Adding this as an enhancement.

**Comment by ajinabraham** [comment]
fixed
