### ISSUE TITLE
APK Static scan : Not Analyzing 

### ISSUE THREAD

**Issue by Arunraj89** [ajinabraham/Mobile-Security-Framework-MobSF#89]
Hi i tried to scan an apk of 15MB using MobSF static, But it shows me an UI that 100% Uploaded ... and not proceeding to analyze the apk. When i cjecked back in CMD i saw the below response "[22/Dec/2015 23:15:38]"POST /Upload/ HTTP/1.1" 500 69322". Its look like 500 Error thrown. Help me out to scan the APK. Thanks

**Comment by ajinabraham** [comment]
paste the complete console log.

**Comment by Arunraj89** [comment]
Console Log : 

E:\Application Security\Framework\Mobile-Security-Framework-MobSF-master>python manage.py runserver

[INFO] Finding JDK Location in Windows....

[INFO] Oracle JDK Identified. Looking for JDK 1.7 or above

[INFO] Oracle Java (JDK >= 1.7) is installed!

[INFO] Finding JDK Location in Windows....

[INFO] Oracle JDK Identified. Looking for JDK 1.7 or above

[INFO] Oracle Java (JDK >= 1.7) is installed!
Performing system checks...

System check identified no issues (0 silenced).
December 22, 2015 - 23:42:26
Django version 1.8, using settings 'MobSF.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[INFO] Mobile Security Framework v0.8.8beta
[22/Dec/2015 23:42:38]"GET / HTTP/1.1" 200 7201
[22/Dec/2015 23:42:56]"POST /Upload/ HTTP/1.1" 500 69322

UI Screenshot: 
![apk issue](https://cloud.githubusercontent.com/assets/16404627/11962454/efc66044-a905-11e5-87be-31a1949fd978.jpg)

**Comment by ajinabraham** [comment]
Can you try with a different browser?

**Comment by Arunraj89** [comment]
I tried in FF and Chrome, In both I am getting same Error.

**Comment by ajinabraham** [comment]
Looks strange. So you are saying it's working fine for smaller APKs?
Is the APK publicly available so that I can test locally?

**Comment by Arunraj89** [comment]
ya https://goo.gl/T6fosL

**Comment by ajinabraham** [comment]
The APK file name after download will be `NetX360®_v2.0.1.14_apkpure.com.apk`
the `®` symbol is causing the problem, rename the file to something else and try again. It worked for me. Try that and let me know if it worked for you.

**Comment by Arunraj89** [comment]
Ya it's working Fine for me know... Thanks

**Comment by bugwrangler** [comment]
+1 nice caught!
