### ISSUE TITLE
Bluetooth Support in Dynamic Analysis

### ISSUE THREAD

**Issue by errbufferoverfl** [ajinabraham/Mobile-Security-Framework-MobSF#91]
Is there a way to connect to bluetooth devices through MobSF VM and use the dynamic analysis tool?

**Comment by ajinabraham** [comment]
You cannot do that from MobSF VM as it does not support bluetooth virtualization. The next version of the MobSF will contain instructions to set the Dynamic Analysis on a rooted device in addition to a VM. You have the capability to use bluetooth in that build.
