### ISSUE TITLE
Errno 2] No such file or directory

### ISSUE THREAD

**Issue by fr33wi11** [ajinabraham/Mobile-Security-Framework-MobSF#92]
Hi,

I am having following error when trying the dynamic analysis. 

Is this bug or am I missing something?

-----------

[Errno 2] No such file or directory
Request Method:	POST
Request URL:	http://127.0.0.1:8000/DynamicAnalyzer/
Django Version:	1.8
Exception Type:	OSError
Exception Value:	
[Errno 2] No such file or directory
Exception Location:	/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py in _execute_child, line 1335
Python Executable:	/usr/bin/python
Python Version:	2.7.10
Python Path:	
['/Users/editedUsername/MobSF',
 '/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg',
 '/Library/Python/2.7/site-packages/setuptools-14.3.1-py2.7.egg',
 '/Library/Python/2.7/site-packages/Twisted-10.2.0-py2.7-macosx-10.10-intel.egg',
 '/Library/Python/2.7/site-packages/drozer-2.3.4-py2.7.egg',
 '/Library/Python/2.7/site-packages/protobuf-3.0.0a1-py2.7.egg',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC',
 '/Library/Python/2.7/site-packages']

Track Back

Environment:

Request Method: POST
Request URL: http://127.0.0.1:8000/DynamicAnalyzer/

Django Version: 1.8
Python Version: 2.7.10
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'StaticAnalyzer',
 'DynamicAnalyzer')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware')

Traceback:
File "/Library/Python/2.7/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/Users/kashifsohail/MobSF/DynamicAnalyzer/views.py" in DynamicAnalyzer
  32.             RefreshVM(UUID,SUUID,VBOXEXE)
File "/Users/kashifsohail/MobSF/DynamicAnalyzer/views.py" in RefreshVM
  392.     subprocess.call(args)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py" in call
  522.     return Popen(*popenargs, **kwargs).wait()
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py" in __init__
  710.                                 errread, errwrite)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py" in _execute_child
  1335.                 raise child_exception

Exception Type: OSError at /DynamicAnalyzer/
Exception Value: [Errno 2] No such file or directory

**Comment by ajinabraham** [comment]
Did you followed the Wiki?
Looks like error occurred in RefreshVM(UUID,SUUID,VBOXEXE) 

Make sure that your virtualbox executable is available at this path: https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/blob/master/MobSF/settings.py#L117

The error occurred in https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/blob/master/DynamicAnalyzer/views.py#L389-L392

try putting a try catch and see what went wrong (If you are comfortable with python)
or wait till the next release when I add functionality to add more debug info.

**Comment by whitehatpanda** [comment]
Try the below solution to solve this problem:
1. pip install -r requirements.txt (maybe need sudo)
2. chmod -R /DynamicAnalyzer
3. In the MobSF/settings.py, check your path to VirtualBox: it might be /usr/local/bin instead of /usr/bin

**Comment by mrpinghe** [comment]
I had the same issue, and it turns out, it's just my VBoxManage binary location is at /usr/local/bin rather than /usr/bin, and neither your video nor the doc highlighted the need to investigate this particular value. Once I changed the path to the correct one, all is well. So... maybe update your config doc? :)

Thanks for the great tool though!

**Comment by ajinabraham** [comment]
This is fixed in master. https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/commit/e0aa0d1a57aaa76c68856ffa8395a98072a4be18

You can redownload master.
