### ISSUE TITLE
Report generation Error

### ISSUE THREAD

**Issue by Arunraj89** [ajinabraham/Mobile-Security-Framework-MobSF#93]
Hi Team, 

i run the scan on MAC OSX and got the result, but once i try to generate the PDF report it take me to the error page.

**Comment by ajinabraham** [comment]
You need to put the error logs here. Without that I cannot help you.

**Comment by ajinabraham** [comment]
Any updates here?

**Comment by ajinabraham** [comment]
Closing this as no follow ups received in 10 days.
