### ISSUE TITLE
"Don't Play Around. An Error just popped in!  MS-Windows OS system call failed."

### ISSUE THREAD

**Issue by thiruspark** [ajinabraham/Mobile-Security-Framework-MobSF#94]
Hi dear ones,
while scanning the android apk the following error arises,
"Don't Play Around. An Error just popped in!

MS-Windows OS system call failed."

i have installed latest versions of python, jdk, pip scripts components
below are the log, please help me in rectifying this issue

C:\Users\isms\Desktop\Thirumurugan\tools\Android testing\Mobile-Security-Fr
amework-MobSF-0.8.8.2>manage.py runserver

[INFO] Finding JDK Location in Windows....

[INFO] Oracle JDK Identified. Looking for JDK 1.7 or above

[ERROR] Cannot Run Process - [Error 2] The system cannot find the file specified

[ERROR] Oracle JDK 1.7 or above is not found!

[INFO] Finding JDK Location in Windows....

[INFO] Oracle JDK Identified. Looking for JDK 1.7 or above

[ERROR] Cannot Run Process - [Error 2] The system cannot find the file specified

[ERROR] Oracle JDK 1.7 or above is not found!
Performing system checks...

System check identified no issues (0 silenced).
January 13, 2016 - 17:44:39
Django version 1.8, using settings 'MobSF.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[INFO] MIME Type: application/vnd.android.package-archive FILE: myCams.apk
[13/Jan/2016 17:44:48]"POST /Upload/ HTTP/1.1" 200 133
[INFO] Starting Analysis on : myCams.apk
[INFO] Generating Hashes
[INFO] Unzipping
[INFO] Getting Hardcoded Certificates
[INFO] APK Extracted
[INFO] Getting Manifest from Binary
[INFO] AXML -> XML
[INFO] Parsing AndroidManifest.xml
[INFO] Extracting Manifest Data
[INFO] Manifest Analysis Started
[INFO] Formatting Permissions
[INFO] Reading Signer Certificate
[INFO] DEX -> JAR
[INFO] Running JAVA Path fix in Windows
C:\Users\cams_isms\Desktop\Thirumurugan\tools\Android testing\Mobile-Security-Fr
amework-MobSF-0.8.8.2\uploads\d194e38945abd0212cf66184a1fd4aa7\classes.jar exist
s, use --force to overwrite
[INFO] DEX -> SMALI

**Comment by ajinabraham** [comment]
From the above log it seems , either your JDK is not properly installed or it's not properly detected by MobSF
`[ERROR] Cannot Run Process - [Error 2] The system cannot find the file specified`

**Comment by ajinabraham** [comment]
Whats your JDK path?

**Comment by thiruspark** [comment]
Hi sir,
this is my jdk path
"C:\Program Files\Java\jdk1.8.0_66\bin\"

i have updated this path to settings.py file in the MobSF Folder too as

if platform.system()=="Windows":
    JAVA_PATH=java.FindJava()
    #JAVA_PATH='C:/Program Files/Java/jdk1.8.0_66/bin/'  # Use "/" instead of "\" for the path and the path should end with a "/".
    VBOX='C:\Program Files\Oracle\VirtualBox\VBoxManage.exe' #Path to VBoxManage.exe

**Comment by thiruspark** [comment]
Hi sir,
this is my jdk path
"C:\Program Files\Java\jdk1.8.0_66\bin\"i have updated this path to settings.py file in the MobSF Folder too asif platform.system()=="Windows":
 JAVA_PATH=java.FindJava()
 #JAVA_PATH='C:/Program Files/Java/jdk1.8.0_66/bin/' # Use "/" instead of "\" for the path and the path should end with a "/".
 VBOX='C:\Program Files\Oracle\VirtualBox\VBoxManage.exe' #Path to VBoxManage.exe

**Comment by thiruspark** [comment]
Hello sir,
i have reinstalled the fresh Mobsf and tried again, below are the console

C:\Users\cams_isms\Desktop\Thirumurugan\tools\Android testing\Mobile-Security-Fr
amework-MobSF-master>manage.py runserver 8080

[INFO] Finding JDK Location in Windows....

[INFO] Oracle JDK Identified. Looking for JDK 1.7 or above

[INFO] Oracle Java (JDK >= 1.7) is installed!

[INFO] Finding JDK Location in Windows....

[INFO] Oracle JDK Identified. Looking for JDK 1.7 or above

[INFO] Oracle Java (JDK >= 1.7) is installed!
Performing system checks...

System check identified no issues (0 silenced).
January 20, 2016 - 11:14:32
Django version 1.8, using settings 'MobSF.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CTRL-BREAK.
.
.
.
.
.
.
.
.
.(these things i have marked ..... because it cannot be retrived)
.
.
.
.
.
.
java.lang.IndexOutOfBoundsException: Index: 12, Size: 12
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at jd.fI.a(Unknown Source)
        at jd.fI.a(Unknown Source)
        at jd.af.b(Unknown Source)
        at jd.af.a(Unknown Source)
        at jd.af.a(Unknown Source)
        at jd.i.a(Unknown Source)
        at jd.ide.intellij.JavaDecompiler.decompile(Native Method)
        at jd.core.Decompiler.decompile(Decompiler.java:47)
        at jd.core.Decompiler.decompileToDir(Decompiler.java:56)
        at jd.core.Main.main(Main.java:16)
Decompiled 1705 classes
[INFO] Static Android Code Analysis Started
[INFO] Code Analysis Started on - C:\Users\cams_isms\Desktop\Thirumurugan\tools\
Android testing\Mobile-Security-Framework-MobSF-master\uploads/5a83c2ec558531aa8
7c3af5c4edcc955/java_source/
[INFO] Finished Code Analysis, Email and URL Extraction

[INFO] Generating Java and Smali Downloads
[INFO] Generating Downloads
[INFO] Zipping
[INFO] Zipping
[20/Jan/2016 11:21:50]"GET /StaticAnalyzer/?name=com.KCamsApp-1.apk&type=apk&che
cksum=5a83c2ec558531aa87c3af5c4edcc955 HTTP/1.1" 200 2960

**Comment by ajinabraham** [comment]
Everything looks working fine.
Don't worry about the jd-core decompiler execptions

```
java.lang.IndexOutOfBoundsException: Index: 12, Size: 12
at java.util.ArrayList.rangeCheck(ArrayList.java:653)
at java.util.ArrayList.get(ArrayList.java:429)
at jd.fI.a(Unknown Source)
at jd.fI.a(Unknown Source)
at jd.af.b(Unknown Source)
at jd.af.a(Unknown Source)
at jd.af.a(Unknown Source)
at jd.i.a(Unknown Source)
at jd.ide.intellij.JavaDecompiler.decompile(Native Method)
at jd.core.Decompiler.decompile(Decompiler.java:47)
at jd.core.Decompiler.decompileToDir(Decompiler.java:56)
at jd.core.Main.main(Main.java:16)
```

**Comment by thiruspark** [comment]
All are looking good only sir,
iam not bordering about jd-core decompiler execptions
but while scanning the apk i get the error again and again, please help

check the screenshots.

![1](https://cloud.githubusercontent.com/assets/16684238/12507973/220c1a2c-c11f-11e5-84c8-9eb47629c105.JPG)
![2](https://cloud.githubusercontent.com/assets/16684238/12508075/d10631a2-c11f-11e5-8dfd-d71b872f0287.JPG)
