### ISSUE TITLE
Unable to install an apk

### ISSUE THREAD

**Issue by abhishek1712** [ajinabraham/Mobile-Security-Framework-MobSF#95]
The VM is failing to install an apk, as I get continuous pop-ups stating :: 
Unfortunately, the applications has stopped working.
Even though, its gets installed, The pop continues on every initialization of every activity in the app.
Maybe its because of the custom ROM, coz the alert still says the application has problem due to the custom rom.
Great work @ the framework :+1: 
Pleasse fix it

**Comment by ajinabraham** [comment]
The reason could be that the application is detecting VM as a custom ROM. Find out the ROM detection code and patch it or wait for the next release of MobSF that supports a real device instead of VM.

Again thanks for your compliments.
