### ISSUE TITLE
ip is not visible in the IP Management.

### ISSUE THREAD

**Issue by tabriz83** [ajinabraham/Mobile-Security-Framework-MobSF#96]
HI, ajinabraham.

I have problem while performing steps of configuring dynamic analysis.

Guide : 
[<img alt="VM IP" src="https://cloud.githubusercontent.com/assets/4301109/9769219/794771da-5746-11e5-9d81-5549422aac71.png">](url)

Me :
[<img src ="http://i.imgur.com/JzXiyEq.png">](url)
**IP does not appear in the photo of the IP Management.**

Could you give us you advice on this problem?

**Comment by ajinabraham** [comment]
This is strange. You are sure you configured the VirtualBox Network Adapter 1 and 2 before booting VM?
https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/wiki/Documentation#steps-to-follow

**Comment by ajinabraham** [comment]
Any updates here?

**Comment by ajinabraham** [comment]
Closing this as no follow ups received in 10 days.

**Comment by Varoreina** [comment]
Hi ajinabraham, 

I have the same issue described above by tabriz83 reported on 5 Feb 2016. I literally cannot see the VM IP when booting the VM. Adapters 1 & 2 were properly configured before booting.
Can you help me here please?

**Comment by ajinabraham** [comment]
This is something beyond the project. Some issues with VirtualBox or your virtual network adapter configs. You should delete all your virtual adapters and try this: https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/6.-What-to-do-when-MobSF-VM-and-VirtualBox-Host-Only-Adapter-are-not-in-the-same-network-range

**Comment by dinglam** [comment]
![capture3](https://user-images.githubusercontent.com/8123823/33804971-8dda829e-ddeb-11e7-8034-9992872aad38.JPG)
I also have this problem
