### ISSUE TITLE
Upgrade JustTrustMe

### ISSUE THREAD

**Issue by anantshri** [ajinabraham/Mobile-Security-Framework-MobSF#97]
I can see JustTrustMe Apk is 5 months old, no versioning again makes it hard to pinpoint.
Project has had many updates https://github.com/Fuzion24/JustTrustMe

might make sense to upgrade your apk set.

**Comment by ajinabraham** [comment]
Yes, this make sense.e

**Comment by ajinabraham** [comment]
Done.
