### ISSUE TITLE
allow change in writable folder locations 

### ISSUE THREAD

**Issue by anantshri** [ajinabraham/Mobile-Security-Framework-MobSF#98]
can think of multiple scenario where this could be useful. Basically any folder where a write operation is performed should be outside of code base. 

i suggest ~/.mobsf/ folder as a location to store all data and configuration.

This would also include your db.sqlite3 file. I would suggest instead of packaging a db.sqlite3 file it should be created on first start or whenever its not found.

**Comment by ajinabraham** [comment]
all paths are configurable now: https://github.com/ajinabraham/Mobile-Security-Framework-MobSF/blob/nullcon/MobSF/settings.py#L85-L94
